// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretPostgresqlResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretPostgresqlResource{}
	_ resource.ResourceWithImportState = &DynamicSecretPostgresqlResource{}
)

type DynamicSecretPostgresqlResource struct {
	client *AkeylessClient
}

func NewDynamicSecretPostgresqlResource() resource.Resource {
	return &DynamicSecretPostgresqlResource{}
}

type DynamicSecretPostgresqlModel struct {
	CreationStatements types.String `tfsdk:"creation_statements"`
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	PasswordLength types.String `tfsdk:"password_length"`
	PostgresqlDbName types.String `tfsdk:"postgresql_db_name"`
	PostgresqlHost types.String `tfsdk:"postgresql_host"`
	PostgresqlPassword types.String `tfsdk:"postgresql_password"`
	PostgresqlPort types.String `tfsdk:"postgresql_port"`
	PostgresqlUsername types.String `tfsdk:"postgresql_username"`
	ProducerEncryptionKey types.String `tfsdk:"producer_encryption_key"`
	RevocationStatement types.String `tfsdk:"revocation_statement"`
	SecureAccessDelay types.Int64 `tfsdk:"secure_access_delay"`
	Ssl types.Bool `tfsdk:"ssl"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretPostgresqlResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_postgresql"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"creation_statements": schema.StringAttribute{
				Description: "PostgreSQL creation statements",
				Optional: true,
			},
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"postgresql_db_name": schema.StringAttribute{
				Description: "PostgreSQL DB Name",
				Optional: true,
			},
			"postgresql_host": schema.StringAttribute{
				Description: "PostgreSQL host",
				Optional: true,
			},
			"postgresql_password": schema.StringAttribute{
				Description: "PostgreSQL admin password",
				Optional: true,
				Sensitive: true,
			},
			"postgresql_port": schema.StringAttribute{
				Description: "PostgreSQL port (default: 5432)",
				Optional: true,
			},
			"postgresql_username": schema.StringAttribute{
				Description: "PostgreSQL admin username",
				Optional: true,
			},
			"producer_encryption_key": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"revocation_statement": schema.StringAttribute{
				Description: "PostgreSQL Revocation statements",
				Optional: true,
			},
			"secure_access_delay": schema.Int64Attribute{
				Description: "The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds",
				Optional: true,
			},
			"ssl": schema.BoolAttribute{
				Description: "Enable SSL connection",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretPostgresqlResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretPostgresqlResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretPostgresqlModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-postgresql")

	// Set creation_statements
	if !plan.CreationStatements.IsNull() && !plan.CreationStatements.IsUnknown() {
		v := plan.CreationStatements.ValueString()
		body.SetCreationStatements(&v)
	}

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set postgresql_db_name
	if !plan.PostgresqlDbName.IsNull() && !plan.PostgresqlDbName.IsUnknown() {
		v := plan.PostgresqlDbName.ValueString()
		body.SetPostgresqlDbName(&v)
	}

	// Set postgresql_host
	if !plan.PostgresqlHost.IsNull() && !plan.PostgresqlHost.IsUnknown() {
		v := plan.PostgresqlHost.ValueString()
		body.SetPostgresqlHost(&v)
	}

	// Set postgresql_password
	if !plan.PostgresqlPassword.IsNull() && !plan.PostgresqlPassword.IsUnknown() {
		v := plan.PostgresqlPassword.ValueString()
		body.SetPostgresqlPassword(&v)
	}

	// Set postgresql_port
	if !plan.PostgresqlPort.IsNull() && !plan.PostgresqlPort.IsUnknown() {
		v := plan.PostgresqlPort.ValueString()
		body.SetPostgresqlPort(&v)
	}

	// Set postgresql_username
	if !plan.PostgresqlUsername.IsNull() && !plan.PostgresqlUsername.IsUnknown() {
		v := plan.PostgresqlUsername.ValueString()
		body.SetPostgresqlUsername(&v)
	}

	// Set producer_encryption_key
	if !plan.ProducerEncryptionKey.IsNull() && !plan.ProducerEncryptionKey.IsUnknown() {
		v := plan.ProducerEncryptionKey.ValueString()
		body.SetProducerEncryptionKey(&v)
	}

	// Set revocation_statement
	if !plan.RevocationStatement.IsNull() && !plan.RevocationStatement.IsUnknown() {
		v := plan.RevocationStatement.ValueString()
		body.SetRevocationStatement(&v)
	}

	// Set secure_access_delay
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}

	// Set ssl
	if !plan.Ssl.IsNull() && !plan.Ssl.IsUnknown() {
		v := plan.Ssl.ValueBool()
		body.SetSsl(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretPostgresql")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretPostgresql", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretPostgresqlResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretPostgresqlModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretPostgresqlResource) readResource(ctx context.Context, id string) (DynamicSecretPostgresqlModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretPostgresqlModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretPostgresql", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretPostgresqlResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretPostgresqlModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-postgresql")
	if !plan.CreationStatements.IsNull() && !plan.CreationStatements.IsUnknown() {
		v := plan.CreationStatements.ValueString()
		body.SetCreationStatements(&v)
	}
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.PostgresqlDbName.IsNull() && !plan.PostgresqlDbName.IsUnknown() {
		v := plan.PostgresqlDbName.ValueString()
		body.SetPostgresqlDbName(&v)
	}
	if !plan.PostgresqlHost.IsNull() && !plan.PostgresqlHost.IsUnknown() {
		v := plan.PostgresqlHost.ValueString()
		body.SetPostgresqlHost(&v)
	}
	if !plan.PostgresqlPassword.IsNull() && !plan.PostgresqlPassword.IsUnknown() {
		v := plan.PostgresqlPassword.ValueString()
		body.SetPostgresqlPassword(&v)
	}
	if !plan.PostgresqlPort.IsNull() && !plan.PostgresqlPort.IsUnknown() {
		v := plan.PostgresqlPort.ValueString()
		body.SetPostgresqlPort(&v)
	}
	if !plan.PostgresqlUsername.IsNull() && !plan.PostgresqlUsername.IsUnknown() {
		v := plan.PostgresqlUsername.ValueString()
		body.SetPostgresqlUsername(&v)
	}
	if !plan.ProducerEncryptionKey.IsNull() && !plan.ProducerEncryptionKey.IsUnknown() {
		v := plan.ProducerEncryptionKey.ValueString()
		body.SetProducerEncryptionKey(&v)
	}
	if !plan.RevocationStatement.IsNull() && !plan.RevocationStatement.IsUnknown() {
		v := plan.RevocationStatement.ValueString()
		body.SetRevocationStatement(&v)
	}
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}
	if !plan.Ssl.IsNull() && !plan.Ssl.IsUnknown() {
		v := plan.Ssl.ValueBool()
		body.SetSsl(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretPostgresql")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretPostgresql", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretPostgresqlResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretPostgresqlModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretPostgresql", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretPostgresql", err.Error())
		return
	}
}

func (r *DynamicSecretPostgresqlResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
