// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &ClassicKeyResource{}
	_ resource.ResourceWithConfigure   = &ClassicKeyResource{}
	_ resource.ResourceWithImportState = &ClassicKeyResource{}
)

type ClassicKeyResource struct {
	client *AkeylessClient
}

func NewClassicKeyResource() resource.Resource {
	return &ClassicKeyResource{}
}

type ClassicKeyModel struct {
	Alg types.String `tfsdk:"alg"`
	AutoRotate types.String `tfsdk:"auto_rotate"`
	CertFileData types.String `tfsdk:"cert_file_data"`
	CertificateCommonName types.String `tfsdk:"certificate_common_name"`
	CertificateCountry types.String `tfsdk:"certificate_country"`
	CertificateDigestAlgo types.String `tfsdk:"certificate_digest_algo"`
	CertificateFormat types.String `tfsdk:"certificate_format"`
	CertificateLocality types.String `tfsdk:"certificate_locality"`
	CertificateOrganization types.String `tfsdk:"certificate_organization"`
	CertificateProvince types.String `tfsdk:"certificate_province"`
	CertificateTtl types.Int64 `tfsdk:"certificate_ttl"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ExpirationEventIn types.Set `tfsdk:"expiration_event_in"`
	GenerateSelfSignedCertificate types.Bool `tfsdk:"generate_self_signed_certificate"`
	GpgAlg types.String `tfsdk:"gpg_alg"`
	HashAlgorithm types.String `tfsdk:"hash_algorithm"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	KeyData types.String `tfsdk:"key_data"`
	Name types.String `tfsdk:"name"`
	ProtectionKeyName types.String `tfsdk:"protection_key_name"`
	RotationEventIn types.Set `tfsdk:"rotation_event_in"`
	RotationInterval types.String `tfsdk:"rotation_interval"`
	Tags types.Set `tfsdk:"tags"`
}

func (r *ClassicKeyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_classic_key"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"alg": schema.StringAttribute{
				Description: "Classic key algorithm: AES128GCM, AES256GCM, AES128SIV, AES256SIV, RSA1024, RSA2048, RSA3072, RSA4096, EC256, EC384",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"auto_rotate": schema.StringAttribute{
				Description: "Whether to automatically rotate every rotation_interval days, or disable existing automatic rotation [true/false]",
				Optional: true,
			},
			"cert_file_data": schema.StringAttribute{
				Description: "Certificate PEM data (for RSA keys)",
				Optional: true,
				Sensitive: true,
			},
			"certificate_common_name": schema.StringAttribute{
				Description: "Common name for generated certificate",
				Optional: true,
			},
			"certificate_country": schema.StringAttribute{
				Description: "Country for generated certificate",
				Optional: true,
			},
			"certificate_digest_algo": schema.StringAttribute{
				Description: "Digest algorithm to be used for the certificate key signing.",
				Optional: true,
			},
			"certificate_format": schema.StringAttribute{
				Description: "",
				Optional: true,
			},
			"certificate_locality": schema.StringAttribute{
				Description: "Locality for generated certificate",
				Optional: true,
			},
			"certificate_organization": schema.StringAttribute{
				Description: "Organization for generated certificate",
				Optional: true,
			},
			"certificate_province": schema.StringAttribute{
				Description: "Province for generated certificate",
				Optional: true,
			},
			"certificate_ttl": schema.Int64Attribute{
				Description: "Certificate TTL in days",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Key description",
				Optional: true,
			},
			"expiration_event_in": schema.SetAttribute{
				Description: "How many days before the expiration of the certificate would you like to be notified.",
				Optional: true,
				ElementType: types.StringType{},
			},
			"generate_self_signed_certificate": schema.BoolAttribute{
				Description: "Generate a self-signed certificate",
				Optional: true,
			},
			"gpg_alg": schema.StringAttribute{
				Description: "gpg alg: Relevant only if GPG key type selected; options: [RSA1024, RSA2048, RSA3072, RSA4096, Ed25519]",
				Optional: true,
			},
			"hash_algorithm": schema.StringAttribute{
				Description: "Specifies the hash algorithm used for the encryption key's operations, available options: [SHA256, SHA384, SHA512]",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"key_data": schema.StringAttribute{
				Description: "Key material (base64 encoded)",
				Optional: true,
				Sensitive: true,
			},
			"name": schema.StringAttribute{
				Description: "ClassicKey name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"protection_key_name": schema.StringAttribute{
				Description: "Encryption key used to protect this key",
				Optional: true,
			},
			"rotation_event_in": schema.SetAttribute{
				Description: "How many days before the rotation of the item would you like to be notified",
				Optional: true,
				ElementType: types.StringType{},
			},
			"rotation_interval": schema.StringAttribute{
				Description: "The number of days to wait between every automatic rotation (1-365)",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the key",
				Optional: true,
				ElementType: types.StringType{},
			},
		},
	}
}

func (r *ClassicKeyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *ClassicKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ClassicKeyModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/create-classic-key")

	// Set alg
	if !plan.Alg.IsNull() && !plan.Alg.IsUnknown() {
		v := plan.Alg.ValueString()
		body.SetAlg(&v)
	}

	// Set auto_rotate
	if !plan.AutoRotate.IsNull() && !plan.AutoRotate.IsUnknown() {
		v := plan.AutoRotate.ValueString()
		body.SetAutoRotate(&v)
	}

	// Set cert_file_data
	if !plan.CertFileData.IsNull() && !plan.CertFileData.IsUnknown() {
		v := plan.CertFileData.ValueString()
		body.SetCertFileData(&v)
	}

	// Set certificate_common_name
	if !plan.CertificateCommonName.IsNull() && !plan.CertificateCommonName.IsUnknown() {
		v := plan.CertificateCommonName.ValueString()
		body.SetCertificateCommonName(&v)
	}

	// Set certificate_country
	if !plan.CertificateCountry.IsNull() && !plan.CertificateCountry.IsUnknown() {
		v := plan.CertificateCountry.ValueString()
		body.SetCertificateCountry(&v)
	}

	// Set certificate_digest_algo
	if !plan.CertificateDigestAlgo.IsNull() && !plan.CertificateDigestAlgo.IsUnknown() {
		v := plan.CertificateDigestAlgo.ValueString()
		body.SetCertificateDigestAlgo(&v)
	}

	// Set certificate_format
	if !plan.CertificateFormat.IsNull() && !plan.CertificateFormat.IsUnknown() {
		v := plan.CertificateFormat.ValueString()
		body.SetCertificateFormat(&v)
	}

	// Set certificate_locality
	if !plan.CertificateLocality.IsNull() && !plan.CertificateLocality.IsUnknown() {
		v := plan.CertificateLocality.ValueString()
		body.SetCertificateLocality(&v)
	}

	// Set certificate_organization
	if !plan.CertificateOrganization.IsNull() && !plan.CertificateOrganization.IsUnknown() {
		v := plan.CertificateOrganization.ValueString()
		body.SetCertificateOrganization(&v)
	}

	// Set certificate_province
	if !plan.CertificateProvince.IsNull() && !plan.CertificateProvince.IsUnknown() {
		v := plan.CertificateProvince.ValueString()
		body.SetCertificateProvince(&v)
	}

	// Set certificate_ttl
	if !plan.CertificateTtl.IsNull() && !plan.CertificateTtl.IsUnknown() {
		v := plan.CertificateTtl.ValueInt64()
		body.SetCertificateTtl(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set expiration_event_in
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}

	// Set generate_self_signed_certificate
	if !plan.GenerateSelfSignedCertificate.IsNull() && !plan.GenerateSelfSignedCertificate.IsUnknown() {
		v := plan.GenerateSelfSignedCertificate.ValueBool()
		body.SetGenerateSelfSignedCertificate(&v)
	}

	// Set gpg_alg
	if !plan.GpgAlg.IsNull() && !plan.GpgAlg.IsUnknown() {
		v := plan.GpgAlg.ValueString()
		body.SetGpgAlg(&v)
	}

	// Set hash_algorithm
	if !plan.HashAlgorithm.IsNull() && !plan.HashAlgorithm.IsUnknown() {
		v := plan.HashAlgorithm.ValueString()
		body.SetHashAlgorithm(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set key_data
	if !plan.KeyData.IsNull() && !plan.KeyData.IsUnknown() {
		v := plan.KeyData.ValueString()
		body.SetKeyData(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set protection_key_name
	if !plan.ProtectionKeyName.IsNull() && !plan.ProtectionKeyName.IsUnknown() {
		v := plan.ProtectionKeyName.ValueString()
		body.SetProtectionKeyName(&v)
	}

	// Set rotation_event_in
	if !plan.RotationEventIn.IsNull() && !plan.RotationEventIn.IsUnknown() {
		body.SetRotationEventIn(expandStringSet(ctx, plan.RotationEventIn))
	}

	// Set rotation_interval
	if !plan.RotationInterval.IsNull() && !plan.RotationInterval.IsUnknown() {
		v := plan.RotationInterval.ValueString()
		body.SetRotationInterval(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	tflog.Debug(ctx, "Creating ClassicKey")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating ClassicKey", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *ClassicKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ClassicKeyModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *ClassicKeyResource) readResource(ctx context.Context, id string) (ClassicKeyModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state ClassicKeyModel

	body := akeyless_api.NewReadBody("/describe-item")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading ClassicKey", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "classic_key_details.algorithm"); ok {
		state.Alg = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_metadata"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "protection_key_name"); ok {
		state.ProtectionKeyName = types.StringValue(v)
	}
	if v, ok := GetNestedStringSlice(result, "item_tags"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.Tags = setVal
	}

	return state, diags
}

func (r *ClassicKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ClassicKeyModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/update-item")
	if !plan.Alg.IsNull() && !plan.Alg.IsUnknown() {
		v := plan.Alg.ValueString()
		body.SetAlg(&v)
	}
	if !plan.AutoRotate.IsNull() && !plan.AutoRotate.IsUnknown() {
		v := plan.AutoRotate.ValueString()
		body.SetAutoRotate(&v)
	}
	if !plan.CertFileData.IsNull() && !plan.CertFileData.IsUnknown() {
		v := plan.CertFileData.ValueString()
		body.SetCertFileData(&v)
	}
	if !plan.CertificateCommonName.IsNull() && !plan.CertificateCommonName.IsUnknown() {
		v := plan.CertificateCommonName.ValueString()
		body.SetCertificateCommonName(&v)
	}
	if !plan.CertificateCountry.IsNull() && !plan.CertificateCountry.IsUnknown() {
		v := plan.CertificateCountry.ValueString()
		body.SetCertificateCountry(&v)
	}
	if !plan.CertificateDigestAlgo.IsNull() && !plan.CertificateDigestAlgo.IsUnknown() {
		v := plan.CertificateDigestAlgo.ValueString()
		body.SetCertificateDigestAlgo(&v)
	}
	if !plan.CertificateFormat.IsNull() && !plan.CertificateFormat.IsUnknown() {
		v := plan.CertificateFormat.ValueString()
		body.SetCertificateFormat(&v)
	}
	if !plan.CertificateLocality.IsNull() && !plan.CertificateLocality.IsUnknown() {
		v := plan.CertificateLocality.ValueString()
		body.SetCertificateLocality(&v)
	}
	if !plan.CertificateOrganization.IsNull() && !plan.CertificateOrganization.IsUnknown() {
		v := plan.CertificateOrganization.ValueString()
		body.SetCertificateOrganization(&v)
	}
	if !plan.CertificateProvince.IsNull() && !plan.CertificateProvince.IsUnknown() {
		v := plan.CertificateProvince.ValueString()
		body.SetCertificateProvince(&v)
	}
	if !plan.CertificateTtl.IsNull() && !plan.CertificateTtl.IsUnknown() {
		v := plan.CertificateTtl.ValueInt64()
		body.SetCertificateTtl(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}
	if !plan.GenerateSelfSignedCertificate.IsNull() && !plan.GenerateSelfSignedCertificate.IsUnknown() {
		v := plan.GenerateSelfSignedCertificate.ValueBool()
		body.SetGenerateSelfSignedCertificate(&v)
	}
	if !plan.GpgAlg.IsNull() && !plan.GpgAlg.IsUnknown() {
		v := plan.GpgAlg.ValueString()
		body.SetGpgAlg(&v)
	}
	if !plan.HashAlgorithm.IsNull() && !plan.HashAlgorithm.IsUnknown() {
		v := plan.HashAlgorithm.ValueString()
		body.SetHashAlgorithm(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.KeyData.IsNull() && !plan.KeyData.IsUnknown() {
		v := plan.KeyData.ValueString()
		body.SetKeyData(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProtectionKeyName.IsNull() && !plan.ProtectionKeyName.IsUnknown() {
		v := plan.ProtectionKeyName.ValueString()
		body.SetProtectionKeyName(&v)
	}
	if !plan.RotationEventIn.IsNull() && !plan.RotationEventIn.IsUnknown() {
		body.SetRotationEventIn(expandStringSet(ctx, plan.RotationEventIn))
	}
	if !plan.RotationInterval.IsNull() && !plan.RotationInterval.IsUnknown() {
		v := plan.RotationInterval.ValueString()
		body.SetRotationInterval(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	tflog.Debug(ctx, "Updating ClassicKey")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating ClassicKey", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *ClassicKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ClassicKeyModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-item")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting ClassicKey", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting ClassicKey", err.Error())
		return
	}
}

func (r *ClassicKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
