// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &GatewayAllowedAccessResource{}
	_ resource.ResourceWithConfigure   = &GatewayAllowedAccessResource{}
	_ resource.ResourceWithImportState = &GatewayAllowedAccessResource{}
)

type GatewayAllowedAccessResource struct {
	client *AkeylessClient
}

func NewGatewayAllowedAccessResource() resource.Resource {
	return &GatewayAllowedAccessResource{}
}

type GatewayAllowedAccessModel struct {
	SubClaimsCaseInsensitive types.Bool `tfsdk:"SubClaimsCaseInsensitive"`
	AccessId types.String `tfsdk:"access_id"`
	CaseSensitive types.String `tfsdk:"case_sensitive"`
	Description types.String `tfsdk:"description"`
	Name types.String `tfsdk:"name"`
	Permissions types.String `tfsdk:"permissions"`
	SubClaims types.Map `tfsdk:"sub_claims"`
}

func (r *GatewayAllowedAccessResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_allowed_access"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"SubClaimsCaseInsensitive": schema.BoolAttribute{
				Description: "",
				Optional: true,
			},
			"access_id": schema.StringAttribute{
				Description: "The access ID to attach to this allowed access",
				Required: true,
			},
			"case_sensitive": schema.StringAttribute{
				Description: "Treat sub claims as case-sensitive [true/false]",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Allowed access description",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Allowed access name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"permissions": schema.StringAttribute{
				Description: "Comma-separated list of permissions: defaults, targets, classic_keys, automatic_migration, ldap_auth, dynamic_secret, k8s_auth, log_forwarding, zero_knowledge_encryption, rotated_secret, caching, event_forwarding, admin, kmip, general, rotate_secret_value",
				Optional: true,
			},
			"sub_claims": schema.MapAttribute{
				Description: "Key/val of sub claims, e.g. group=admins,developers",
				Optional: true,
				ElementType: types.StringType{},
			},
		},
	}
}

func (r *GatewayAllowedAccessResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *GatewayAllowedAccessResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewayAllowedAccessModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/gateway-create-allowed-access")

	// Set SubClaimsCaseInsensitive
	if !plan.SubClaimsCaseInsensitive.IsNull() && !plan.SubClaimsCaseInsensitive.IsUnknown() {
		v := plan.SubClaimsCaseInsensitive.ValueBool()
		body.SetSubClaimsCaseInsensitive(&v)
	}

	// Set access_id
	if !plan.AccessId.IsNull() && !plan.AccessId.IsUnknown() {
		v := plan.AccessId.ValueString()
		body.SetAccessId(&v)
	}

	// Set case_sensitive
	if !plan.CaseSensitive.IsNull() && !plan.CaseSensitive.IsUnknown() {
		v := plan.CaseSensitive.ValueString()
		body.SetCaseSensitive(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set permissions
	if !plan.Permissions.IsNull() && !plan.Permissions.IsUnknown() {
		v := plan.Permissions.ValueString()
		body.SetPermissions(&v)
	}

	// Set sub_claims
	if !plan.SubClaims.IsNull() && !plan.SubClaims.IsUnknown() {
		// TODO: handle SubClaims (types.Map)
	}

	tflog.Debug(ctx, "Creating GatewayAllowedAccess")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating GatewayAllowedAccess", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *GatewayAllowedAccessResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewayAllowedAccessModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *GatewayAllowedAccessResource) readResource(ctx context.Context, id string) (GatewayAllowedAccessModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state GatewayAllowedAccessModel

	body := akeyless_api.NewReadBody("/gateway-get-allowed-access")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading GatewayAllowedAccess", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "access_id"); ok {
		state.AccessId = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "permissions"); ok {
		state.Permissions = types.StringValue(v)
	}
	// TODO: handle SubClaims (types.Map) from "sub_claims"

	return state, diags
}

func (r *GatewayAllowedAccessResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewayAllowedAccessModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/gateway-update-allowed-access")
	if !plan.SubClaimsCaseInsensitive.IsNull() && !plan.SubClaimsCaseInsensitive.IsUnknown() {
		v := plan.SubClaimsCaseInsensitive.ValueBool()
		body.SetSubClaimsCaseInsensitive(&v)
	}
	if !plan.AccessId.IsNull() && !plan.AccessId.IsUnknown() {
		v := plan.AccessId.ValueString()
		body.SetAccessId(&v)
	}
	if !plan.CaseSensitive.IsNull() && !plan.CaseSensitive.IsUnknown() {
		v := plan.CaseSensitive.ValueString()
		body.SetCaseSensitive(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.Permissions.IsNull() && !plan.Permissions.IsUnknown() {
		v := plan.Permissions.ValueString()
		body.SetPermissions(&v)
	}
	if !plan.SubClaims.IsNull() && !plan.SubClaims.IsUnknown() {
		// TODO: handle SubClaims (types.Map)
	}

	tflog.Debug(ctx, "Updating GatewayAllowedAccess")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating GatewayAllowedAccess", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *GatewayAllowedAccessResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewayAllowedAccessModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/gateway-delete-allowed-access")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting GatewayAllowedAccess", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting GatewayAllowedAccess", err.Error())
		return
	}
}

func (r *GatewayAllowedAccessResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
