// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretMysqlResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretMysqlResource{}
	_ resource.ResourceWithImportState = &DynamicSecretMysqlResource{}
)

type DynamicSecretMysqlResource struct {
	client *AkeylessClient
}

func NewDynamicSecretMysqlResource() resource.Resource {
	return &DynamicSecretMysqlResource{}
}

type DynamicSecretMysqlModel struct {
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DbServerCertificates types.String `tfsdk:"db_server_certificates"`
	DbServerName types.String `tfsdk:"db_server_name"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	MysqlDbname types.String `tfsdk:"mysql_dbname"`
	MysqlHost types.String `tfsdk:"mysql_host"`
	MysqlPassword types.String `tfsdk:"mysql_password"`
	MysqlPort types.String `tfsdk:"mysql_port"`
	MysqlRevocationStatements types.String `tfsdk:"mysql_revocation_statements"`
	MysqlScreationStatements types.String `tfsdk:"mysql_screation_statements"`
	MysqlUsername types.String `tfsdk:"mysql_username"`
	Name types.String `tfsdk:"name"`
	PasswordLength types.String `tfsdk:"password_length"`
	ProducerEncryptionKeyName types.String `tfsdk:"producer_encryption_key_name"`
	SecureAccessDelay types.Int64 `tfsdk:"secure_access_delay"`
	Ssl types.Bool `tfsdk:"ssl"`
	SslCertificate types.String `tfsdk:"ssl_certificate"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretMysqlResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_mysql"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"db_server_certificates": schema.StringAttribute{
				Description: "Database server certificates (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"db_server_name": schema.StringAttribute{
				Description: "Database server name for TLS verification",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"mysql_dbname": schema.StringAttribute{
				Description: "MySQL database name",
				Optional: true,
			},
			"mysql_host": schema.StringAttribute{
				Description: "MySQL host",
				Optional: true,
			},
			"mysql_password": schema.StringAttribute{
				Description: "MySQL admin password",
				Optional: true,
				Sensitive: true,
			},
			"mysql_port": schema.StringAttribute{
				Description: "MySQL port (default: 3306)",
				Optional: true,
			},
			"mysql_revocation_statements": schema.StringAttribute{
				Description: "MySQL revocation statements",
				Optional: true,
			},
			"mysql_screation_statements": schema.StringAttribute{
				Description: "MySQL Creation statements",
				Optional: true,
			},
			"mysql_username": schema.StringAttribute{
				Description: "MySQL admin username",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"producer_encryption_key_name": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"secure_access_delay": schema.Int64Attribute{
				Description: "The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds",
				Optional: true,
			},
			"ssl": schema.BoolAttribute{
				Description: "Enable SSL connection",
				Optional: true,
			},
			"ssl_certificate": schema.StringAttribute{
				Description: "SSL certificate (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretMysqlResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretMysqlResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretMysqlModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-mysql")

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set db_server_certificates
	if !plan.DbServerCertificates.IsNull() && !plan.DbServerCertificates.IsUnknown() {
		v := plan.DbServerCertificates.ValueString()
		body.SetDbServerCertificates(&v)
	}

	// Set db_server_name
	if !plan.DbServerName.IsNull() && !plan.DbServerName.IsUnknown() {
		v := plan.DbServerName.ValueString()
		body.SetDbServerName(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set mysql_dbname
	if !plan.MysqlDbname.IsNull() && !plan.MysqlDbname.IsUnknown() {
		v := plan.MysqlDbname.ValueString()
		body.SetMysqlDbname(&v)
	}

	// Set mysql_host
	if !plan.MysqlHost.IsNull() && !plan.MysqlHost.IsUnknown() {
		v := plan.MysqlHost.ValueString()
		body.SetMysqlHost(&v)
	}

	// Set mysql_password
	if !plan.MysqlPassword.IsNull() && !plan.MysqlPassword.IsUnknown() {
		v := plan.MysqlPassword.ValueString()
		body.SetMysqlPassword(&v)
	}

	// Set mysql_port
	if !plan.MysqlPort.IsNull() && !plan.MysqlPort.IsUnknown() {
		v := plan.MysqlPort.ValueString()
		body.SetMysqlPort(&v)
	}

	// Set mysql_revocation_statements
	if !plan.MysqlRevocationStatements.IsNull() && !plan.MysqlRevocationStatements.IsUnknown() {
		v := plan.MysqlRevocationStatements.ValueString()
		body.SetMysqlRevocationStatements(&v)
	}

	// Set mysql_screation_statements
	if !plan.MysqlScreationStatements.IsNull() && !plan.MysqlScreationStatements.IsUnknown() {
		v := plan.MysqlScreationStatements.ValueString()
		body.SetMysqlScreationStatements(&v)
	}

	// Set mysql_username
	if !plan.MysqlUsername.IsNull() && !plan.MysqlUsername.IsUnknown() {
		v := plan.MysqlUsername.ValueString()
		body.SetMysqlUsername(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set producer_encryption_key_name
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}

	// Set secure_access_delay
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}

	// Set ssl
	if !plan.Ssl.IsNull() && !plan.Ssl.IsUnknown() {
		v := plan.Ssl.ValueBool()
		body.SetSsl(&v)
	}

	// Set ssl_certificate
	if !plan.SslCertificate.IsNull() && !plan.SslCertificate.IsUnknown() {
		v := plan.SslCertificate.ValueString()
		body.SetSslCertificate(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretMysql")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretMysql", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretMysqlResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretMysqlModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretMysqlResource) readResource(ctx context.Context, id string) (DynamicSecretMysqlModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretMysqlModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretMysql", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretMysqlResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretMysqlModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-mysql")
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DbServerCertificates.IsNull() && !plan.DbServerCertificates.IsUnknown() {
		v := plan.DbServerCertificates.ValueString()
		body.SetDbServerCertificates(&v)
	}
	if !plan.DbServerName.IsNull() && !plan.DbServerName.IsUnknown() {
		v := plan.DbServerName.ValueString()
		body.SetDbServerName(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.MysqlDbname.IsNull() && !plan.MysqlDbname.IsUnknown() {
		v := plan.MysqlDbname.ValueString()
		body.SetMysqlDbname(&v)
	}
	if !plan.MysqlHost.IsNull() && !plan.MysqlHost.IsUnknown() {
		v := plan.MysqlHost.ValueString()
		body.SetMysqlHost(&v)
	}
	if !plan.MysqlPassword.IsNull() && !plan.MysqlPassword.IsUnknown() {
		v := plan.MysqlPassword.ValueString()
		body.SetMysqlPassword(&v)
	}
	if !plan.MysqlPort.IsNull() && !plan.MysqlPort.IsUnknown() {
		v := plan.MysqlPort.ValueString()
		body.SetMysqlPort(&v)
	}
	if !plan.MysqlRevocationStatements.IsNull() && !plan.MysqlRevocationStatements.IsUnknown() {
		v := plan.MysqlRevocationStatements.ValueString()
		body.SetMysqlRevocationStatements(&v)
	}
	if !plan.MysqlScreationStatements.IsNull() && !plan.MysqlScreationStatements.IsUnknown() {
		v := plan.MysqlScreationStatements.ValueString()
		body.SetMysqlScreationStatements(&v)
	}
	if !plan.MysqlUsername.IsNull() && !plan.MysqlUsername.IsUnknown() {
		v := plan.MysqlUsername.ValueString()
		body.SetMysqlUsername(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}
	if !plan.Ssl.IsNull() && !plan.Ssl.IsUnknown() {
		v := plan.Ssl.ValueBool()
		body.SetSsl(&v)
	}
	if !plan.SslCertificate.IsNull() && !plan.SslCertificate.IsUnknown() {
		v := plan.SslCertificate.ValueString()
		body.SetSslCertificate(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretMysql")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretMysql", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretMysqlResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretMysqlModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretMysql", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretMysql", err.Error())
		return
	}
}

func (r *DynamicSecretMysqlResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
