// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &KmipClientResource{}
	_ resource.ResourceWithConfigure   = &KmipClientResource{}
	_ resource.ResourceWithImportState = &KmipClientResource{}
)

type KmipClientResource struct {
	client *AkeylessClient
}

func NewKmipClientResource() resource.Resource {
	return &KmipClientResource{}
}

type KmipClientModel struct {
	ActivateKeysOnCreation types.String `tfsdk:"activate_keys_on_creation"`
	CertificateTtl types.Int64 `tfsdk:"certificate_ttl"`
	Name types.String `tfsdk:"name"`
}

func (r *KmipClientResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_kmip_client"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"activate_keys_on_creation": schema.StringAttribute{
				Description: "If set to 'true', newly created keys on the client will be set to an 'active' state",
				Optional: true,
			},
			"certificate_ttl": schema.Int64Attribute{
				Description: "Client certificate TTL in days",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Client name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (r *KmipClientResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *KmipClientResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan KmipClientModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/kmip-create-client")

	// Set activate_keys_on_creation
	if !plan.ActivateKeysOnCreation.IsNull() && !plan.ActivateKeysOnCreation.IsUnknown() {
		v := plan.ActivateKeysOnCreation.ValueString()
		body.SetActivateKeysOnCreation(&v)
	}

	// Set certificate_ttl
	if !plan.CertificateTtl.IsNull() && !plan.CertificateTtl.IsUnknown() {
		v := plan.CertificateTtl.ValueInt64()
		body.SetCertificateTtl(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	tflog.Debug(ctx, "Creating KmipClient")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating KmipClient", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *KmipClientResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state KmipClientModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *KmipClientResource) readResource(ctx context.Context, id string) (KmipClientModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state KmipClientModel

	body := akeyless_api.NewReadBody("/kmip-get-client")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading KmipClient", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	// TODO: state.ActivateKeysOnCreation = ... // no read_mapping defined
	// TODO: state.CertificateTtl = ... // no read_mapping defined
	// TODO: state.Name = ... // no read_mapping defined
	_ = result

	return state, diags
}

func (r *KmipClientResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError(
		"Update Not Supported",
		"This resource does not support updates. Delete and recreate instead.",
	)
}

func (r *KmipClientResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state KmipClientModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/kmip-delete-client")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting KmipClient", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting KmipClient", err.Error())
		return
	}
}

func (r *KmipClientResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
