// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &RoleResource{}
	_ resource.ResourceWithConfigure   = &RoleResource{}
	_ resource.ResourceWithImportState = &RoleResource{}
)

type RoleResource struct {
	client *AkeylessClient
}

func NewRoleResource() resource.Resource {
	return &RoleResource{}
}

type RoleModel struct {
	AnalyticsAccess types.String `tfsdk:"analytics_access"`
	AuditAccess types.String `tfsdk:"audit_access"`
	Comment types.String `tfsdk:"comment"`
	DeleteProtection types.String `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	EventCenterAccess types.String `tfsdk:"event_center_access"`
	EventForwardersAccess types.String `tfsdk:"event_forwarders_access"`
	EventForwardersName types.Set `tfsdk:"event_forwarders_name"`
	GwAnalyticsAccess types.String `tfsdk:"gw_analytics_access"`
	Name types.String `tfsdk:"name"`
	ReverseRbacAccess types.String `tfsdk:"reverse_rbac_access"`
	SraReportsAccess types.String `tfsdk:"sra_reports_access"`
	UsageReportsAccess types.String `tfsdk:"usage_reports_access"`
}

func (r *RoleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_role"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"analytics_access": schema.StringAttribute{
				Description: "Allow this role to view analytics",
				Optional: true,
			},
			"audit_access": schema.StringAttribute{
				Description: "Allow this role to view audit logs",
				Optional: true,
			},
			"comment": schema.StringAttribute{
				Description: "Deprecated - use description",
				Optional: true,
			},
			"delete_protection": schema.StringAttribute{
				Description: "Protection from accidental deletion of this object [true/false]",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Role description",
				Optional: true,
			},
			"event_center_access": schema.StringAttribute{
				Description: "Allow this role to view Event Center. Currently only 'none', 'scoped' and 'all'
values are supported",
				Optional: true,
			},
			"event_forwarders_access": schema.StringAttribute{
				Description: "Allow this role to manage Event Forwarders. Currently only 'none' and 'all' values are supported.",
				Optional: true,
			},
			"event_forwarders_name": schema.SetAttribute{
				Description: "Allow this role to manage the following Event Forwarders.",
				Optional: true,
				ElementType: types.StringType{},
			},
			"gw_analytics_access": schema.StringAttribute{
				Description: "Allow this role to view gateway analytics",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Role name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"reverse_rbac_access": schema.StringAttribute{
				Description: "Allow this role to view Reverse RBAC. Supported values: 'scoped', 'all'.",
				Optional: true,
			},
			"sra_reports_access": schema.StringAttribute{
				Description: "Allow this role to view SRA reports",
				Optional: true,
			},
			"usage_reports_access": schema.StringAttribute{
				Description: "Allow this role to view Usage Report. Currently only 'none' and
'all' values are supported.",
				Optional: true,
			},
		},
	}
}

func (r *RoleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *RoleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan RoleModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/create-role")

	// Set analytics_access
	if !plan.AnalyticsAccess.IsNull() && !plan.AnalyticsAccess.IsUnknown() {
		v := plan.AnalyticsAccess.ValueString()
		body.SetAnalyticsAccess(&v)
	}

	// Set audit_access
	if !plan.AuditAccess.IsNull() && !plan.AuditAccess.IsUnknown() {
		v := plan.AuditAccess.ValueString()
		body.SetAuditAccess(&v)
	}

	// Set comment
	if !plan.Comment.IsNull() && !plan.Comment.IsUnknown() {
		v := plan.Comment.ValueString()
		body.SetComment(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueString()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set event_center_access
	if !plan.EventCenterAccess.IsNull() && !plan.EventCenterAccess.IsUnknown() {
		v := plan.EventCenterAccess.ValueString()
		body.SetEventCenterAccess(&v)
	}

	// Set event_forwarders_access
	if !plan.EventForwardersAccess.IsNull() && !plan.EventForwardersAccess.IsUnknown() {
		v := plan.EventForwardersAccess.ValueString()
		body.SetEventForwardersAccess(&v)
	}

	// Set event_forwarders_name
	if !plan.EventForwardersName.IsNull() && !plan.EventForwardersName.IsUnknown() {
		body.SetEventForwardersName(expandStringSet(ctx, plan.EventForwardersName))
	}

	// Set gw_analytics_access
	if !plan.GwAnalyticsAccess.IsNull() && !plan.GwAnalyticsAccess.IsUnknown() {
		v := plan.GwAnalyticsAccess.ValueString()
		body.SetGwAnalyticsAccess(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set reverse_rbac_access
	if !plan.ReverseRbacAccess.IsNull() && !plan.ReverseRbacAccess.IsUnknown() {
		v := plan.ReverseRbacAccess.ValueString()
		body.SetReverseRbacAccess(&v)
	}

	// Set sra_reports_access
	if !plan.SraReportsAccess.IsNull() && !plan.SraReportsAccess.IsUnknown() {
		v := plan.SraReportsAccess.ValueString()
		body.SetSraReportsAccess(&v)
	}

	// Set usage_reports_access
	if !plan.UsageReportsAccess.IsNull() && !plan.UsageReportsAccess.IsUnknown() {
		v := plan.UsageReportsAccess.ValueString()
		body.SetUsageReportsAccess(&v)
	}

	tflog.Debug(ctx, "Creating Role")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating Role", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *RoleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state RoleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *RoleResource) readResource(ctx context.Context, id string) (RoleModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state RoleModel

	body := akeyless_api.NewReadBody("/get-role")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading Role", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "role_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *RoleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan RoleModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/update-role")
	if !plan.AnalyticsAccess.IsNull() && !plan.AnalyticsAccess.IsUnknown() {
		v := plan.AnalyticsAccess.ValueString()
		body.SetAnalyticsAccess(&v)
	}
	if !plan.AuditAccess.IsNull() && !plan.AuditAccess.IsUnknown() {
		v := plan.AuditAccess.ValueString()
		body.SetAuditAccess(&v)
	}
	if !plan.Comment.IsNull() && !plan.Comment.IsUnknown() {
		v := plan.Comment.ValueString()
		body.SetComment(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueString()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.EventCenterAccess.IsNull() && !plan.EventCenterAccess.IsUnknown() {
		v := plan.EventCenterAccess.ValueString()
		body.SetEventCenterAccess(&v)
	}
	if !plan.EventForwardersAccess.IsNull() && !plan.EventForwardersAccess.IsUnknown() {
		v := plan.EventForwardersAccess.ValueString()
		body.SetEventForwardersAccess(&v)
	}
	if !plan.EventForwardersName.IsNull() && !plan.EventForwardersName.IsUnknown() {
		body.SetEventForwardersName(expandStringSet(ctx, plan.EventForwardersName))
	}
	if !plan.GwAnalyticsAccess.IsNull() && !plan.GwAnalyticsAccess.IsUnknown() {
		v := plan.GwAnalyticsAccess.ValueString()
		body.SetGwAnalyticsAccess(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ReverseRbacAccess.IsNull() && !plan.ReverseRbacAccess.IsUnknown() {
		v := plan.ReverseRbacAccess.ValueString()
		body.SetReverseRbacAccess(&v)
	}
	if !plan.SraReportsAccess.IsNull() && !plan.SraReportsAccess.IsUnknown() {
		v := plan.SraReportsAccess.ValueString()
		body.SetSraReportsAccess(&v)
	}
	if !plan.UsageReportsAccess.IsNull() && !plan.UsageReportsAccess.IsUnknown() {
		v := plan.UsageReportsAccess.ValueString()
		body.SetUsageReportsAccess(&v)
	}

	tflog.Debug(ctx, "Updating Role")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating Role", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *RoleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state RoleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-role")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting Role", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting Role", err.Error())
		return
	}
}

func (r *RoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
