// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretOracleResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretOracleResource{}
	_ resource.ResourceWithImportState = &DynamicSecretOracleResource{}
)

type DynamicSecretOracleResource struct {
	client *AkeylessClient
}

func NewDynamicSecretOracleResource() resource.Resource {
	return &DynamicSecretOracleResource{}
}

type DynamicSecretOracleModel struct {
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DbServerCertificates types.String `tfsdk:"db_server_certificates"`
	DbServerName types.String `tfsdk:"db_server_name"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	OracleHost types.String `tfsdk:"oracle_host"`
	OraclePassword types.String `tfsdk:"oracle_password"`
	OraclePort types.String `tfsdk:"oracle_port"`
	OracleRevocationStatements types.String `tfsdk:"oracle_revocation_statements"`
	OracleScreationStatements types.String `tfsdk:"oracle_screation_statements"`
	OracleServiceName types.String `tfsdk:"oracle_service_name"`
	OracleUsername types.String `tfsdk:"oracle_username"`
	PasswordLength types.String `tfsdk:"password_length"`
	ProducerEncryptionKeyName types.String `tfsdk:"producer_encryption_key_name"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretOracleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_oracle"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"db_server_certificates": schema.StringAttribute{
				Description: "Database server certificates (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"db_server_name": schema.StringAttribute{
				Description: "Database server name for TLS verification",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"oracle_host": schema.StringAttribute{
				Description: "Oracle host",
				Optional: true,
			},
			"oracle_password": schema.StringAttribute{
				Description: "Oracle admin password",
				Optional: true,
				Sensitive: true,
			},
			"oracle_port": schema.StringAttribute{
				Description: "Oracle port (default: 1521)",
				Optional: true,
			},
			"oracle_revocation_statements": schema.StringAttribute{
				Description: "Oracle revocation statements",
				Optional: true,
			},
			"oracle_screation_statements": schema.StringAttribute{
				Description: "Oracle Creation statements",
				Optional: true,
			},
			"oracle_service_name": schema.StringAttribute{
				Description: "Oracle service name",
				Optional: true,
			},
			"oracle_username": schema.StringAttribute{
				Description: "Oracle admin username",
				Optional: true,
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"producer_encryption_key_name": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretOracleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretOracleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretOracleModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-oracle")

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set db_server_certificates
	if !plan.DbServerCertificates.IsNull() && !plan.DbServerCertificates.IsUnknown() {
		v := plan.DbServerCertificates.ValueString()
		body.SetDbServerCertificates(&v)
	}

	// Set db_server_name
	if !plan.DbServerName.IsNull() && !plan.DbServerName.IsUnknown() {
		v := plan.DbServerName.ValueString()
		body.SetDbServerName(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set oracle_host
	if !plan.OracleHost.IsNull() && !plan.OracleHost.IsUnknown() {
		v := plan.OracleHost.ValueString()
		body.SetOracleHost(&v)
	}

	// Set oracle_password
	if !plan.OraclePassword.IsNull() && !plan.OraclePassword.IsUnknown() {
		v := plan.OraclePassword.ValueString()
		body.SetOraclePassword(&v)
	}

	// Set oracle_port
	if !plan.OraclePort.IsNull() && !plan.OraclePort.IsUnknown() {
		v := plan.OraclePort.ValueString()
		body.SetOraclePort(&v)
	}

	// Set oracle_revocation_statements
	if !plan.OracleRevocationStatements.IsNull() && !plan.OracleRevocationStatements.IsUnknown() {
		v := plan.OracleRevocationStatements.ValueString()
		body.SetOracleRevocationStatements(&v)
	}

	// Set oracle_screation_statements
	if !plan.OracleScreationStatements.IsNull() && !plan.OracleScreationStatements.IsUnknown() {
		v := plan.OracleScreationStatements.ValueString()
		body.SetOracleScreationStatements(&v)
	}

	// Set oracle_service_name
	if !plan.OracleServiceName.IsNull() && !plan.OracleServiceName.IsUnknown() {
		v := plan.OracleServiceName.ValueString()
		body.SetOracleServiceName(&v)
	}

	// Set oracle_username
	if !plan.OracleUsername.IsNull() && !plan.OracleUsername.IsUnknown() {
		v := plan.OracleUsername.ValueString()
		body.SetOracleUsername(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set producer_encryption_key_name
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretOracle")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretOracle", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretOracleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretOracleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretOracleResource) readResource(ctx context.Context, id string) (DynamicSecretOracleModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretOracleModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretOracle", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretOracleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretOracleModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-oracle")
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DbServerCertificates.IsNull() && !plan.DbServerCertificates.IsUnknown() {
		v := plan.DbServerCertificates.ValueString()
		body.SetDbServerCertificates(&v)
	}
	if !plan.DbServerName.IsNull() && !plan.DbServerName.IsUnknown() {
		v := plan.DbServerName.ValueString()
		body.SetDbServerName(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.OracleHost.IsNull() && !plan.OracleHost.IsUnknown() {
		v := plan.OracleHost.ValueString()
		body.SetOracleHost(&v)
	}
	if !plan.OraclePassword.IsNull() && !plan.OraclePassword.IsUnknown() {
		v := plan.OraclePassword.ValueString()
		body.SetOraclePassword(&v)
	}
	if !plan.OraclePort.IsNull() && !plan.OraclePort.IsUnknown() {
		v := plan.OraclePort.ValueString()
		body.SetOraclePort(&v)
	}
	if !plan.OracleRevocationStatements.IsNull() && !plan.OracleRevocationStatements.IsUnknown() {
		v := plan.OracleRevocationStatements.ValueString()
		body.SetOracleRevocationStatements(&v)
	}
	if !plan.OracleScreationStatements.IsNull() && !plan.OracleScreationStatements.IsUnknown() {
		v := plan.OracleScreationStatements.ValueString()
		body.SetOracleScreationStatements(&v)
	}
	if !plan.OracleServiceName.IsNull() && !plan.OracleServiceName.IsUnknown() {
		v := plan.OracleServiceName.ValueString()
		body.SetOracleServiceName(&v)
	}
	if !plan.OracleUsername.IsNull() && !plan.OracleUsername.IsUnknown() {
		v := plan.OracleUsername.ValueString()
		body.SetOracleUsername(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretOracle")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretOracle", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretOracleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretOracleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretOracle", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretOracle", err.Error())
		return
	}
}

func (r *DynamicSecretOracleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
