// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetPingResource{}
	_ resource.ResourceWithConfigure   = &TargetPingResource{}
	_ resource.ResourceWithImportState = &TargetPingResource{}
)

type TargetPingResource struct {
	client *AkeylessClient
}

func NewTargetPingResource() resource.Resource {
	return &TargetPingResource{}
}

type TargetPingModel struct {
	AdministrativePort types.String `tfsdk:"administrative_port"`
	AuthorizationPort types.String `tfsdk:"authorization_port"`
	Description types.String `tfsdk:"description"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	PingUrl types.String `tfsdk:"ping_url"`
	PrivilegedUser types.String `tfsdk:"privileged_user"`
}

func (r *TargetPingResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_ping"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"administrative_port": schema.StringAttribute{
				Description: "Ping Identity administrative port",
				Optional: true,
			},
			"authorization_port": schema.StringAttribute{
				Description: "Ping Identity authorization port",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"ping_url": schema.StringAttribute{
				Description: "Ping Identity server URL",
				Optional: true,
			},
			"privileged_user": schema.StringAttribute{
				Description: "Ping Identity privileged username",
				Optional: true,
			},
		},
	}
}

func (r *TargetPingResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetPingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetPingModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-ping")

	// Set administrative_port
	if !plan.AdministrativePort.IsNull() && !plan.AdministrativePort.IsUnknown() {
		v := plan.AdministrativePort.ValueString()
		body.SetAdministrativePort(&v)
	}

	// Set authorization_port
	if !plan.AuthorizationPort.IsNull() && !plan.AuthorizationPort.IsUnknown() {
		v := plan.AuthorizationPort.ValueString()
		body.SetAuthorizationPort(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set ping_url
	if !plan.PingUrl.IsNull() && !plan.PingUrl.IsUnknown() {
		v := plan.PingUrl.ValueString()
		body.SetPingUrl(&v)
	}

	// Set privileged_user
	if !plan.PrivilegedUser.IsNull() && !plan.PrivilegedUser.IsUnknown() {
		v := plan.PrivilegedUser.ValueString()
		body.SetPrivilegedUser(&v)
	}

	tflog.Debug(ctx, "Creating TargetPing")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetPing", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetPingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetPingModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetPingResource) readResource(ctx context.Context, id string) (TargetPingModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetPingModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetPing", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetPingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetPingModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-ping")
	if !plan.AdministrativePort.IsNull() && !plan.AdministrativePort.IsUnknown() {
		v := plan.AdministrativePort.ValueString()
		body.SetAdministrativePort(&v)
	}
	if !plan.AuthorizationPort.IsNull() && !plan.AuthorizationPort.IsUnknown() {
		v := plan.AuthorizationPort.ValueString()
		body.SetAuthorizationPort(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PingUrl.IsNull() && !plan.PingUrl.IsUnknown() {
		v := plan.PingUrl.ValueString()
		body.SetPingUrl(&v)
	}
	if !plan.PrivilegedUser.IsNull() && !plan.PrivilegedUser.IsUnknown() {
		v := plan.PrivilegedUser.ValueString()
		body.SetPrivilegedUser(&v)
	}

	tflog.Debug(ctx, "Updating TargetPing")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetPing", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetPingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetPingModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetPing", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetPing", err.Error())
		return
	}
}

func (r *TargetPingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
