// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretRdpResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretRdpResource{}
	_ resource.ResourceWithImportState = &DynamicSecretRdpResource{}
)

type DynamicSecretRdpResource struct {
	client *AkeylessClient
}

func NewDynamicSecretRdpResource() resource.Resource {
	return &DynamicSecretRdpResource{}
}

type DynamicSecretRdpModel struct {
	AllowUserExtendSession types.Int64 `tfsdk:"allow_user_extend_session"`
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	FixedUserClaimKeyname types.String `tfsdk:"fixed_user_claim_keyname"`
	FixedUserOnly types.String `tfsdk:"fixed_user_only"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	PasswordLength types.String `tfsdk:"password_length"`
	ProducerEncryptionKeyName types.String `tfsdk:"producer_encryption_key_name"`
	RdpAdminName types.String `tfsdk:"rdp_admin_name"`
	RdpAdminPwd types.String `tfsdk:"rdp_admin_pwd"`
	RdpHostName types.String `tfsdk:"rdp_host_name"`
	RdpHostPort types.String `tfsdk:"rdp_host_port"`
	RdpUserGroups types.String `tfsdk:"rdp_user_groups"`
	SecureAccessDelay types.Int64 `tfsdk:"secure_access_delay"`
	SecureAccessRdGatewayServer types.String `tfsdk:"secure_access_rd_gateway_server"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
	WarnUserBeforeExpiration types.Int64 `tfsdk:"warn_user_before_expiration"`
}

func (r *DynamicSecretRdpResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_rdp"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_user_extend_session": schema.Int64Attribute{
				Description: "AllowUserExtendSession",
				Optional: true,
			},
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"fixed_user_claim_keyname": schema.StringAttribute{
				Description: "For externally provided users, denotes the key-name of IdP claim to extract the username from (relevant only for fixed-user-only=true)",
				Optional: true,
			},
			"fixed_user_only": schema.StringAttribute{
				Description: "Allow access using externally (IdP) provided username [true/false]",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"producer_encryption_key_name": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"rdp_admin_name": schema.StringAttribute{
				Description: "RDP admin username",
				Optional: true,
			},
			"rdp_admin_pwd": schema.StringAttribute{
				Description: "RDP admin password",
				Optional: true,
				Sensitive: true,
			},
			"rdp_host_name": schema.StringAttribute{
				Description: "RDP host address",
				Optional: true,
			},
			"rdp_host_port": schema.StringAttribute{
				Description: "RDP port (default: 3389)",
				Optional: true,
			},
			"rdp_user_groups": schema.StringAttribute{
				Description: "RDP user groups for dynamic users",
				Optional: true,
			},
			"secure_access_delay": schema.Int64Attribute{
				Description: "The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds",
				Optional: true,
			},
			"secure_access_rd_gateway_server": schema.StringAttribute{
				Description: "RD Gateway server",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
			"warn_user_before_expiration": schema.Int64Attribute{
				Description: "WarnBeforeUserExpiration",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretRdpResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretRdpResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretRdpModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-rdp")

	// Set allow_user_extend_session
	if !plan.AllowUserExtendSession.IsNull() && !plan.AllowUserExtendSession.IsUnknown() {
		v := plan.AllowUserExtendSession.ValueInt64()
		body.SetAllowUserExtendSession(&v)
	}

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set fixed_user_claim_keyname
	if !plan.FixedUserClaimKeyname.IsNull() && !plan.FixedUserClaimKeyname.IsUnknown() {
		v := plan.FixedUserClaimKeyname.ValueString()
		body.SetFixedUserClaimKeyname(&v)
	}

	// Set fixed_user_only
	if !plan.FixedUserOnly.IsNull() && !plan.FixedUserOnly.IsUnknown() {
		v := plan.FixedUserOnly.ValueString()
		body.SetFixedUserOnly(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set producer_encryption_key_name
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}

	// Set rdp_admin_name
	if !plan.RdpAdminName.IsNull() && !plan.RdpAdminName.IsUnknown() {
		v := plan.RdpAdminName.ValueString()
		body.SetRdpAdminName(&v)
	}

	// Set rdp_admin_pwd
	if !plan.RdpAdminPwd.IsNull() && !plan.RdpAdminPwd.IsUnknown() {
		v := plan.RdpAdminPwd.ValueString()
		body.SetRdpAdminPwd(&v)
	}

	// Set rdp_host_name
	if !plan.RdpHostName.IsNull() && !plan.RdpHostName.IsUnknown() {
		v := plan.RdpHostName.ValueString()
		body.SetRdpHostName(&v)
	}

	// Set rdp_host_port
	if !plan.RdpHostPort.IsNull() && !plan.RdpHostPort.IsUnknown() {
		v := plan.RdpHostPort.ValueString()
		body.SetRdpHostPort(&v)
	}

	// Set rdp_user_groups
	if !plan.RdpUserGroups.IsNull() && !plan.RdpUserGroups.IsUnknown() {
		v := plan.RdpUserGroups.ValueString()
		body.SetRdpUserGroups(&v)
	}

	// Set secure_access_delay
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}

	// Set secure_access_rd_gateway_server
	if !plan.SecureAccessRdGatewayServer.IsNull() && !plan.SecureAccessRdGatewayServer.IsUnknown() {
		v := plan.SecureAccessRdGatewayServer.ValueString()
		body.SetSecureAccessRdGatewayServer(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	// Set warn_user_before_expiration
	if !plan.WarnUserBeforeExpiration.IsNull() && !plan.WarnUserBeforeExpiration.IsUnknown() {
		v := plan.WarnUserBeforeExpiration.ValueInt64()
		body.SetWarnUserBeforeExpiration(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretRdp")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretRdp", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretRdpResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretRdpModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretRdpResource) readResource(ctx context.Context, id string) (DynamicSecretRdpModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretRdpModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretRdp", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretRdpResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretRdpModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-rdp")
	if !plan.AllowUserExtendSession.IsNull() && !plan.AllowUserExtendSession.IsUnknown() {
		v := plan.AllowUserExtendSession.ValueInt64()
		body.SetAllowUserExtendSession(&v)
	}
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.FixedUserClaimKeyname.IsNull() && !plan.FixedUserClaimKeyname.IsUnknown() {
		v := plan.FixedUserClaimKeyname.ValueString()
		body.SetFixedUserClaimKeyname(&v)
	}
	if !plan.FixedUserOnly.IsNull() && !plan.FixedUserOnly.IsUnknown() {
		v := plan.FixedUserOnly.ValueString()
		body.SetFixedUserOnly(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}
	if !plan.RdpAdminName.IsNull() && !plan.RdpAdminName.IsUnknown() {
		v := plan.RdpAdminName.ValueString()
		body.SetRdpAdminName(&v)
	}
	if !plan.RdpAdminPwd.IsNull() && !plan.RdpAdminPwd.IsUnknown() {
		v := plan.RdpAdminPwd.ValueString()
		body.SetRdpAdminPwd(&v)
	}
	if !plan.RdpHostName.IsNull() && !plan.RdpHostName.IsUnknown() {
		v := plan.RdpHostName.ValueString()
		body.SetRdpHostName(&v)
	}
	if !plan.RdpHostPort.IsNull() && !plan.RdpHostPort.IsUnknown() {
		v := plan.RdpHostPort.ValueString()
		body.SetRdpHostPort(&v)
	}
	if !plan.RdpUserGroups.IsNull() && !plan.RdpUserGroups.IsUnknown() {
		v := plan.RdpUserGroups.ValueString()
		body.SetRdpUserGroups(&v)
	}
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}
	if !plan.SecureAccessRdGatewayServer.IsNull() && !plan.SecureAccessRdGatewayServer.IsUnknown() {
		v := plan.SecureAccessRdGatewayServer.ValueString()
		body.SetSecureAccessRdGatewayServer(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}
	if !plan.WarnUserBeforeExpiration.IsNull() && !plan.WarnUserBeforeExpiration.IsUnknown() {
		v := plan.WarnUserBeforeExpiration.ValueInt64()
		body.SetWarnUserBeforeExpiration(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretRdp")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretRdp", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretRdpResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretRdpModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretRdp", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretRdp", err.Error())
		return
	}
}

func (r *DynamicSecretRdpResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
