// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetArtifactoryResource{}
	_ resource.ResourceWithConfigure   = &TargetArtifactoryResource{}
	_ resource.ResourceWithImportState = &TargetArtifactoryResource{}
)

type TargetArtifactoryResource struct {
	client *AkeylessClient
}

func NewTargetArtifactoryResource() resource.Resource {
	return &TargetArtifactoryResource{}
}

type TargetArtifactoryModel struct {
	ArtifactoryAdminName types.String `tfsdk:"artifactory_admin_name"`
	ArtifactoryAdminPwd types.String `tfsdk:"artifactory_admin_pwd"`
	BaseUrl types.String `tfsdk:"base_url"`
	Description types.String `tfsdk:"description"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
}

func (r *TargetArtifactoryResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_artifactory"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"artifactory_admin_name": schema.StringAttribute{
				Description: "Artifactory admin username",
				Required: true,
			},
			"artifactory_admin_pwd": schema.StringAttribute{
				Description: "Artifactory admin password",
				Required: true,
				Sensitive: true,
			},
			"base_url": schema.StringAttribute{
				Description: "Artifactory base URL",
				Required: true,
			},
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key used to encrypt the target secret value (if empty, the
account default protectionKey key will be used)",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (r *TargetArtifactoryResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetArtifactoryResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetArtifactoryModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-artifactory")

	// Set artifactory_admin_name
	if !plan.ArtifactoryAdminName.IsNull() && !plan.ArtifactoryAdminName.IsUnknown() {
		v := plan.ArtifactoryAdminName.ValueString()
		body.SetArtifactoryAdminName(&v)
	}

	// Set artifactory_admin_pwd
	if !plan.ArtifactoryAdminPwd.IsNull() && !plan.ArtifactoryAdminPwd.IsUnknown() {
		v := plan.ArtifactoryAdminPwd.ValueString()
		body.SetArtifactoryAdminPwd(&v)
	}

	// Set base_url
	if !plan.BaseUrl.IsNull() && !plan.BaseUrl.IsUnknown() {
		v := plan.BaseUrl.ValueString()
		body.SetBaseUrl(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	tflog.Debug(ctx, "Creating TargetArtifactory")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetArtifactory", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetArtifactoryResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetArtifactoryModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetArtifactoryResource) readResource(ctx context.Context, id string) (TargetArtifactoryModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetArtifactoryModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetArtifactory", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetArtifactoryResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetArtifactoryModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-artifactory")
	if !plan.ArtifactoryAdminName.IsNull() && !plan.ArtifactoryAdminName.IsUnknown() {
		v := plan.ArtifactoryAdminName.ValueString()
		body.SetArtifactoryAdminName(&v)
	}
	if !plan.ArtifactoryAdminPwd.IsNull() && !plan.ArtifactoryAdminPwd.IsUnknown() {
		v := plan.ArtifactoryAdminPwd.ValueString()
		body.SetArtifactoryAdminPwd(&v)
	}
	if !plan.BaseUrl.IsNull() && !plan.BaseUrl.IsUnknown() {
		v := plan.BaseUrl.ValueString()
		body.SetBaseUrl(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	tflog.Debug(ctx, "Updating TargetArtifactory")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetArtifactory", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetArtifactoryResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetArtifactoryModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetArtifactory", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetArtifactory", err.Error())
		return
	}
}

func (r *TargetArtifactoryResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
