// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &AuthMethodCertResource{}
	_ resource.ResourceWithConfigure   = &AuthMethodCertResource{}
	_ resource.ResourceWithImportState = &AuthMethodCertResource{}
)

type AuthMethodCertResource struct {
	client *AkeylessClient
}

func NewAuthMethodCertResource() resource.Resource {
	return &AuthMethodCertResource{}
}

type AuthMethodCertModel struct {
	AccessExpires types.Int64 `tfsdk:"access_expires"`
	AllowedClientType types.Set `tfsdk:"allowed_client_type"`
	AllowedCors types.String `tfsdk:"allowed_cors"`
	AuditLogsClaims types.Set `tfsdk:"audit_logs_claims"`
	BoundCommonNames types.Set `tfsdk:"bound_common_names"`
	BoundDnsSans types.Set `tfsdk:"bound_dns_sans"`
	BoundEmailSans types.Set `tfsdk:"bound_email_sans"`
	BoundExtensions types.Set `tfsdk:"bound_extensions"`
	BoundIps types.Set `tfsdk:"bound_ips"`
	BoundOrganizationalUnits types.Set `tfsdk:"bound_organizational_units"`
	BoundUriSans types.Set `tfsdk:"bound_uri_sans"`
	CertificateData types.String `tfsdk:"certificate_data"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ExpirationEventIn types.Set `tfsdk:"expiration_event_in"`
	ForceSubClaims types.Bool `tfsdk:"force_sub_claims"`
	GwBoundIps types.Set `tfsdk:"gw_bound_ips"`
	JwtTtl types.Int64 `tfsdk:"jwt_ttl"`
	Name types.String `tfsdk:"name"`
	ProductType types.Set `tfsdk:"product_type"`
	RequireCrlDp types.Bool `tfsdk:"require_crl_dp"`
	RevokedCertIds types.Set `tfsdk:"revoked_cert_ids"`
	UniqueIdentifier types.String `tfsdk:"unique_identifier"`
}

func (r *AuthMethodCertResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_auth_method_cert"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_expires": schema.Int64Attribute{
				Description: "Access expiration in Unix time (0 = no expiry)",
				Optional: true,
			},
			"allowed_client_type": schema.SetAttribute{
				Description: "limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]",
				Optional: true,
				ElementType: types.StringType{},
			},
			"allowed_cors": schema.StringAttribute{
				Description: "Comma separated list of allowed CORS domains to be validated as part of the authentication flow.",
				Optional: true,
			},
			"audit_logs_claims": schema.SetAttribute{
				Description: "Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_common_names": schema.SetAttribute{
				Description: "Bound common names for certificate matching",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_dns_sans": schema.SetAttribute{
				Description: "Bound DNS SANs for certificate matching",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_email_sans": schema.SetAttribute{
				Description: "Bound email SANs for certificate matching",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_extensions": schema.SetAttribute{
				Description: "Bound extensions (OID:value pairs)",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_ips": schema.SetAttribute{
				Description: "CIDR whitelist for access",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_organizational_units": schema.SetAttribute{
				Description: "Bound organizational units for certificate matching",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_uri_sans": schema.SetAttribute{
				Description: "Bound URI SANs for certificate matching",
				Optional: true,
				ElementType: types.StringType{},
			},
			"certificate_data": schema.StringAttribute{
				Description: "PEM certificate data for validation",
				Optional: true,
				Sensitive: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Auth Method description",
				Optional: true,
			},
			"expiration_event_in": schema.SetAttribute{
				Description: "How many days before the expiration of the auth method would you like to be notified.",
				Optional: true,
				ElementType: types.StringType{},
			},
			"force_sub_claims": schema.BoolAttribute{
				Description: "Force sub-claims enforcement",
				Optional: true,
			},
			"gw_bound_ips": schema.SetAttribute{
				Description: "Gateway CIDR whitelist",
				Optional: true,
				ElementType: types.StringType{},
			},
			"jwt_ttl": schema.Int64Attribute{
				Description: "JWT TTL in seconds",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Auth Method name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"product_type": schema.SetAttribute{
				Description: "Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]",
				Optional: true,
				ElementType: types.StringType{},
			},
			"require_crl_dp": schema.BoolAttribute{
				Description: "Require certificate CRL distribution points (CDP) and enforce CRL validation during authentication.",
				Optional: true,
			},
			"revoked_cert_ids": schema.SetAttribute{
				Description: "Revoked certificate serial numbers",
				Optional: true,
				ElementType: types.StringType{},
			},
			"unique_identifier": schema.StringAttribute{
				Description: "A unique identifier (ID) value should be configured, such as common_name or organizational_unit
Whenever a user logs in with a token, these authentication types issue
a \"sub claim\" that contains details uniquely identifying that user.
This sub claim includes a key containing the ID value that you
configured, and is used to distinguish between different users from
within the same organization.",
				Required: true,
			},
		},
	}
}

func (r *AuthMethodCertResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *AuthMethodCertResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan AuthMethodCertModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/auth-method-create-cert")

	// Set access_expires
	if !plan.AccessExpires.IsNull() && !plan.AccessExpires.IsUnknown() {
		v := plan.AccessExpires.ValueInt64()
		body.SetAccessExpires(&v)
	}

	// Set allowed_client_type
	if !plan.AllowedClientType.IsNull() && !plan.AllowedClientType.IsUnknown() {
		body.SetAllowedClientType(expandStringSet(ctx, plan.AllowedClientType))
	}

	// Set allowed_cors
	if !plan.AllowedCors.IsNull() && !plan.AllowedCors.IsUnknown() {
		v := plan.AllowedCors.ValueString()
		body.SetAllowedCors(&v)
	}

	// Set audit_logs_claims
	if !plan.AuditLogsClaims.IsNull() && !plan.AuditLogsClaims.IsUnknown() {
		body.SetAuditLogsClaims(expandStringSet(ctx, plan.AuditLogsClaims))
	}

	// Set bound_common_names
	if !plan.BoundCommonNames.IsNull() && !plan.BoundCommonNames.IsUnknown() {
		body.SetBoundCommonNames(expandStringSet(ctx, plan.BoundCommonNames))
	}

	// Set bound_dns_sans
	if !plan.BoundDnsSans.IsNull() && !plan.BoundDnsSans.IsUnknown() {
		body.SetBoundDnsSans(expandStringSet(ctx, plan.BoundDnsSans))
	}

	// Set bound_email_sans
	if !plan.BoundEmailSans.IsNull() && !plan.BoundEmailSans.IsUnknown() {
		body.SetBoundEmailSans(expandStringSet(ctx, plan.BoundEmailSans))
	}

	// Set bound_extensions
	if !plan.BoundExtensions.IsNull() && !plan.BoundExtensions.IsUnknown() {
		body.SetBoundExtensions(expandStringSet(ctx, plan.BoundExtensions))
	}

	// Set bound_ips
	if !plan.BoundIps.IsNull() && !plan.BoundIps.IsUnknown() {
		body.SetBoundIps(expandStringSet(ctx, plan.BoundIps))
	}

	// Set bound_organizational_units
	if !plan.BoundOrganizationalUnits.IsNull() && !plan.BoundOrganizationalUnits.IsUnknown() {
		body.SetBoundOrganizationalUnits(expandStringSet(ctx, plan.BoundOrganizationalUnits))
	}

	// Set bound_uri_sans
	if !plan.BoundUriSans.IsNull() && !plan.BoundUriSans.IsUnknown() {
		body.SetBoundUriSans(expandStringSet(ctx, plan.BoundUriSans))
	}

	// Set certificate_data
	if !plan.CertificateData.IsNull() && !plan.CertificateData.IsUnknown() {
		v := plan.CertificateData.ValueString()
		body.SetCertificateData(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set expiration_event_in
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}

	// Set force_sub_claims
	if !plan.ForceSubClaims.IsNull() && !plan.ForceSubClaims.IsUnknown() {
		v := plan.ForceSubClaims.ValueBool()
		body.SetForceSubClaims(&v)
	}

	// Set gw_bound_ips
	if !plan.GwBoundIps.IsNull() && !plan.GwBoundIps.IsUnknown() {
		body.SetGwBoundIps(expandStringSet(ctx, plan.GwBoundIps))
	}

	// Set jwt_ttl
	if !plan.JwtTtl.IsNull() && !plan.JwtTtl.IsUnknown() {
		v := plan.JwtTtl.ValueInt64()
		body.SetJwtTtl(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set product_type
	if !plan.ProductType.IsNull() && !plan.ProductType.IsUnknown() {
		body.SetProductType(expandStringSet(ctx, plan.ProductType))
	}

	// Set require_crl_dp
	if !plan.RequireCrlDp.IsNull() && !plan.RequireCrlDp.IsUnknown() {
		v := plan.RequireCrlDp.ValueBool()
		body.SetRequireCrlDp(&v)
	}

	// Set revoked_cert_ids
	if !plan.RevokedCertIds.IsNull() && !plan.RevokedCertIds.IsUnknown() {
		body.SetRevokedCertIds(expandStringSet(ctx, plan.RevokedCertIds))
	}

	// Set unique_identifier
	if !plan.UniqueIdentifier.IsNull() && !plan.UniqueIdentifier.IsUnknown() {
		v := plan.UniqueIdentifier.ValueString()
		body.SetUniqueIdentifier(&v)
	}

	tflog.Debug(ctx, "Creating AuthMethodCert")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating AuthMethodCert", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodCertResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state AuthMethodCertModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodCertResource) readResource(ctx context.Context, id string) (AuthMethodCertModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state AuthMethodCertModel

	body := akeyless_api.NewReadBody("/get-auth-method")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading AuthMethodCert", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "access_info.access_expires"); ok {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			state.AccessExpires = types.Int64Value(n)
		}
	}
	if v, ok := GetNestedStringSlice(result, "access_info.cert_access_rules.bound_common_names"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.BoundCommonNames = setVal
	}
	if v, ok := GetNestedStringSlice(result, "access_info.cert_access_rules.bound_dns_sans"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.BoundDnsSans = setVal
	}
	if v, ok := GetNestedStringSlice(result, "access_info.cert_access_rules.bound_email_sans"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.BoundEmailSans = setVal
	}
	if v, ok := GetNestedStringSlice(result, "access_info.cert_access_rules.bound_extensions"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.BoundExtensions = setVal
	}
	if v, ok := GetNestedStringSlice(result, "access_info.cert_access_rules.bound_organizational_units"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.BoundOrganizationalUnits = setVal
	}
	if v, ok := GetNestedStringSlice(result, "access_info.cert_access_rules.bound_uri_sans"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.BoundUriSans = setVal
	}
	if v, ok := GetNestedString(result, "access_info.cert_access_rules.certificate_data"); ok {
		state.CertificateData = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "access_info.force_sub_claims"); ok {
		state.ForceSubClaims = types.BoolValue(v == "true")
	}

	return state, diags
}

func (r *AuthMethodCertResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan AuthMethodCertModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/auth-method-update-cert")
	if !plan.AccessExpires.IsNull() && !plan.AccessExpires.IsUnknown() {
		v := plan.AccessExpires.ValueInt64()
		body.SetAccessExpires(&v)
	}
	if !plan.AllowedClientType.IsNull() && !plan.AllowedClientType.IsUnknown() {
		body.SetAllowedClientType(expandStringSet(ctx, plan.AllowedClientType))
	}
	if !plan.AllowedCors.IsNull() && !plan.AllowedCors.IsUnknown() {
		v := plan.AllowedCors.ValueString()
		body.SetAllowedCors(&v)
	}
	if !plan.AuditLogsClaims.IsNull() && !plan.AuditLogsClaims.IsUnknown() {
		body.SetAuditLogsClaims(expandStringSet(ctx, plan.AuditLogsClaims))
	}
	if !plan.BoundCommonNames.IsNull() && !plan.BoundCommonNames.IsUnknown() {
		body.SetBoundCommonNames(expandStringSet(ctx, plan.BoundCommonNames))
	}
	if !plan.BoundDnsSans.IsNull() && !plan.BoundDnsSans.IsUnknown() {
		body.SetBoundDnsSans(expandStringSet(ctx, plan.BoundDnsSans))
	}
	if !plan.BoundEmailSans.IsNull() && !plan.BoundEmailSans.IsUnknown() {
		body.SetBoundEmailSans(expandStringSet(ctx, plan.BoundEmailSans))
	}
	if !plan.BoundExtensions.IsNull() && !plan.BoundExtensions.IsUnknown() {
		body.SetBoundExtensions(expandStringSet(ctx, plan.BoundExtensions))
	}
	if !plan.BoundIps.IsNull() && !plan.BoundIps.IsUnknown() {
		body.SetBoundIps(expandStringSet(ctx, plan.BoundIps))
	}
	if !plan.BoundOrganizationalUnits.IsNull() && !plan.BoundOrganizationalUnits.IsUnknown() {
		body.SetBoundOrganizationalUnits(expandStringSet(ctx, plan.BoundOrganizationalUnits))
	}
	if !plan.BoundUriSans.IsNull() && !plan.BoundUriSans.IsUnknown() {
		body.SetBoundUriSans(expandStringSet(ctx, plan.BoundUriSans))
	}
	if !plan.CertificateData.IsNull() && !plan.CertificateData.IsUnknown() {
		v := plan.CertificateData.ValueString()
		body.SetCertificateData(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}
	if !plan.ForceSubClaims.IsNull() && !plan.ForceSubClaims.IsUnknown() {
		v := plan.ForceSubClaims.ValueBool()
		body.SetForceSubClaims(&v)
	}
	if !plan.GwBoundIps.IsNull() && !plan.GwBoundIps.IsUnknown() {
		body.SetGwBoundIps(expandStringSet(ctx, plan.GwBoundIps))
	}
	if !plan.JwtTtl.IsNull() && !plan.JwtTtl.IsUnknown() {
		v := plan.JwtTtl.ValueInt64()
		body.SetJwtTtl(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProductType.IsNull() && !plan.ProductType.IsUnknown() {
		body.SetProductType(expandStringSet(ctx, plan.ProductType))
	}
	if !plan.RequireCrlDp.IsNull() && !plan.RequireCrlDp.IsUnknown() {
		v := plan.RequireCrlDp.ValueBool()
		body.SetRequireCrlDp(&v)
	}
	if !plan.RevokedCertIds.IsNull() && !plan.RevokedCertIds.IsUnknown() {
		body.SetRevokedCertIds(expandStringSet(ctx, plan.RevokedCertIds))
	}
	if !plan.UniqueIdentifier.IsNull() && !plan.UniqueIdentifier.IsUnknown() {
		v := plan.UniqueIdentifier.ValueString()
		body.SetUniqueIdentifier(&v)
	}

	tflog.Debug(ctx, "Updating AuthMethodCert")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating AuthMethodCert", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodCertResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state AuthMethodCertModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-auth-method")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting AuthMethodCert", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting AuthMethodCert", err.Error())
		return
	}
}

func (r *AuthMethodCertResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
