// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretHanadbResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretHanadbResource{}
	_ resource.ResourceWithImportState = &DynamicSecretHanadbResource{}
)

type DynamicSecretHanadbResource struct {
	client *AkeylessClient
}

func NewDynamicSecretHanadbResource() resource.Resource {
	return &DynamicSecretHanadbResource{}
}

type DynamicSecretHanadbModel struct {
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	HanaDbname types.String `tfsdk:"hana_dbname"`
	HanadbCreateStatements types.String `tfsdk:"hanadb_create_statements"`
	HanadbHost types.String `tfsdk:"hanadb_host"`
	HanadbPassword types.String `tfsdk:"hanadb_password"`
	HanadbPort types.String `tfsdk:"hanadb_port"`
	HanadbRevocationStatements types.String `tfsdk:"hanadb_revocation_statements"`
	HanadbUsername types.String `tfsdk:"hanadb_username"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	PasswordLength types.String `tfsdk:"password_length"`
	ProducerEncryptionKeyName types.String `tfsdk:"producer_encryption_key_name"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretHanadbResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_hanadb"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"hana_dbname": schema.StringAttribute{
				Description: "HanaDb Name",
				Optional: true,
			},
			"hanadb_create_statements": schema.StringAttribute{
				Description: "HanaDb Creation statements",
				Optional: true,
			},
			"hanadb_host": schema.StringAttribute{
				Description: "HANA host",
				Optional: true,
			},
			"hanadb_password": schema.StringAttribute{
				Description: "HANA admin password",
				Optional: true,
				Sensitive: true,
			},
			"hanadb_port": schema.StringAttribute{
				Description: "HANA port (default: 443)",
				Optional: true,
			},
			"hanadb_revocation_statements": schema.StringAttribute{
				Description: "HANA SQL revocation statements",
				Optional: true,
			},
			"hanadb_username": schema.StringAttribute{
				Description: "HANA admin username",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"producer_encryption_key_name": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretHanadbResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretHanadbResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretHanadbModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-hanadb")

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set hana_dbname
	if !plan.HanaDbname.IsNull() && !plan.HanaDbname.IsUnknown() {
		v := plan.HanaDbname.ValueString()
		body.SetHanaDbname(&v)
	}

	// Set hanadb_create_statements
	if !plan.HanadbCreateStatements.IsNull() && !plan.HanadbCreateStatements.IsUnknown() {
		v := plan.HanadbCreateStatements.ValueString()
		body.SetHanadbCreateStatements(&v)
	}

	// Set hanadb_host
	if !plan.HanadbHost.IsNull() && !plan.HanadbHost.IsUnknown() {
		v := plan.HanadbHost.ValueString()
		body.SetHanadbHost(&v)
	}

	// Set hanadb_password
	if !plan.HanadbPassword.IsNull() && !plan.HanadbPassword.IsUnknown() {
		v := plan.HanadbPassword.ValueString()
		body.SetHanadbPassword(&v)
	}

	// Set hanadb_port
	if !plan.HanadbPort.IsNull() && !plan.HanadbPort.IsUnknown() {
		v := plan.HanadbPort.ValueString()
		body.SetHanadbPort(&v)
	}

	// Set hanadb_revocation_statements
	if !plan.HanadbRevocationStatements.IsNull() && !plan.HanadbRevocationStatements.IsUnknown() {
		v := plan.HanadbRevocationStatements.ValueString()
		body.SetHanadbRevocationStatements(&v)
	}

	// Set hanadb_username
	if !plan.HanadbUsername.IsNull() && !plan.HanadbUsername.IsUnknown() {
		v := plan.HanadbUsername.ValueString()
		body.SetHanadbUsername(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set producer_encryption_key_name
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretHanadb")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretHanadb", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretHanadbResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretHanadbModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretHanadbResource) readResource(ctx context.Context, id string) (DynamicSecretHanadbModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretHanadbModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretHanadb", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretHanadbResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretHanadbModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-hanadb")
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.HanaDbname.IsNull() && !plan.HanaDbname.IsUnknown() {
		v := plan.HanaDbname.ValueString()
		body.SetHanaDbname(&v)
	}
	if !plan.HanadbCreateStatements.IsNull() && !plan.HanadbCreateStatements.IsUnknown() {
		v := plan.HanadbCreateStatements.ValueString()
		body.SetHanadbCreateStatements(&v)
	}
	if !plan.HanadbHost.IsNull() && !plan.HanadbHost.IsUnknown() {
		v := plan.HanadbHost.ValueString()
		body.SetHanadbHost(&v)
	}
	if !plan.HanadbPassword.IsNull() && !plan.HanadbPassword.IsUnknown() {
		v := plan.HanadbPassword.ValueString()
		body.SetHanadbPassword(&v)
	}
	if !plan.HanadbPort.IsNull() && !plan.HanadbPort.IsUnknown() {
		v := plan.HanadbPort.ValueString()
		body.SetHanadbPort(&v)
	}
	if !plan.HanadbRevocationStatements.IsNull() && !plan.HanadbRevocationStatements.IsUnknown() {
		v := plan.HanadbRevocationStatements.ValueString()
		body.SetHanadbRevocationStatements(&v)
	}
	if !plan.HanadbUsername.IsNull() && !plan.HanadbUsername.IsUnknown() {
		v := plan.HanadbUsername.ValueString()
		body.SetHanadbUsername(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretHanadb")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretHanadb", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretHanadbResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretHanadbModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretHanadb", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretHanadb", err.Error())
		return
	}
}

func (r *DynamicSecretHanadbResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
