// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetAwsResource{}
	_ resource.ResourceWithConfigure   = &TargetAwsResource{}
	_ resource.ResourceWithImportState = &TargetAwsResource{}
)

type TargetAwsResource struct {
	client *AkeylessClient
}

func NewTargetAwsResource() resource.Resource {
	return &TargetAwsResource{}
}

type TargetAwsModel struct {
	AccessKey types.String `tfsdk:"access_key"`
	AccessKeyId types.String `tfsdk:"access_key_id"`
	Description types.String `tfsdk:"description"`
	GenerateExternalId types.Bool `tfsdk:"generate_external_id"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	Region types.String `tfsdk:"region"`
	RoleArn types.String `tfsdk:"role_arn"`
	SessionToken types.String `tfsdk:"session_token"`
	UseGwCloudIdentity types.Bool `tfsdk:"use_gw_cloud_identity"`
}

func (r *TargetAwsResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_aws"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_key": schema.StringAttribute{
				Description: "AWS secret access key",
				Required: true,
				Sensitive: true,
			},
			"access_key_id": schema.StringAttribute{
				Description: "AWS access key ID",
				Required: true,
				Sensitive: true,
			},
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"generate_external_id": schema.BoolAttribute{
				Description: "A unique auto-generated value used in your AWS account when configuring your AWS IAM role to securely delegate access to Akeyless. Relevant only when using GW cloud ID",
				Optional: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"region": schema.StringAttribute{
				Description: "AWS region",
				Optional: true,
			},
			"role_arn": schema.StringAttribute{
				Description: "AWS IAM role identifier that Gateway will assume in your AWS account, relevant only when using external ID",
				Optional: true,
			},
			"session_token": schema.StringAttribute{
				Description: "AWS session token (for temporary credentials)",
				Optional: true,
				Sensitive: true,
			},
			"use_gw_cloud_identity": schema.BoolAttribute{
				Description: "Use gateway cloud identity for authentication",
				Optional: true,
			},
		},
	}
}

func (r *TargetAwsResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetAwsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetAwsModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-aws")

	// Set access_key
	if !plan.AccessKey.IsNull() && !plan.AccessKey.IsUnknown() {
		v := plan.AccessKey.ValueString()
		body.SetAccessKey(&v)
	}

	// Set access_key_id
	if !plan.AccessKeyId.IsNull() && !plan.AccessKeyId.IsUnknown() {
		v := plan.AccessKeyId.ValueString()
		body.SetAccessKeyId(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set generate_external_id
	if !plan.GenerateExternalId.IsNull() && !plan.GenerateExternalId.IsUnknown() {
		v := plan.GenerateExternalId.ValueBool()
		body.SetGenerateExternalId(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set region
	if !plan.Region.IsNull() && !plan.Region.IsUnknown() {
		v := plan.Region.ValueString()
		body.SetRegion(&v)
	}

	// Set role_arn
	if !plan.RoleArn.IsNull() && !plan.RoleArn.IsUnknown() {
		v := plan.RoleArn.ValueString()
		body.SetRoleArn(&v)
	}

	// Set session_token
	if !plan.SessionToken.IsNull() && !plan.SessionToken.IsUnknown() {
		v := plan.SessionToken.ValueString()
		body.SetSessionToken(&v)
	}

	// Set use_gw_cloud_identity
	if !plan.UseGwCloudIdentity.IsNull() && !plan.UseGwCloudIdentity.IsUnknown() {
		v := plan.UseGwCloudIdentity.ValueBool()
		body.SetUseGwCloudIdentity(&v)
	}

	tflog.Debug(ctx, "Creating TargetAws")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetAws", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetAwsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetAwsModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetAwsResource) readResource(ctx context.Context, id string) (TargetAwsModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetAwsModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetAws", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetAwsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetAwsModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-aws")
	if !plan.AccessKey.IsNull() && !plan.AccessKey.IsUnknown() {
		v := plan.AccessKey.ValueString()
		body.SetAccessKey(&v)
	}
	if !plan.AccessKeyId.IsNull() && !plan.AccessKeyId.IsUnknown() {
		v := plan.AccessKeyId.ValueString()
		body.SetAccessKeyId(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.GenerateExternalId.IsNull() && !plan.GenerateExternalId.IsUnknown() {
		v := plan.GenerateExternalId.ValueBool()
		body.SetGenerateExternalId(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.Region.IsNull() && !plan.Region.IsUnknown() {
		v := plan.Region.ValueString()
		body.SetRegion(&v)
	}
	if !plan.RoleArn.IsNull() && !plan.RoleArn.IsUnknown() {
		v := plan.RoleArn.ValueString()
		body.SetRoleArn(&v)
	}
	if !plan.SessionToken.IsNull() && !plan.SessionToken.IsUnknown() {
		v := plan.SessionToken.ValueString()
		body.SetSessionToken(&v)
	}
	if !plan.UseGwCloudIdentity.IsNull() && !plan.UseGwCloudIdentity.IsUnknown() {
		v := plan.UseGwCloudIdentity.ValueBool()
		body.SetUseGwCloudIdentity(&v)
	}

	tflog.Debug(ctx, "Updating TargetAws")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetAws", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetAwsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetAwsModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetAws", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetAws", err.Error())
		return
	}
}

func (r *TargetAwsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
