// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &AuthMethodHuaweiResource{}
	_ resource.ResourceWithConfigure   = &AuthMethodHuaweiResource{}
	_ resource.ResourceWithImportState = &AuthMethodHuaweiResource{}
)

type AuthMethodHuaweiResource struct {
	client *AkeylessClient
}

func NewAuthMethodHuaweiResource() resource.Resource {
	return &AuthMethodHuaweiResource{}
}

type AuthMethodHuaweiModel struct {
	AccessExpires types.Int64 `tfsdk:"access_expires"`
	AllowedClientType types.Set `tfsdk:"allowed_client_type"`
	AuditLogsClaims types.Set `tfsdk:"audit_logs_claims"`
	AuthUrl types.String `tfsdk:"auth_url"`
	BoundDomainId types.Set `tfsdk:"bound_domain_id"`
	BoundDomainName types.Set `tfsdk:"bound_domain_name"`
	BoundIps types.Set `tfsdk:"bound_ips"`
	BoundTenantId types.Set `tfsdk:"bound_tenant_id"`
	BoundTenantName types.Set `tfsdk:"bound_tenant_name"`
	BoundUserId types.Set `tfsdk:"bound_user_id"`
	BoundUserName types.Set `tfsdk:"bound_user_name"`
	DeleteProtection types.String `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ExpirationEventIn types.Set `tfsdk:"expiration_event_in"`
	ForceSubClaims types.Bool `tfsdk:"force_sub_claims"`
	GwBoundIps types.Set `tfsdk:"gw_bound_ips"`
	JwtTtl types.Int64 `tfsdk:"jwt_ttl"`
	Name types.String `tfsdk:"name"`
	ProductType types.Set `tfsdk:"product_type"`
}

func (r *AuthMethodHuaweiResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_auth_method_huawei"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_expires": schema.Int64Attribute{
				Description: "Access expiration date in Unix timestamp (select 0 for access without
expiry date)",
				Optional: true,
			},
			"allowed_client_type": schema.SetAttribute{
				Description: "limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]",
				Optional: true,
				ElementType: types.StringType{},
			},
			"audit_logs_claims": schema.SetAttribute{
				Description: "Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"",
				Optional: true,
				ElementType: types.StringType{},
			},
			"auth_url": schema.StringAttribute{
				Description: "sts URL",
				Optional: true,
			},
			"bound_domain_id": schema.SetAttribute{
				Description: "A list of domain IDs that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_domain_name": schema.SetAttribute{
				Description: "A list of domain names that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_ips": schema.SetAttribute{
				Description: "A CIDR whitelist with the IPs that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_tenant_id": schema.SetAttribute{
				Description: "A list of full tenant ids that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_tenant_name": schema.SetAttribute{
				Description: "A list of full tenant names that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_user_id": schema.SetAttribute{
				Description: "A list of full user ids that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_user_name": schema.SetAttribute{
				Description: "A list of full user-name that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"delete_protection": schema.StringAttribute{
				Description: "Protection from accidental deletion of this object [true/false]",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Auth Method description",
				Optional: true,
			},
			"expiration_event_in": schema.SetAttribute{
				Description: "How many days before the expiration of the auth method would you like to be notified.",
				Optional: true,
				ElementType: types.StringType{},
			},
			"force_sub_claims": schema.BoolAttribute{
				Description: "if true: enforce role-association must include sub claims",
				Optional: true,
			},
			"gw_bound_ips": schema.SetAttribute{
				Description: "A CIDR whitelist with the GW IPs that the access is restricted to",
				Optional: true,
				ElementType: types.StringType{},
			},
			"jwt_ttl": schema.Int64Attribute{
				Description: "Jwt TTL",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Auth Method name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"product_type": schema.SetAttribute{
				Description: "Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]",
				Optional: true,
				ElementType: types.StringType{},
			},
		},
	}
}

func (r *AuthMethodHuaweiResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *AuthMethodHuaweiResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan AuthMethodHuaweiModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/create-auth-method-huawei")

	// Set access_expires
	if !plan.AccessExpires.IsNull() && !plan.AccessExpires.IsUnknown() {
		v := plan.AccessExpires.ValueInt64()
		body.SetAccessExpires(&v)
	}

	// Set allowed_client_type
	if !plan.AllowedClientType.IsNull() && !plan.AllowedClientType.IsUnknown() {
		body.SetAllowedClientType(expandStringSet(ctx, plan.AllowedClientType))
	}

	// Set audit_logs_claims
	if !plan.AuditLogsClaims.IsNull() && !plan.AuditLogsClaims.IsUnknown() {
		body.SetAuditLogsClaims(expandStringSet(ctx, plan.AuditLogsClaims))
	}

	// Set auth_url
	if !plan.AuthUrl.IsNull() && !plan.AuthUrl.IsUnknown() {
		v := plan.AuthUrl.ValueString()
		body.SetAuthUrl(&v)
	}

	// Set bound_domain_id
	if !plan.BoundDomainId.IsNull() && !plan.BoundDomainId.IsUnknown() {
		body.SetBoundDomainId(expandStringSet(ctx, plan.BoundDomainId))
	}

	// Set bound_domain_name
	if !plan.BoundDomainName.IsNull() && !plan.BoundDomainName.IsUnknown() {
		body.SetBoundDomainName(expandStringSet(ctx, plan.BoundDomainName))
	}

	// Set bound_ips
	if !plan.BoundIps.IsNull() && !plan.BoundIps.IsUnknown() {
		body.SetBoundIps(expandStringSet(ctx, plan.BoundIps))
	}

	// Set bound_tenant_id
	if !plan.BoundTenantId.IsNull() && !plan.BoundTenantId.IsUnknown() {
		body.SetBoundTenantId(expandStringSet(ctx, plan.BoundTenantId))
	}

	// Set bound_tenant_name
	if !plan.BoundTenantName.IsNull() && !plan.BoundTenantName.IsUnknown() {
		body.SetBoundTenantName(expandStringSet(ctx, plan.BoundTenantName))
	}

	// Set bound_user_id
	if !plan.BoundUserId.IsNull() && !plan.BoundUserId.IsUnknown() {
		body.SetBoundUserId(expandStringSet(ctx, plan.BoundUserId))
	}

	// Set bound_user_name
	if !plan.BoundUserName.IsNull() && !plan.BoundUserName.IsUnknown() {
		body.SetBoundUserName(expandStringSet(ctx, plan.BoundUserName))
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueString()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set expiration_event_in
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}

	// Set force_sub_claims
	if !plan.ForceSubClaims.IsNull() && !plan.ForceSubClaims.IsUnknown() {
		v := plan.ForceSubClaims.ValueBool()
		body.SetForceSubClaims(&v)
	}

	// Set gw_bound_ips
	if !plan.GwBoundIps.IsNull() && !plan.GwBoundIps.IsUnknown() {
		body.SetGwBoundIps(expandStringSet(ctx, plan.GwBoundIps))
	}

	// Set jwt_ttl
	if !plan.JwtTtl.IsNull() && !plan.JwtTtl.IsUnknown() {
		v := plan.JwtTtl.ValueInt64()
		body.SetJwtTtl(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set product_type
	if !plan.ProductType.IsNull() && !plan.ProductType.IsUnknown() {
		body.SetProductType(expandStringSet(ctx, plan.ProductType))
	}

	tflog.Debug(ctx, "Creating AuthMethodHuawei")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating AuthMethodHuawei", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodHuaweiResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state AuthMethodHuaweiModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodHuaweiResource) readResource(ctx context.Context, id string) (AuthMethodHuaweiModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state AuthMethodHuaweiModel

	body := akeyless_api.NewReadBody("/get-auth-method")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading AuthMethodHuawei", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	// TODO: state.AccessExpires = ... // no read_mapping defined
	// TODO: state.AllowedClientType = ... // no read_mapping defined
	// TODO: state.AuditLogsClaims = ... // no read_mapping defined
	// TODO: state.AuthUrl = ... // no read_mapping defined
	// TODO: state.BoundDomainId = ... // no read_mapping defined
	// TODO: state.BoundDomainName = ... // no read_mapping defined
	// TODO: state.BoundIps = ... // no read_mapping defined
	// TODO: state.BoundTenantId = ... // no read_mapping defined
	// TODO: state.BoundTenantName = ... // no read_mapping defined
	// TODO: state.BoundUserId = ... // no read_mapping defined
	// TODO: state.BoundUserName = ... // no read_mapping defined
	// TODO: state.DeleteProtection = ... // no read_mapping defined
	// TODO: state.Description = ... // no read_mapping defined
	// TODO: state.ExpirationEventIn = ... // no read_mapping defined
	// TODO: state.ForceSubClaims = ... // no read_mapping defined
	// TODO: state.GwBoundIps = ... // no read_mapping defined
	// TODO: state.JwtTtl = ... // no read_mapping defined
	// TODO: state.Name = ... // no read_mapping defined
	// TODO: state.ProductType = ... // no read_mapping defined
	_ = result

	return state, diags
}

func (r *AuthMethodHuaweiResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan AuthMethodHuaweiModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/update-auth-method")
	if !plan.AccessExpires.IsNull() && !plan.AccessExpires.IsUnknown() {
		v := plan.AccessExpires.ValueInt64()
		body.SetAccessExpires(&v)
	}
	if !plan.AllowedClientType.IsNull() && !plan.AllowedClientType.IsUnknown() {
		body.SetAllowedClientType(expandStringSet(ctx, plan.AllowedClientType))
	}
	if !plan.AuditLogsClaims.IsNull() && !plan.AuditLogsClaims.IsUnknown() {
		body.SetAuditLogsClaims(expandStringSet(ctx, plan.AuditLogsClaims))
	}
	if !plan.AuthUrl.IsNull() && !plan.AuthUrl.IsUnknown() {
		v := plan.AuthUrl.ValueString()
		body.SetAuthUrl(&v)
	}
	if !plan.BoundDomainId.IsNull() && !plan.BoundDomainId.IsUnknown() {
		body.SetBoundDomainId(expandStringSet(ctx, plan.BoundDomainId))
	}
	if !plan.BoundDomainName.IsNull() && !plan.BoundDomainName.IsUnknown() {
		body.SetBoundDomainName(expandStringSet(ctx, plan.BoundDomainName))
	}
	if !plan.BoundIps.IsNull() && !plan.BoundIps.IsUnknown() {
		body.SetBoundIps(expandStringSet(ctx, plan.BoundIps))
	}
	if !plan.BoundTenantId.IsNull() && !plan.BoundTenantId.IsUnknown() {
		body.SetBoundTenantId(expandStringSet(ctx, plan.BoundTenantId))
	}
	if !plan.BoundTenantName.IsNull() && !plan.BoundTenantName.IsUnknown() {
		body.SetBoundTenantName(expandStringSet(ctx, plan.BoundTenantName))
	}
	if !plan.BoundUserId.IsNull() && !plan.BoundUserId.IsUnknown() {
		body.SetBoundUserId(expandStringSet(ctx, plan.BoundUserId))
	}
	if !plan.BoundUserName.IsNull() && !plan.BoundUserName.IsUnknown() {
		body.SetBoundUserName(expandStringSet(ctx, plan.BoundUserName))
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueString()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}
	if !plan.ForceSubClaims.IsNull() && !plan.ForceSubClaims.IsUnknown() {
		v := plan.ForceSubClaims.ValueBool()
		body.SetForceSubClaims(&v)
	}
	if !plan.GwBoundIps.IsNull() && !plan.GwBoundIps.IsUnknown() {
		body.SetGwBoundIps(expandStringSet(ctx, plan.GwBoundIps))
	}
	if !plan.JwtTtl.IsNull() && !plan.JwtTtl.IsUnknown() {
		v := plan.JwtTtl.ValueInt64()
		body.SetJwtTtl(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProductType.IsNull() && !plan.ProductType.IsUnknown() {
		body.SetProductType(expandStringSet(ctx, plan.ProductType))
	}

	tflog.Debug(ctx, "Updating AuthMethodHuawei")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating AuthMethodHuawei", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodHuaweiResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state AuthMethodHuaweiModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-auth-method")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting AuthMethodHuawei", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting AuthMethodHuawei", err.Error())
		return
	}
}

func (r *AuthMethodHuaweiResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
