// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretGithubResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretGithubResource{}
	_ resource.ResourceWithImportState = &DynamicSecretGithubResource{}
)

type DynamicSecretGithubResource struct {
	client *AkeylessClient
}

func NewDynamicSecretGithubResource() resource.Resource {
	return &DynamicSecretGithubResource{}
}

type DynamicSecretGithubModel struct {
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	GithubAppId types.Int64 `tfsdk:"github_app_id"`
	GithubAppPrivateKey types.String `tfsdk:"github_app_private_key"`
	GithubBaseUrl types.String `tfsdk:"github_base_url"`
	InstallationId types.Int64 `tfsdk:"installation_id"`
	InstallationOrganization types.String `tfsdk:"installation_organization"`
	InstallationRepository types.String `tfsdk:"installation_repository"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	TokenPermissions types.Set `tfsdk:"token_permissions"`
	TokenRepositories types.Set `tfsdk:"token_repositories"`
	TokenTtl types.String `tfsdk:"token_ttl"`
}

func (r *DynamicSecretGithubResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_github"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"github_app_id": schema.Int64Attribute{
				Description: "GitHub App ID",
				Optional: true,
			},
			"github_app_private_key": schema.StringAttribute{
				Description: "GitHub App private key (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"github_base_url": schema.StringAttribute{
				Description: "GitHub base URL (for GitHub Enterprise)",
				Optional: true,
			},
			"installation_id": schema.Int64Attribute{
				Description: "GitHub App installation ID",
				Optional: true,
			},
			"installation_organization": schema.StringAttribute{
				Description: "GitHub organization for installation",
				Optional: true,
			},
			"installation_repository": schema.StringAttribute{
				Description: "GitHub repository for installation",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"token_permissions": schema.SetAttribute{
				Description: "GitHub token permissions (JSON)",
				Optional: true,
				ElementType: types.StringType{},
			},
			"token_repositories": schema.SetAttribute{
				Description: "GitHub repositories for token scope (comma-separated)",
				Optional: true,
				ElementType: types.StringType{},
			},
			"token_ttl": schema.StringAttribute{
				Description: "Token TTL",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretGithubResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretGithubResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretGithubModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-github")

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set github_app_id
	if !plan.GithubAppId.IsNull() && !plan.GithubAppId.IsUnknown() {
		v := plan.GithubAppId.ValueInt64()
		body.SetGithubAppId(&v)
	}

	// Set github_app_private_key
	if !plan.GithubAppPrivateKey.IsNull() && !plan.GithubAppPrivateKey.IsUnknown() {
		v := plan.GithubAppPrivateKey.ValueString()
		body.SetGithubAppPrivateKey(&v)
	}

	// Set github_base_url
	if !plan.GithubBaseUrl.IsNull() && !plan.GithubBaseUrl.IsUnknown() {
		v := plan.GithubBaseUrl.ValueString()
		body.SetGithubBaseUrl(&v)
	}

	// Set installation_id
	if !plan.InstallationId.IsNull() && !plan.InstallationId.IsUnknown() {
		v := plan.InstallationId.ValueInt64()
		body.SetInstallationId(&v)
	}

	// Set installation_organization
	if !plan.InstallationOrganization.IsNull() && !plan.InstallationOrganization.IsUnknown() {
		v := plan.InstallationOrganization.ValueString()
		body.SetInstallationOrganization(&v)
	}

	// Set installation_repository
	if !plan.InstallationRepository.IsNull() && !plan.InstallationRepository.IsUnknown() {
		v := plan.InstallationRepository.ValueString()
		body.SetInstallationRepository(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set token_permissions
	if !plan.TokenPermissions.IsNull() && !plan.TokenPermissions.IsUnknown() {
		body.SetTokenPermissions(expandStringSet(ctx, plan.TokenPermissions))
	}

	// Set token_repositories
	if !plan.TokenRepositories.IsNull() && !plan.TokenRepositories.IsUnknown() {
		body.SetTokenRepositories(expandStringSet(ctx, plan.TokenRepositories))
	}

	// Set token_ttl
	if !plan.TokenTtl.IsNull() && !plan.TokenTtl.IsUnknown() {
		v := plan.TokenTtl.ValueString()
		body.SetTokenTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretGithub")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretGithub", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretGithubResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretGithubModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretGithubResource) readResource(ctx context.Context, id string) (DynamicSecretGithubModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretGithubModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretGithub", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretGithubResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretGithubModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-github")
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.GithubAppId.IsNull() && !plan.GithubAppId.IsUnknown() {
		v := plan.GithubAppId.ValueInt64()
		body.SetGithubAppId(&v)
	}
	if !plan.GithubAppPrivateKey.IsNull() && !plan.GithubAppPrivateKey.IsUnknown() {
		v := plan.GithubAppPrivateKey.ValueString()
		body.SetGithubAppPrivateKey(&v)
	}
	if !plan.GithubBaseUrl.IsNull() && !plan.GithubBaseUrl.IsUnknown() {
		v := plan.GithubBaseUrl.ValueString()
		body.SetGithubBaseUrl(&v)
	}
	if !plan.InstallationId.IsNull() && !plan.InstallationId.IsUnknown() {
		v := plan.InstallationId.ValueInt64()
		body.SetInstallationId(&v)
	}
	if !plan.InstallationOrganization.IsNull() && !plan.InstallationOrganization.IsUnknown() {
		v := plan.InstallationOrganization.ValueString()
		body.SetInstallationOrganization(&v)
	}
	if !plan.InstallationRepository.IsNull() && !plan.InstallationRepository.IsUnknown() {
		v := plan.InstallationRepository.ValueString()
		body.SetInstallationRepository(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.TokenPermissions.IsNull() && !plan.TokenPermissions.IsUnknown() {
		body.SetTokenPermissions(expandStringSet(ctx, plan.TokenPermissions))
	}
	if !plan.TokenRepositories.IsNull() && !plan.TokenRepositories.IsUnknown() {
		body.SetTokenRepositories(expandStringSet(ctx, plan.TokenRepositories))
	}
	if !plan.TokenTtl.IsNull() && !plan.TokenTtl.IsUnknown() {
		v := plan.TokenTtl.ValueString()
		body.SetTokenTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretGithub")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretGithub", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretGithubResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretGithubModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretGithub", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretGithub", err.Error())
		return
	}
}

func (r *DynamicSecretGithubResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
