// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &RotatedSecretGcpResource{}
	_ resource.ResourceWithConfigure   = &RotatedSecretGcpResource{}
	_ resource.ResourceWithImportState = &RotatedSecretGcpResource{}
)

type RotatedSecretGcpResource struct {
	client *AkeylessClient
}

func NewRotatedSecretGcpResource() resource.Resource {
	return &RotatedSecretGcpResource{}
}

type RotatedSecretGcpModel struct {
	AuthenticationCredentials types.String `tfsdk:"authentication_credentials"`
	AutoRotate types.String `tfsdk:"auto_rotate"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	GcpKey types.String `tfsdk:"gcp_key"`
	GcpServiceAccountEmail types.String `tfsdk:"gcp_service_account_email"`
	GcpServiceAccountKeyId types.String `tfsdk:"gcp_service_account_key_id"`
	GraceRotation types.String `tfsdk:"grace_rotation"`
	GraceRotationHour types.Int64 `tfsdk:"grace_rotation_hour"`
	GraceRotationInterval types.String `tfsdk:"grace_rotation_interval"`
	GraceRotationTiming types.String `tfsdk:"grace_rotation_timing"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	PasswordLength types.String `tfsdk:"password_length"`
	RotationEventIn types.Set `tfsdk:"rotation_event_in"`
	RotationHour types.Int64 `tfsdk:"rotation_hour"`
	RotationInterval types.String `tfsdk:"rotation_interval"`
	RotatorType types.String `tfsdk:"rotator_type"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
}

func (r *RotatedSecretGcpResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_rotated_secret_gcp"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_credentials": schema.StringAttribute{
				Description: "Credentials to connect with: use-user-creds or use-target-creds",
				Optional: true,
			},
			"auto_rotate": schema.StringAttribute{
				Description: "Whether to automatically rotate every rotation-interval days [true/false]",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"gcp_key": schema.StringAttribute{
				Description: "Base64-encoded service account private key text",
				Optional: true,
			},
			"gcp_service_account_email": schema.StringAttribute{
				Description: "The email of the gcp service account to rotate",
				Optional: true,
			},
			"gcp_service_account_key_id": schema.StringAttribute{
				Description: "The key id of the gcp service account to rotate",
				Optional: true,
			},
			"grace_rotation": schema.StringAttribute{
				Description: "Enable graceful rotation (keep both versions temporarily). When enabled, a new secret version is created while the previous version is kept for the grace period, so both versions exist for a limited time. [true/false]",
				Optional: true,
			},
			"grace_rotation_hour": schema.Int64Attribute{
				Description: "The Hour of the grace rotation in UTC",
				Optional: true,
			},
			"grace_rotation_interval": schema.StringAttribute{
				Description: "The number of days to wait before deleting the old key (must be bigger than rotation-interval)",
				Optional: true,
			},
			"grace_rotation_timing": schema.StringAttribute{
				Description: "When to create the new version relative to the rotation date [after/before]",
				Optional: true,
			},
			"key": schema.StringAttribute{
				Description: "Encryption key name for the secret value",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Maximum number of versions",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Rotated secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"rotation_event_in": schema.SetAttribute{
				Description: "How many days before the rotation of the item would you like to be notified",
				Optional: true,
				ElementType: types.StringType{},
			},
			"rotation_hour": schema.Int64Attribute{
				Description: "The hour of the rotation in UTC",
				Optional: true,
			},
			"rotation_interval": schema.StringAttribute{
				Description: "Days between every automatic key rotation (1-365)",
				Optional: true,
			},
			"rotator_type": schema.StringAttribute{
				Description: "The rotator type: target or api-key",
				Required: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the rotated secret",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name to associate",
				Required: true,
			},
		},
	}
}

func (r *RotatedSecretGcpResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *RotatedSecretGcpResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan RotatedSecretGcpModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/rotated-secret-create-gcp")

	// Set authentication_credentials
	if !plan.AuthenticationCredentials.IsNull() && !plan.AuthenticationCredentials.IsUnknown() {
		v := plan.AuthenticationCredentials.ValueString()
		body.SetAuthenticationCredentials(&v)
	}

	// Set auto_rotate
	if !plan.AutoRotate.IsNull() && !plan.AutoRotate.IsUnknown() {
		v := plan.AutoRotate.ValueString()
		body.SetAutoRotate(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set gcp_key
	if !plan.GcpKey.IsNull() && !plan.GcpKey.IsUnknown() {
		v := plan.GcpKey.ValueString()
		body.SetGcpKey(&v)
	}

	// Set gcp_service_account_email
	if !plan.GcpServiceAccountEmail.IsNull() && !plan.GcpServiceAccountEmail.IsUnknown() {
		v := plan.GcpServiceAccountEmail.ValueString()
		body.SetGcpServiceAccountEmail(&v)
	}

	// Set gcp_service_account_key_id
	if !plan.GcpServiceAccountKeyId.IsNull() && !plan.GcpServiceAccountKeyId.IsUnknown() {
		v := plan.GcpServiceAccountKeyId.ValueString()
		body.SetGcpServiceAccountKeyId(&v)
	}

	// Set grace_rotation
	if !plan.GraceRotation.IsNull() && !plan.GraceRotation.IsUnknown() {
		v := plan.GraceRotation.ValueString()
		body.SetGraceRotation(&v)
	}

	// Set grace_rotation_hour
	if !plan.GraceRotationHour.IsNull() && !plan.GraceRotationHour.IsUnknown() {
		v := plan.GraceRotationHour.ValueInt64()
		body.SetGraceRotationHour(&v)
	}

	// Set grace_rotation_interval
	if !plan.GraceRotationInterval.IsNull() && !plan.GraceRotationInterval.IsUnknown() {
		v := plan.GraceRotationInterval.ValueString()
		body.SetGraceRotationInterval(&v)
	}

	// Set grace_rotation_timing
	if !plan.GraceRotationTiming.IsNull() && !plan.GraceRotationTiming.IsUnknown() {
		v := plan.GraceRotationTiming.ValueString()
		body.SetGraceRotationTiming(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set rotation_event_in
	if !plan.RotationEventIn.IsNull() && !plan.RotationEventIn.IsUnknown() {
		body.SetRotationEventIn(expandStringSet(ctx, plan.RotationEventIn))
	}

	// Set rotation_hour
	if !plan.RotationHour.IsNull() && !plan.RotationHour.IsUnknown() {
		v := plan.RotationHour.ValueInt64()
		body.SetRotationHour(&v)
	}

	// Set rotation_interval
	if !plan.RotationInterval.IsNull() && !plan.RotationInterval.IsUnknown() {
		v := plan.RotationInterval.ValueString()
		body.SetRotationInterval(&v)
	}

	// Set rotator_type
	if !plan.RotatorType.IsNull() && !plan.RotatorType.IsUnknown() {
		v := plan.RotatorType.ValueString()
		body.SetRotatorType(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	tflog.Debug(ctx, "Creating RotatedSecretGcp")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating RotatedSecretGcp", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *RotatedSecretGcpResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state RotatedSecretGcpModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *RotatedSecretGcpResource) readResource(ctx context.Context, id string) (RotatedSecretGcpModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state RotatedSecretGcpModel

	body := akeyless_api.NewReadBody("/describe-item")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading RotatedSecretGcp", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "delete_protection"); ok {
		state.DeleteProtection = types.BoolValue(v == "true")
	}
	if v, ok := GetNestedString(result, "item_metadata"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "rotation_interval"); ok {
		state.RotationInterval = types.StringValue(v)
	}
	if v, ok := GetNestedStringSlice(result, "item_tags"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.Tags = setVal
	}

	return state, diags
}

func (r *RotatedSecretGcpResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan RotatedSecretGcpModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/rotated-secret-update-gcp")
	if !plan.AuthenticationCredentials.IsNull() && !plan.AuthenticationCredentials.IsUnknown() {
		v := plan.AuthenticationCredentials.ValueString()
		body.SetAuthenticationCredentials(&v)
	}
	if !plan.AutoRotate.IsNull() && !plan.AutoRotate.IsUnknown() {
		v := plan.AutoRotate.ValueString()
		body.SetAutoRotate(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.GcpKey.IsNull() && !plan.GcpKey.IsUnknown() {
		v := plan.GcpKey.ValueString()
		body.SetGcpKey(&v)
	}
	if !plan.GcpServiceAccountEmail.IsNull() && !plan.GcpServiceAccountEmail.IsUnknown() {
		v := plan.GcpServiceAccountEmail.ValueString()
		body.SetGcpServiceAccountEmail(&v)
	}
	if !plan.GcpServiceAccountKeyId.IsNull() && !plan.GcpServiceAccountKeyId.IsUnknown() {
		v := plan.GcpServiceAccountKeyId.ValueString()
		body.SetGcpServiceAccountKeyId(&v)
	}
	if !plan.GraceRotation.IsNull() && !plan.GraceRotation.IsUnknown() {
		v := plan.GraceRotation.ValueString()
		body.SetGraceRotation(&v)
	}
	if !plan.GraceRotationHour.IsNull() && !plan.GraceRotationHour.IsUnknown() {
		v := plan.GraceRotationHour.ValueInt64()
		body.SetGraceRotationHour(&v)
	}
	if !plan.GraceRotationInterval.IsNull() && !plan.GraceRotationInterval.IsUnknown() {
		v := plan.GraceRotationInterval.ValueString()
		body.SetGraceRotationInterval(&v)
	}
	if !plan.GraceRotationTiming.IsNull() && !plan.GraceRotationTiming.IsUnknown() {
		v := plan.GraceRotationTiming.ValueString()
		body.SetGraceRotationTiming(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.RotationEventIn.IsNull() && !plan.RotationEventIn.IsUnknown() {
		body.SetRotationEventIn(expandStringSet(ctx, plan.RotationEventIn))
	}
	if !plan.RotationHour.IsNull() && !plan.RotationHour.IsUnknown() {
		v := plan.RotationHour.ValueInt64()
		body.SetRotationHour(&v)
	}
	if !plan.RotationInterval.IsNull() && !plan.RotationInterval.IsUnknown() {
		v := plan.RotationInterval.ValueString()
		body.SetRotationInterval(&v)
	}
	if !plan.RotatorType.IsNull() && !plan.RotatorType.IsUnknown() {
		v := plan.RotatorType.ValueString()
		body.SetRotatorType(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	tflog.Debug(ctx, "Updating RotatedSecretGcp")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating RotatedSecretGcp", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *RotatedSecretGcpResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state RotatedSecretGcpModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-item")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting RotatedSecretGcp", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting RotatedSecretGcp", err.Error())
		return
	}
}

func (r *RotatedSecretGcpResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
