// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetLetsEncryptResource{}
	_ resource.ResourceWithConfigure   = &TargetLetsEncryptResource{}
	_ resource.ResourceWithImportState = &TargetLetsEncryptResource{}
)

type TargetLetsEncryptResource struct {
	client *AkeylessClient
}

func NewTargetLetsEncryptResource() resource.Resource {
	return &TargetLetsEncryptResource{}
}

type TargetLetsEncryptModel struct {
	AcmeChallenge types.String `tfsdk:"acme_challenge"`
	Description types.String `tfsdk:"description"`
	DnsTargetCreds types.String `tfsdk:"dns_target_creds"`
	Email types.String `tfsdk:"email"`
	GcpProject types.String `tfsdk:"gcp_project"`
	HostedZone types.String `tfsdk:"hosted_zone"`
	Key types.String `tfsdk:"key"`
	LetsEncryptUrl types.String `tfsdk:"lets_encrypt_url"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	ResourceGroup types.String `tfsdk:"resource_group"`
	Timeout types.String `tfsdk:"timeout"`
}

func (r *TargetLetsEncryptResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_lets_encrypt"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"acme_challenge": schema.StringAttribute{
				Description: "",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"dns_target_creds": schema.StringAttribute{
				Description: "Name of existing cloud target for DNS credentials. Required when acme-challenge=dns. Supported: AWS, Azure, GCP targets",
				Optional: true,
			},
			"email": schema.StringAttribute{
				Description: "Email address for ACME account registration",
				Optional: true,
			},
			"gcp_project": schema.StringAttribute{
				Description: "GCP Cloud DNS: Project ID. Optional - can be derived from service account",
				Optional: true,
			},
			"hosted_zone": schema.StringAttribute{
				Description: "AWS Route53 hosted zone ID. Required when dns-target-creds points to AWS target",
				Optional: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)",
				Optional: true,
			},
			"lets_encrypt_url": schema.StringAttribute{
				Description: "",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"resource_group": schema.StringAttribute{
				Description: "Azure resource group name. Required when dns-target-creds points to Azure target",
				Optional: true,
			},
			"timeout": schema.StringAttribute{
				Description: "",
				Optional: true,
			},
		},
	}
}

func (r *TargetLetsEncryptResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetLetsEncryptResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetLetsEncryptModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-lets-encrypt")

	// Set acme_challenge
	if !plan.AcmeChallenge.IsNull() && !plan.AcmeChallenge.IsUnknown() {
		v := plan.AcmeChallenge.ValueString()
		body.SetAcmeChallenge(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set dns_target_creds
	if !plan.DnsTargetCreds.IsNull() && !plan.DnsTargetCreds.IsUnknown() {
		v := plan.DnsTargetCreds.ValueString()
		body.SetDnsTargetCreds(&v)
	}

	// Set email
	if !plan.Email.IsNull() && !plan.Email.IsUnknown() {
		v := plan.Email.ValueString()
		body.SetEmail(&v)
	}

	// Set gcp_project
	if !plan.GcpProject.IsNull() && !plan.GcpProject.IsUnknown() {
		v := plan.GcpProject.ValueString()
		body.SetGcpProject(&v)
	}

	// Set hosted_zone
	if !plan.HostedZone.IsNull() && !plan.HostedZone.IsUnknown() {
		v := plan.HostedZone.ValueString()
		body.SetHostedZone(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set lets_encrypt_url
	if !plan.LetsEncryptUrl.IsNull() && !plan.LetsEncryptUrl.IsUnknown() {
		v := plan.LetsEncryptUrl.ValueString()
		body.SetLetsEncryptUrl(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set resource_group
	if !plan.ResourceGroup.IsNull() && !plan.ResourceGroup.IsUnknown() {
		v := plan.ResourceGroup.ValueString()
		body.SetResourceGroup(&v)
	}

	// Set timeout
	if !plan.Timeout.IsNull() && !plan.Timeout.IsUnknown() {
		v := plan.Timeout.ValueString()
		body.SetTimeout(&v)
	}

	tflog.Debug(ctx, "Creating TargetLetsEncrypt")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetLetsEncrypt", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetLetsEncryptResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetLetsEncryptModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetLetsEncryptResource) readResource(ctx context.Context, id string) (TargetLetsEncryptModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetLetsEncryptModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetLetsEncrypt", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetLetsEncryptResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetLetsEncryptModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-lets-encrypt")
	if !plan.AcmeChallenge.IsNull() && !plan.AcmeChallenge.IsUnknown() {
		v := plan.AcmeChallenge.ValueString()
		body.SetAcmeChallenge(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.DnsTargetCreds.IsNull() && !plan.DnsTargetCreds.IsUnknown() {
		v := plan.DnsTargetCreds.ValueString()
		body.SetDnsTargetCreds(&v)
	}
	if !plan.Email.IsNull() && !plan.Email.IsUnknown() {
		v := plan.Email.ValueString()
		body.SetEmail(&v)
	}
	if !plan.GcpProject.IsNull() && !plan.GcpProject.IsUnknown() {
		v := plan.GcpProject.ValueString()
		body.SetGcpProject(&v)
	}
	if !plan.HostedZone.IsNull() && !plan.HostedZone.IsUnknown() {
		v := plan.HostedZone.ValueString()
		body.SetHostedZone(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.LetsEncryptUrl.IsNull() && !plan.LetsEncryptUrl.IsUnknown() {
		v := plan.LetsEncryptUrl.ValueString()
		body.SetLetsEncryptUrl(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ResourceGroup.IsNull() && !plan.ResourceGroup.IsUnknown() {
		v := plan.ResourceGroup.ValueString()
		body.SetResourceGroup(&v)
	}
	if !plan.Timeout.IsNull() && !plan.Timeout.IsUnknown() {
		v := plan.Timeout.ValueString()
		body.SetTimeout(&v)
	}

	tflog.Debug(ctx, "Updating TargetLetsEncrypt")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetLetsEncrypt", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetLetsEncryptResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetLetsEncryptModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetLetsEncrypt", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetLetsEncrypt", err.Error())
		return
	}
}

func (r *TargetLetsEncryptResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
