// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &GatewayMigrationResource{}
	_ resource.ResourceWithConfigure   = &GatewayMigrationResource{}
	_ resource.ResourceWithImportState = &GatewayMigrationResource{}
)

type GatewayMigrationResource struct {
	client *AkeylessClient
}

func NewGatewayMigrationResource() resource.Resource {
	return &GatewayMigrationResource{}
}

type GatewayMigrationModel struct {
	ServiceAccountKeyDecoded types.String `tfsdk:"ServiceAccountKeyDecoded"`
	AdAutoRotate types.String `tfsdk:"ad_auto_rotate"`
	AdCertExpirationEventIn types.Set `tfsdk:"ad_cert_expiration_event_in"`
	AdCertificatesPathTemplate types.String `tfsdk:"ad_certificates_path_template"`
	AdComputerBaseDn types.String `tfsdk:"ad_computer_base_dn"`
	AdDiscoverIisApp types.String `tfsdk:"ad_discover_iis_app"`
	AdDiscoverServices types.String `tfsdk:"ad_discover_services"`
	AdDiscoveryTypes types.Set `tfsdk:"ad_discovery_types"`
	AdDomainName types.String `tfsdk:"ad_domain_name"`
	AdDomainUsersPathTemplate types.String `tfsdk:"ad_domain_users_path_template"`
	AdLocalUsersIgnore types.String `tfsdk:"ad_local_users_ignore"`
	AdLocalUsersPathTemplate types.String `tfsdk:"ad_local_users_path_template"`
	AdOsFilter types.String `tfsdk:"ad_os_filter"`
	AdRotationHour types.Int64 `tfsdk:"ad_rotation_hour"`
	AdRotationInterval types.Int64 `tfsdk:"ad_rotation_interval"`
	AdSraEnableRdp types.String `tfsdk:"ad_sra_enable_rdp"`
	AdSshPort types.String `tfsdk:"ad_ssh_port"`
	AdTargetFormat types.String `tfsdk:"ad_target_format"`
	AdTargetName types.String `tfsdk:"ad_target_name"`
	AdTargetsPathTemplate types.String `tfsdk:"ad_targets_path_template"`
	AdTargetsType types.String `tfsdk:"ad_targets_type"`
	AdUserBaseDn types.String `tfsdk:"ad_user_base_dn"`
	AdUserGroups types.String `tfsdk:"ad_user_groups"`
	AdWinrmOverHttp types.String `tfsdk:"ad_winrm_over_http"`
	AdWinrmPort types.String `tfsdk:"ad_winrm_port"`
	AdDiscoverLocalUsers types.String `tfsdk:"ad_discover_local_users"`
	AiCertificateDiscovery types.String `tfsdk:"ai_certificate_discovery"`
	AwsKey types.String `tfsdk:"aws_key"`
	AwsKeyId types.String `tfsdk:"aws_key_id"`
	AwsRegion types.String `tfsdk:"aws_region"`
	AzureClientId types.String `tfsdk:"azure_client_id"`
	AzureKvName types.String `tfsdk:"azure_kv_name"`
	AzureSecret types.String `tfsdk:"azure_secret"`
	AzureTenantId types.String `tfsdk:"azure_tenant_id"`
	ConjurAccount types.String `tfsdk:"conjur_account"`
	ConjurApiKey types.String `tfsdk:"conjur_api_key"`
	ConjurUrl types.String `tfsdk:"conjur_url"`
	ConjurUsername types.String `tfsdk:"conjur_username"`
	ExpirationEventIn types.Set `tfsdk:"expiration_event_in"`
	GcpKey types.String `tfsdk:"gcp_key"`
	GcpProjectId types.String `tfsdk:"gcp_project_id"`
	HashiJson types.String `tfsdk:"hashi_json"`
	HashiNs types.Set `tfsdk:"hashi_ns"`
	HashiToken types.String `tfsdk:"hashi_token"`
	HashiUrl types.String `tfsdk:"hashi_url"`
	Hosts types.String `tfsdk:"hosts"`
	K8sCaCertificate types.Set `tfsdk:"k8s_ca_certificate"`
	K8sClientCertificate types.Set `tfsdk:"k8s_client_certificate"`
	K8sClientKey types.Set `tfsdk:"k8s_client_key"`
	K8sNamespace types.String `tfsdk:"k8s_namespace"`
	K8sPassword types.String `tfsdk:"k8s_password"`
	K8sSkipSystem types.Bool `tfsdk:"k8s_skip_system"`
	K8sToken types.String `tfsdk:"k8s_token"`
	K8sUrl types.String `tfsdk:"k8s_url"`
	K8sUsername types.String `tfsdk:"k8s_username"`
	Name types.String `tfsdk:"name"`
	PortRanges types.String `tfsdk:"port_ranges"`
	ProtectionKey types.String `tfsdk:"protection_key"`
	SiAutoRotate types.String `tfsdk:"si_auto_rotate"`
	SiRotationHour types.Int64 `tfsdk:"si_rotation_hour"`
	SiRotationInterval types.Int64 `tfsdk:"si_rotation_interval"`
	SiSraEnableRdp types.String `tfsdk:"si_sra_enable_rdp"`
	SiTargetName types.String `tfsdk:"si_target_name"`
	SiUserGroups types.String `tfsdk:"si_user_groups"`
	SiUsersIgnore types.String `tfsdk:"si_users_ignore"`
	SiUsersPathTemplate types.String `tfsdk:"si_users_path_template"`
	TargetLocation types.String `tfsdk:"target_location"`
	Type types.String `tfsdk:"type"`
	UseGwCloudIdentity types.Bool `tfsdk:"use_gw_cloud_identity"`
}

func (r *GatewayMigrationResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_migration"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ServiceAccountKeyDecoded": schema.StringAttribute{
				Description: "",
				Optional: true,
			},
			"ad_auto_rotate": schema.StringAttribute{
				Description: "Enable/Disable automatic/recurrent rotation for migrated secrets. Default is false: only manual rotation is allowed for migrated secrets. If set to true, this command should be combined with --ad-rotation-interval and --ad-rotation-hour parameters (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_cert_expiration_event_in": schema.SetAttribute{
				Description: "How many days before the expiration of discovered certificates would you like to be notified (Relevant only for Active Directory migration with certificate discovery enabled)",
				Optional: true,
				ElementType: types.StringType{},
			},
			"ad_certificates_path_template": schema.StringAttribute{
				Description: "Path location template for migrating certificates e.g.: /Certificates/{{COMMON_NAME}} (Relevant only for Active Directory migration with certificate discovery enabled)",
				Optional: true,
			},
			"ad_computer_base_dn": schema.StringAttribute{
				Description: "Distinguished Name of Computer objects (servers) to search in Active Directory e.g.: CN=Computers,DC=example,DC=com (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_discover_iis_app": schema.StringAttribute{
				Description: "Enable/Disable discovery of IIS application from each domain server as part of the SSH/Windows Rotated Secrets. Default is false. (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_discover_services": schema.StringAttribute{
				Description: "Enable/Disable discovery of Windows services from each domain server as part of the SSH/Windows Rotated Secrets. Default is false. (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_discovery_types": schema.SetAttribute{
				Description: "Set migration discovery types (domain-users, computers, local-users). (Relevant only for Active Directory migration)",
				Optional: true,
				ElementType: types.StringType{},
			},
			"ad_domain_name": schema.StringAttribute{
				Description: "Active Directory Domain Name (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_domain_users_path_template": schema.StringAttribute{
				Description: "Path location template for migrating domain users as Rotated Secrets e.g.: .../DomainUsers/{{USERNAME}} (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_local_users_ignore": schema.StringAttribute{
				Description: "Comma-separated list of Local Users which should not be migrated (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_local_users_path_template": schema.StringAttribute{
				Description: "Path location template for migrating domain users as Rotated Secrets e.g.: .../LocalUsers/{{COMPUTER_NAME}}/{{USERNAME}} (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_os_filter": schema.StringAttribute{
				Description: "Filter by Operating System to run the migration, can be used with wildcards, e.g. SRV20* (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_rotation_hour": schema.Int64Attribute{
				Description: "The hour of the scheduled rotation in UTC (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_rotation_interval": schema.Int64Attribute{
				Description: "The number of days to wait between every automatic rotation [1-365] (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_sra_enable_rdp": schema.StringAttribute{
				Description: "Enable/Disable RDP Secure Remote Access for the migrated local users rotated secrets. Default is false: rotated secrets will not be created with SRA (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_ssh_port": schema.StringAttribute{
				Description: "Set the SSH Port for further connection to the domain servers. Default is port 22 (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_target_format": schema.StringAttribute{
				Description: "Relevant only for ad-discovery-types=computers. For linked, all computers will be migrated into a linked target(s). if set with regular, the migration will create a target for each computer.",
				Optional: true,
			},
			"ad_target_name": schema.StringAttribute{
				Description: "Active Directory LDAP Target Name. Server type should be Active Directory (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_targets_path_template": schema.StringAttribute{
				Description: "Path location template for migrating domain servers as SSH/Windows Targets e.g.: .../Servers/{{COMPUTER_NAME}} (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_targets_type": schema.StringAttribute{
				Description: "Set the target type of the domain servers [ssh/windows](Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_user_base_dn": schema.StringAttribute{
				Description: "Distinguished Name of User objects to search in Active Directory, e.g.: CN=Users,DC=example,DC=com (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_user_groups": schema.StringAttribute{
				Description: "Comma-separated list of domain groups from which privileged domain users will be migrated. If empty, migrate all users based on the --ad-user-base-dn (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_winrm_over_http": schema.StringAttribute{
				Description: "Use WinRM over HTTP, by default runs over HTTPS",
				Optional: true,
			},
			"ad_winrm_port": schema.StringAttribute{
				Description: "Set the WinRM Port for further connection to the domain servers. Default is 5986 (Relevant only for Active Directory migration)",
				Optional: true,
			},
			"ad_discover_local_users": schema.StringAttribute{
				Description: "Enable/Disable discovery of local users from each domain server and migrate them as SSH/Windows Rotated Secrets. Default is false: only domain users will be migrated. Discovery of local users might require further installation of SSH on the servers, based on the supplied computer base DN. This will be implemented automatically as part of the migration process (Relevant only for Active Directory migration)
Deprecated: use AdDiscoverTypes",
				Optional: true,
			},
			"ai_certificate_discovery": schema.StringAttribute{
				Description: "Enable AI-assisted certificate discovery (only when AI Insight is enabled on the Gateway)",
				Optional: true,
			},
			"aws_key": schema.StringAttribute{
				Description: "AWS Secret Access Key (relevant only for AWS migration)",
				Optional: true,
			},
			"aws_key_id": schema.StringAttribute{
				Description: "AWS Access Key ID with sufficient permissions to get all secrets, e.g. 'arn:aws:secretsmanager:[Region]:[AccountId]:secret:[/path/to/secrets/*]' (relevant only for AWS migration)",
				Optional: true,
			},
			"aws_region": schema.StringAttribute{
				Description: "AWS region of the required Secrets Manager (relevant only for AWS migration)",
				Optional: true,
			},
			"azure_client_id": schema.StringAttribute{
				Description: "Azure Key Vault Access client ID, should be Azure AD App with a service principal (relevant only for Azure Key Vault migration)",
				Optional: true,
			},
			"azure_kv_name": schema.StringAttribute{
				Description: "Azure Key Vault Name (relevant only for Azure Key Vault migration)",
				Optional: true,
			},
			"azure_secret": schema.StringAttribute{
				Description: "Azure Key Vault secret (relevant only for Azure Key Vault migration)",
				Optional: true,
			},
			"azure_tenant_id": schema.StringAttribute{
				Description: "Azure Key Vault Access tenant ID (relevant only for Azure Key Vault migration)",
				Optional: true,
			},
			"conjur_account": schema.StringAttribute{
				Description: "Conjur account name set on your Conjur server (relevant only for Conjur migration).",
				Optional: true,
			},
			"conjur_api_key": schema.StringAttribute{
				Description: "Conjur API Key for the specified user (relevant only for Conjur migration).",
				Optional: true,
			},
			"conjur_url": schema.StringAttribute{
				Description: "Conjur server base URL (relevant only for Conjur migration).
If conjur-url is HTTPS and Conjur uses a private CA/self-signed certificate,
make the CA bundle available on the Gateway and set CONJUR_SSL_CERT_PATH to its path.",
				Optional: true,
			},
			"conjur_username": schema.StringAttribute{
				Description: "Conjur username used to authenticate (relevant only for Conjur migration).",
				Optional: true,
			},
			"expiration_event_in": schema.SetAttribute{
				Description: "How many days before the expiration of the certificate would you like to be notified.",
				Optional: true,
				ElementType: types.StringType{},
			},
			"gcp_key": schema.StringAttribute{
				Description: "Base64-encoded GCP Service Account private key text with sufficient permissions to Secrets Manager, Minimum required permission is Secret Manager Secret Accessor, e.g. 'roles/secretmanager.secretAccessor' (relevant only for GCP migration)",
				Optional: true,
			},
			"gcp_project_id": schema.StringAttribute{
				Description: "GCP Project ID (cross-project override)",
				Optional: true,
			},
			"hashi_json": schema.StringAttribute{
				Description: "Import secret key as json value or independent secrets (relevant only for HasiCorp Vault migration) [true/false]",
				Optional: true,
			},
			"hashi_ns": schema.SetAttribute{
				Description: "HashiCorp Vault Namespaces is a comma-separated list of namespaces which need to be imported into Akeyless Vault. For every provided namespace, all its child namespaces are imported as well, e.g. nmsp/subnmsp1/subnmsp2,nmsp/anothernmsp. By default, import all namespaces (relevant only for HasiCorp Vault migration)",
				Optional: true,
				ElementType: types.StringType{},
			},
			"hashi_token": schema.StringAttribute{
				Description: "HashiCorp Vault access token with sufficient permissions to preform list & read operations on secrets objects (relevant only for HasiCorp Vault migration)",
				Optional: true,
			},
			"hashi_url": schema.StringAttribute{
				Description: "HashiCorp Vault API URL, e.g. https://vault-mgr01:8200 (relevant only for HasiCorp Vault migration)",
				Optional: true,
			},
			"hosts": schema.StringAttribute{
				Description: "A comma separated list of IPs, CIDR ranges, or DNS names to scan",
				Required: true,
			},
			"k8s_ca_certificate": schema.SetAttribute{
				Description: "For Certificate Authentication method
K8s Cluster CA certificate (relevant only for K8s migration with Certificate Authentication method)",
				Optional: true,
				ElementType: types.Int64Type{},
			},
			"k8s_client_certificate": schema.SetAttribute{
				Description: "K8s Client certificate with sufficient permission to list and get secrets in the namespace(s) you selected (relevant only for K8s migration with Certificate Authentication method)",
				Optional: true,
				ElementType: types.Int64Type{},
			},
			"k8s_client_key": schema.SetAttribute{
				Description: "K8s Client key (relevant only for K8s migration with Certificate Authentication method)",
				Optional: true,
				ElementType: types.Int64Type{},
			},
			"k8s_namespace": schema.StringAttribute{
				Description: "K8s Namespace, Use this field to import secrets from a particular namespace only. By default, the secrets are imported from all namespaces (relevant only for K8s migration)",
				Optional: true,
			},
			"k8s_password": schema.StringAttribute{
				Description: "K8s Client password (relevant only for K8s migration with Password Authentication method)",
				Optional: true,
			},
			"k8s_skip_system": schema.BoolAttribute{
				Description: "K8s Skip Control Plane Secrets, This option allows to avoid importing secrets from system namespaces (relevant only for K8s migration)",
				Optional: true,
			},
			"k8s_token": schema.StringAttribute{
				Description: "For Token Authentication method
K8s Bearer Token with sufficient permission to list and get secrets in the namespace(s) you selected (relevant only for K8s migration with Token Authentication method)",
				Optional: true,
			},
			"k8s_url": schema.StringAttribute{
				Description: "K8s API Server URL, e.g. https://k8s-api.mycompany.com:6443 (relevant only for K8s migration)",
				Optional: true,
			},
			"k8s_username": schema.StringAttribute{
				Description: "For Password Authentication method
K8s Client username with sufficient permission to list and get secrets in the namespace(s) you selected (relevant only for K8s migration with Password Authentication method)",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Migration name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"port_ranges": schema.StringAttribute{
				Description: "A comma separated list of port ranges
Examples: \"80,443\" or \"80,443,8080-8090\" or \"443\"",
				Optional: true,
			},
			"protection_key": schema.StringAttribute{
				Description: "The name of the key that protects the classic key value (if empty, the account default key will be used)",
				Optional: true,
			},
			"si_auto_rotate": schema.StringAttribute{
				Description: "Enable/Disable automatic/recurrent rotation for migrated secrets. Default is false: only manual rotation is allowed for migrated secrets. If set to true, this command should be combined with --si-rotation-interval and --si-rotation-hour parameters (Relevant only for Server Inventory migration)",
				Optional: true,
			},
			"si_rotation_hour": schema.Int64Attribute{
				Description: "The hour of the scheduled rotation in UTC (Relevant only for Server Inventory migration)",
				Optional: true,
			},
			"si_rotation_interval": schema.Int64Attribute{
				Description: "The number of days to wait between every automatic rotation [1-365] (Relevant only for Server Inventory migration)",
				Optional: true,
			},
			"si_sra_enable_rdp": schema.StringAttribute{
				Description: "Enable/Disable RDP Secure Remote Access for the migrated local users rotated secrets. Default is false: rotated secrets will not be created with SRA (Relevant only for Server Inventory migration)",
				Optional: true,
			},
			"si_target_name": schema.StringAttribute{
				Description: "SSH, Windows or Linked Target Name. (Relevant only for Server Inventory migration)",
				Required: true,
			},
			"si_user_groups": schema.StringAttribute{
				Description: "Comma-separated list of groups to migrate users from. If empty, all users from all groups will be migrated (Relevant only for Server Inventory migration)",
				Optional: true,
			},
			"si_users_ignore": schema.StringAttribute{
				Description: "Comma-separated list of Local Users which should not be migrated (Relevant only for Server Inventory migration)",
				Optional: true,
			},
			"si_users_path_template": schema.StringAttribute{
				Description: "Path location template for migrating users as Rotated Secrets e.g.: .../Users/{{COMPUTER_NAME}}/{{USERNAME}} (Relevant only for Server Inventory migration)",
				Required: true,
			},
			"target_location": schema.StringAttribute{
				Description: "Target location in Akeyless for imported secrets",
				Required: true,
			},
			"type": schema.StringAttribute{
				Description: "Migration type (hashi/aws/gcp/k8s/azure_kv/conjur/active_directory/server_inventory/certificate)",
				Optional: true,
			},
			"use_gw_cloud_identity": schema.BoolAttribute{
				Description: "Use the GW's Cloud IAM",
				Optional: true,
			},
		},
	}
}

func (r *GatewayMigrationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *GatewayMigrationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewayMigrationModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/gateway-create-migration")

	// Set ServiceAccountKeyDecoded
	if !plan.ServiceAccountKeyDecoded.IsNull() && !plan.ServiceAccountKeyDecoded.IsUnknown() {
		v := plan.ServiceAccountKeyDecoded.ValueString()
		body.SetServiceAccountKeyDecoded(&v)
	}

	// Set ad_auto_rotate
	if !plan.AdAutoRotate.IsNull() && !plan.AdAutoRotate.IsUnknown() {
		v := plan.AdAutoRotate.ValueString()
		body.SetAdAutoRotate(&v)
	}

	// Set ad_cert_expiration_event_in
	if !plan.AdCertExpirationEventIn.IsNull() && !plan.AdCertExpirationEventIn.IsUnknown() {
		body.SetAdCertExpirationEventIn(expandStringSet(ctx, plan.AdCertExpirationEventIn))
	}

	// Set ad_certificates_path_template
	if !plan.AdCertificatesPathTemplate.IsNull() && !plan.AdCertificatesPathTemplate.IsUnknown() {
		v := plan.AdCertificatesPathTemplate.ValueString()
		body.SetAdCertificatesPathTemplate(&v)
	}

	// Set ad_computer_base_dn
	if !plan.AdComputerBaseDn.IsNull() && !plan.AdComputerBaseDn.IsUnknown() {
		v := plan.AdComputerBaseDn.ValueString()
		body.SetAdComputerBaseDn(&v)
	}

	// Set ad_discover_iis_app
	if !plan.AdDiscoverIisApp.IsNull() && !plan.AdDiscoverIisApp.IsUnknown() {
		v := plan.AdDiscoverIisApp.ValueString()
		body.SetAdDiscoverIisApp(&v)
	}

	// Set ad_discover_services
	if !plan.AdDiscoverServices.IsNull() && !plan.AdDiscoverServices.IsUnknown() {
		v := plan.AdDiscoverServices.ValueString()
		body.SetAdDiscoverServices(&v)
	}

	// Set ad_discovery_types
	if !plan.AdDiscoveryTypes.IsNull() && !plan.AdDiscoveryTypes.IsUnknown() {
		body.SetAdDiscoveryTypes(expandStringSet(ctx, plan.AdDiscoveryTypes))
	}

	// Set ad_domain_name
	if !plan.AdDomainName.IsNull() && !plan.AdDomainName.IsUnknown() {
		v := plan.AdDomainName.ValueString()
		body.SetAdDomainName(&v)
	}

	// Set ad_domain_users_path_template
	if !plan.AdDomainUsersPathTemplate.IsNull() && !plan.AdDomainUsersPathTemplate.IsUnknown() {
		v := plan.AdDomainUsersPathTemplate.ValueString()
		body.SetAdDomainUsersPathTemplate(&v)
	}

	// Set ad_local_users_ignore
	if !plan.AdLocalUsersIgnore.IsNull() && !plan.AdLocalUsersIgnore.IsUnknown() {
		v := plan.AdLocalUsersIgnore.ValueString()
		body.SetAdLocalUsersIgnore(&v)
	}

	// Set ad_local_users_path_template
	if !plan.AdLocalUsersPathTemplate.IsNull() && !plan.AdLocalUsersPathTemplate.IsUnknown() {
		v := plan.AdLocalUsersPathTemplate.ValueString()
		body.SetAdLocalUsersPathTemplate(&v)
	}

	// Set ad_os_filter
	if !plan.AdOsFilter.IsNull() && !plan.AdOsFilter.IsUnknown() {
		v := plan.AdOsFilter.ValueString()
		body.SetAdOsFilter(&v)
	}

	// Set ad_rotation_hour
	if !plan.AdRotationHour.IsNull() && !plan.AdRotationHour.IsUnknown() {
		v := plan.AdRotationHour.ValueInt64()
		body.SetAdRotationHour(&v)
	}

	// Set ad_rotation_interval
	if !plan.AdRotationInterval.IsNull() && !plan.AdRotationInterval.IsUnknown() {
		v := plan.AdRotationInterval.ValueInt64()
		body.SetAdRotationInterval(&v)
	}

	// Set ad_sra_enable_rdp
	if !plan.AdSraEnableRdp.IsNull() && !plan.AdSraEnableRdp.IsUnknown() {
		v := plan.AdSraEnableRdp.ValueString()
		body.SetAdSraEnableRdp(&v)
	}

	// Set ad_ssh_port
	if !plan.AdSshPort.IsNull() && !plan.AdSshPort.IsUnknown() {
		v := plan.AdSshPort.ValueString()
		body.SetAdSshPort(&v)
	}

	// Set ad_target_format
	if !plan.AdTargetFormat.IsNull() && !plan.AdTargetFormat.IsUnknown() {
		v := plan.AdTargetFormat.ValueString()
		body.SetAdTargetFormat(&v)
	}

	// Set ad_target_name
	if !plan.AdTargetName.IsNull() && !plan.AdTargetName.IsUnknown() {
		v := plan.AdTargetName.ValueString()
		body.SetAdTargetName(&v)
	}

	// Set ad_targets_path_template
	if !plan.AdTargetsPathTemplate.IsNull() && !plan.AdTargetsPathTemplate.IsUnknown() {
		v := plan.AdTargetsPathTemplate.ValueString()
		body.SetAdTargetsPathTemplate(&v)
	}

	// Set ad_targets_type
	if !plan.AdTargetsType.IsNull() && !plan.AdTargetsType.IsUnknown() {
		v := plan.AdTargetsType.ValueString()
		body.SetAdTargetsType(&v)
	}

	// Set ad_user_base_dn
	if !plan.AdUserBaseDn.IsNull() && !plan.AdUserBaseDn.IsUnknown() {
		v := plan.AdUserBaseDn.ValueString()
		body.SetAdUserBaseDn(&v)
	}

	// Set ad_user_groups
	if !plan.AdUserGroups.IsNull() && !plan.AdUserGroups.IsUnknown() {
		v := plan.AdUserGroups.ValueString()
		body.SetAdUserGroups(&v)
	}

	// Set ad_winrm_over_http
	if !plan.AdWinrmOverHttp.IsNull() && !plan.AdWinrmOverHttp.IsUnknown() {
		v := plan.AdWinrmOverHttp.ValueString()
		body.SetAdWinrmOverHttp(&v)
	}

	// Set ad_winrm_port
	if !plan.AdWinrmPort.IsNull() && !plan.AdWinrmPort.IsUnknown() {
		v := plan.AdWinrmPort.ValueString()
		body.SetAdWinrmPort(&v)
	}

	// Set ad_discover_local_users
	if !plan.AdDiscoverLocalUsers.IsNull() && !plan.AdDiscoverLocalUsers.IsUnknown() {
		v := plan.AdDiscoverLocalUsers.ValueString()
		body.SetAdDiscoverLocalUsers(&v)
	}

	// Set ai_certificate_discovery
	if !plan.AiCertificateDiscovery.IsNull() && !plan.AiCertificateDiscovery.IsUnknown() {
		v := plan.AiCertificateDiscovery.ValueString()
		body.SetAiCertificateDiscovery(&v)
	}

	// Set aws_key
	if !plan.AwsKey.IsNull() && !plan.AwsKey.IsUnknown() {
		v := plan.AwsKey.ValueString()
		body.SetAwsKey(&v)
	}

	// Set aws_key_id
	if !plan.AwsKeyId.IsNull() && !plan.AwsKeyId.IsUnknown() {
		v := plan.AwsKeyId.ValueString()
		body.SetAwsKeyId(&v)
	}

	// Set aws_region
	if !plan.AwsRegion.IsNull() && !plan.AwsRegion.IsUnknown() {
		v := plan.AwsRegion.ValueString()
		body.SetAwsRegion(&v)
	}

	// Set azure_client_id
	if !plan.AzureClientId.IsNull() && !plan.AzureClientId.IsUnknown() {
		v := plan.AzureClientId.ValueString()
		body.SetAzureClientId(&v)
	}

	// Set azure_kv_name
	if !plan.AzureKvName.IsNull() && !plan.AzureKvName.IsUnknown() {
		v := plan.AzureKvName.ValueString()
		body.SetAzureKvName(&v)
	}

	// Set azure_secret
	if !plan.AzureSecret.IsNull() && !plan.AzureSecret.IsUnknown() {
		v := plan.AzureSecret.ValueString()
		body.SetAzureSecret(&v)
	}

	// Set azure_tenant_id
	if !plan.AzureTenantId.IsNull() && !plan.AzureTenantId.IsUnknown() {
		v := plan.AzureTenantId.ValueString()
		body.SetAzureTenantId(&v)
	}

	// Set conjur_account
	if !plan.ConjurAccount.IsNull() && !plan.ConjurAccount.IsUnknown() {
		v := plan.ConjurAccount.ValueString()
		body.SetConjurAccount(&v)
	}

	// Set conjur_api_key
	if !plan.ConjurApiKey.IsNull() && !plan.ConjurApiKey.IsUnknown() {
		v := plan.ConjurApiKey.ValueString()
		body.SetConjurApiKey(&v)
	}

	// Set conjur_url
	if !plan.ConjurUrl.IsNull() && !plan.ConjurUrl.IsUnknown() {
		v := plan.ConjurUrl.ValueString()
		body.SetConjurUrl(&v)
	}

	// Set conjur_username
	if !plan.ConjurUsername.IsNull() && !plan.ConjurUsername.IsUnknown() {
		v := plan.ConjurUsername.ValueString()
		body.SetConjurUsername(&v)
	}

	// Set expiration_event_in
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}

	// Set gcp_key
	if !plan.GcpKey.IsNull() && !plan.GcpKey.IsUnknown() {
		v := plan.GcpKey.ValueString()
		body.SetGcpKey(&v)
	}

	// Set gcp_project_id
	if !plan.GcpProjectId.IsNull() && !plan.GcpProjectId.IsUnknown() {
		v := plan.GcpProjectId.ValueString()
		body.SetGcpProjectId(&v)
	}

	// Set hashi_json
	if !plan.HashiJson.IsNull() && !plan.HashiJson.IsUnknown() {
		v := plan.HashiJson.ValueString()
		body.SetHashiJson(&v)
	}

	// Set hashi_ns
	if !plan.HashiNs.IsNull() && !plan.HashiNs.IsUnknown() {
		body.SetHashiNs(expandStringSet(ctx, plan.HashiNs))
	}

	// Set hashi_token
	if !plan.HashiToken.IsNull() && !plan.HashiToken.IsUnknown() {
		v := plan.HashiToken.ValueString()
		body.SetHashiToken(&v)
	}

	// Set hashi_url
	if !plan.HashiUrl.IsNull() && !plan.HashiUrl.IsUnknown() {
		v := plan.HashiUrl.ValueString()
		body.SetHashiUrl(&v)
	}

	// Set hosts
	if !plan.Hosts.IsNull() && !plan.Hosts.IsUnknown() {
		v := plan.Hosts.ValueString()
		body.SetHosts(&v)
	}

	// Set k8s_ca_certificate
	if !plan.K8sCaCertificate.IsNull() && !plan.K8sCaCertificate.IsUnknown() {
		body.SetK8sCaCertificate(expandStringSet(ctx, plan.K8sCaCertificate))
	}

	// Set k8s_client_certificate
	if !plan.K8sClientCertificate.IsNull() && !plan.K8sClientCertificate.IsUnknown() {
		body.SetK8sClientCertificate(expandStringSet(ctx, plan.K8sClientCertificate))
	}

	// Set k8s_client_key
	if !plan.K8sClientKey.IsNull() && !plan.K8sClientKey.IsUnknown() {
		body.SetK8sClientKey(expandStringSet(ctx, plan.K8sClientKey))
	}

	// Set k8s_namespace
	if !plan.K8sNamespace.IsNull() && !plan.K8sNamespace.IsUnknown() {
		v := plan.K8sNamespace.ValueString()
		body.SetK8sNamespace(&v)
	}

	// Set k8s_password
	if !plan.K8sPassword.IsNull() && !plan.K8sPassword.IsUnknown() {
		v := plan.K8sPassword.ValueString()
		body.SetK8sPassword(&v)
	}

	// Set k8s_skip_system
	if !plan.K8sSkipSystem.IsNull() && !plan.K8sSkipSystem.IsUnknown() {
		v := plan.K8sSkipSystem.ValueBool()
		body.SetK8sSkipSystem(&v)
	}

	// Set k8s_token
	if !plan.K8sToken.IsNull() && !plan.K8sToken.IsUnknown() {
		v := plan.K8sToken.ValueString()
		body.SetK8sToken(&v)
	}

	// Set k8s_url
	if !plan.K8sUrl.IsNull() && !plan.K8sUrl.IsUnknown() {
		v := plan.K8sUrl.ValueString()
		body.SetK8sUrl(&v)
	}

	// Set k8s_username
	if !plan.K8sUsername.IsNull() && !plan.K8sUsername.IsUnknown() {
		v := plan.K8sUsername.ValueString()
		body.SetK8sUsername(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set port_ranges
	if !plan.PortRanges.IsNull() && !plan.PortRanges.IsUnknown() {
		v := plan.PortRanges.ValueString()
		body.SetPortRanges(&v)
	}

	// Set protection_key
	if !plan.ProtectionKey.IsNull() && !plan.ProtectionKey.IsUnknown() {
		v := plan.ProtectionKey.ValueString()
		body.SetProtectionKey(&v)
	}

	// Set si_auto_rotate
	if !plan.SiAutoRotate.IsNull() && !plan.SiAutoRotate.IsUnknown() {
		v := plan.SiAutoRotate.ValueString()
		body.SetSiAutoRotate(&v)
	}

	// Set si_rotation_hour
	if !plan.SiRotationHour.IsNull() && !plan.SiRotationHour.IsUnknown() {
		v := plan.SiRotationHour.ValueInt64()
		body.SetSiRotationHour(&v)
	}

	// Set si_rotation_interval
	if !plan.SiRotationInterval.IsNull() && !plan.SiRotationInterval.IsUnknown() {
		v := plan.SiRotationInterval.ValueInt64()
		body.SetSiRotationInterval(&v)
	}

	// Set si_sra_enable_rdp
	if !plan.SiSraEnableRdp.IsNull() && !plan.SiSraEnableRdp.IsUnknown() {
		v := plan.SiSraEnableRdp.ValueString()
		body.SetSiSraEnableRdp(&v)
	}

	// Set si_target_name
	if !plan.SiTargetName.IsNull() && !plan.SiTargetName.IsUnknown() {
		v := plan.SiTargetName.ValueString()
		body.SetSiTargetName(&v)
	}

	// Set si_user_groups
	if !plan.SiUserGroups.IsNull() && !plan.SiUserGroups.IsUnknown() {
		v := plan.SiUserGroups.ValueString()
		body.SetSiUserGroups(&v)
	}

	// Set si_users_ignore
	if !plan.SiUsersIgnore.IsNull() && !plan.SiUsersIgnore.IsUnknown() {
		v := plan.SiUsersIgnore.ValueString()
		body.SetSiUsersIgnore(&v)
	}

	// Set si_users_path_template
	if !plan.SiUsersPathTemplate.IsNull() && !plan.SiUsersPathTemplate.IsUnknown() {
		v := plan.SiUsersPathTemplate.ValueString()
		body.SetSiUsersPathTemplate(&v)
	}

	// Set target_location
	if !plan.TargetLocation.IsNull() && !plan.TargetLocation.IsUnknown() {
		v := plan.TargetLocation.ValueString()
		body.SetTargetLocation(&v)
	}

	// Set type
	if !plan.Type.IsNull() && !plan.Type.IsUnknown() {
		v := plan.Type.ValueString()
		body.SetType(&v)
	}

	// Set use_gw_cloud_identity
	if !plan.UseGwCloudIdentity.IsNull() && !plan.UseGwCloudIdentity.IsUnknown() {
		v := plan.UseGwCloudIdentity.ValueBool()
		body.SetUseGwCloudIdentity(&v)
	}

	tflog.Debug(ctx, "Creating GatewayMigration")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating GatewayMigration", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *GatewayMigrationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewayMigrationModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *GatewayMigrationResource) readResource(ctx context.Context, id string) (GatewayMigrationModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state GatewayMigrationModel

	body := akeyless_api.NewReadBody("/gateway-get-migration")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading GatewayMigration", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	// TODO: state.ServiceAccountKeyDecoded = ... // no read_mapping defined
	// TODO: state.AdAutoRotate = ... // no read_mapping defined
	// TODO: state.AdCertExpirationEventIn = ... // no read_mapping defined
	// TODO: state.AdCertificatesPathTemplate = ... // no read_mapping defined
	// TODO: state.AdComputerBaseDn = ... // no read_mapping defined
	// TODO: state.AdDiscoverIisApp = ... // no read_mapping defined
	// TODO: state.AdDiscoverServices = ... // no read_mapping defined
	// TODO: state.AdDiscoveryTypes = ... // no read_mapping defined
	// TODO: state.AdDomainName = ... // no read_mapping defined
	// TODO: state.AdDomainUsersPathTemplate = ... // no read_mapping defined
	// TODO: state.AdLocalUsersIgnore = ... // no read_mapping defined
	// TODO: state.AdLocalUsersPathTemplate = ... // no read_mapping defined
	// TODO: state.AdOsFilter = ... // no read_mapping defined
	// TODO: state.AdRotationHour = ... // no read_mapping defined
	// TODO: state.AdRotationInterval = ... // no read_mapping defined
	// TODO: state.AdSraEnableRdp = ... // no read_mapping defined
	// TODO: state.AdSshPort = ... // no read_mapping defined
	// TODO: state.AdTargetFormat = ... // no read_mapping defined
	// TODO: state.AdTargetName = ... // no read_mapping defined
	// TODO: state.AdTargetsPathTemplate = ... // no read_mapping defined
	// TODO: state.AdTargetsType = ... // no read_mapping defined
	// TODO: state.AdUserBaseDn = ... // no read_mapping defined
	// TODO: state.AdUserGroups = ... // no read_mapping defined
	// TODO: state.AdWinrmOverHttp = ... // no read_mapping defined
	// TODO: state.AdWinrmPort = ... // no read_mapping defined
	// TODO: state.AdDiscoverLocalUsers = ... // no read_mapping defined
	// TODO: state.AiCertificateDiscovery = ... // no read_mapping defined
	// TODO: state.AwsKey = ... // no read_mapping defined
	// TODO: state.AwsKeyId = ... // no read_mapping defined
	// TODO: state.AwsRegion = ... // no read_mapping defined
	// TODO: state.AzureClientId = ... // no read_mapping defined
	// TODO: state.AzureKvName = ... // no read_mapping defined
	// TODO: state.AzureSecret = ... // no read_mapping defined
	// TODO: state.AzureTenantId = ... // no read_mapping defined
	// TODO: state.ConjurAccount = ... // no read_mapping defined
	// TODO: state.ConjurApiKey = ... // no read_mapping defined
	// TODO: state.ConjurUrl = ... // no read_mapping defined
	// TODO: state.ConjurUsername = ... // no read_mapping defined
	// TODO: state.ExpirationEventIn = ... // no read_mapping defined
	// TODO: state.GcpKey = ... // no read_mapping defined
	// TODO: state.GcpProjectId = ... // no read_mapping defined
	// TODO: state.HashiJson = ... // no read_mapping defined
	// TODO: state.HashiNs = ... // no read_mapping defined
	// TODO: state.HashiToken = ... // no read_mapping defined
	// TODO: state.HashiUrl = ... // no read_mapping defined
	// TODO: state.Hosts = ... // no read_mapping defined
	// TODO: state.K8sCaCertificate = ... // no read_mapping defined
	// TODO: state.K8sClientCertificate = ... // no read_mapping defined
	// TODO: state.K8sClientKey = ... // no read_mapping defined
	// TODO: state.K8sNamespace = ... // no read_mapping defined
	// TODO: state.K8sPassword = ... // no read_mapping defined
	// TODO: state.K8sSkipSystem = ... // no read_mapping defined
	// TODO: state.K8sToken = ... // no read_mapping defined
	// TODO: state.K8sUrl = ... // no read_mapping defined
	// TODO: state.K8sUsername = ... // no read_mapping defined
	// TODO: state.Name = ... // no read_mapping defined
	// TODO: state.PortRanges = ... // no read_mapping defined
	// TODO: state.ProtectionKey = ... // no read_mapping defined
	// TODO: state.SiAutoRotate = ... // no read_mapping defined
	// TODO: state.SiRotationHour = ... // no read_mapping defined
	// TODO: state.SiRotationInterval = ... // no read_mapping defined
	// TODO: state.SiSraEnableRdp = ... // no read_mapping defined
	// TODO: state.SiTargetName = ... // no read_mapping defined
	// TODO: state.SiUserGroups = ... // no read_mapping defined
	// TODO: state.SiUsersIgnore = ... // no read_mapping defined
	// TODO: state.SiUsersPathTemplate = ... // no read_mapping defined
	// TODO: state.TargetLocation = ... // no read_mapping defined
	// TODO: state.Type = ... // no read_mapping defined
	// TODO: state.UseGwCloudIdentity = ... // no read_mapping defined
	_ = result

	return state, diags
}

func (r *GatewayMigrationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewayMigrationModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/gateway-update-migration")
	if !plan.ServiceAccountKeyDecoded.IsNull() && !plan.ServiceAccountKeyDecoded.IsUnknown() {
		v := plan.ServiceAccountKeyDecoded.ValueString()
		body.SetServiceAccountKeyDecoded(&v)
	}
	if !plan.AdAutoRotate.IsNull() && !plan.AdAutoRotate.IsUnknown() {
		v := plan.AdAutoRotate.ValueString()
		body.SetAdAutoRotate(&v)
	}
	if !plan.AdCertExpirationEventIn.IsNull() && !plan.AdCertExpirationEventIn.IsUnknown() {
		body.SetAdCertExpirationEventIn(expandStringSet(ctx, plan.AdCertExpirationEventIn))
	}
	if !plan.AdCertificatesPathTemplate.IsNull() && !plan.AdCertificatesPathTemplate.IsUnknown() {
		v := plan.AdCertificatesPathTemplate.ValueString()
		body.SetAdCertificatesPathTemplate(&v)
	}
	if !plan.AdComputerBaseDn.IsNull() && !plan.AdComputerBaseDn.IsUnknown() {
		v := plan.AdComputerBaseDn.ValueString()
		body.SetAdComputerBaseDn(&v)
	}
	if !plan.AdDiscoverIisApp.IsNull() && !plan.AdDiscoverIisApp.IsUnknown() {
		v := plan.AdDiscoverIisApp.ValueString()
		body.SetAdDiscoverIisApp(&v)
	}
	if !plan.AdDiscoverServices.IsNull() && !plan.AdDiscoverServices.IsUnknown() {
		v := plan.AdDiscoverServices.ValueString()
		body.SetAdDiscoverServices(&v)
	}
	if !plan.AdDiscoveryTypes.IsNull() && !plan.AdDiscoveryTypes.IsUnknown() {
		body.SetAdDiscoveryTypes(expandStringSet(ctx, plan.AdDiscoveryTypes))
	}
	if !plan.AdDomainName.IsNull() && !plan.AdDomainName.IsUnknown() {
		v := plan.AdDomainName.ValueString()
		body.SetAdDomainName(&v)
	}
	if !plan.AdDomainUsersPathTemplate.IsNull() && !plan.AdDomainUsersPathTemplate.IsUnknown() {
		v := plan.AdDomainUsersPathTemplate.ValueString()
		body.SetAdDomainUsersPathTemplate(&v)
	}
	if !plan.AdLocalUsersIgnore.IsNull() && !plan.AdLocalUsersIgnore.IsUnknown() {
		v := plan.AdLocalUsersIgnore.ValueString()
		body.SetAdLocalUsersIgnore(&v)
	}
	if !plan.AdLocalUsersPathTemplate.IsNull() && !plan.AdLocalUsersPathTemplate.IsUnknown() {
		v := plan.AdLocalUsersPathTemplate.ValueString()
		body.SetAdLocalUsersPathTemplate(&v)
	}
	if !plan.AdOsFilter.IsNull() && !plan.AdOsFilter.IsUnknown() {
		v := plan.AdOsFilter.ValueString()
		body.SetAdOsFilter(&v)
	}
	if !plan.AdRotationHour.IsNull() && !plan.AdRotationHour.IsUnknown() {
		v := plan.AdRotationHour.ValueInt64()
		body.SetAdRotationHour(&v)
	}
	if !plan.AdRotationInterval.IsNull() && !plan.AdRotationInterval.IsUnknown() {
		v := plan.AdRotationInterval.ValueInt64()
		body.SetAdRotationInterval(&v)
	}
	if !plan.AdSraEnableRdp.IsNull() && !plan.AdSraEnableRdp.IsUnknown() {
		v := plan.AdSraEnableRdp.ValueString()
		body.SetAdSraEnableRdp(&v)
	}
	if !plan.AdSshPort.IsNull() && !plan.AdSshPort.IsUnknown() {
		v := plan.AdSshPort.ValueString()
		body.SetAdSshPort(&v)
	}
	if !plan.AdTargetFormat.IsNull() && !plan.AdTargetFormat.IsUnknown() {
		v := plan.AdTargetFormat.ValueString()
		body.SetAdTargetFormat(&v)
	}
	if !plan.AdTargetName.IsNull() && !plan.AdTargetName.IsUnknown() {
		v := plan.AdTargetName.ValueString()
		body.SetAdTargetName(&v)
	}
	if !plan.AdTargetsPathTemplate.IsNull() && !plan.AdTargetsPathTemplate.IsUnknown() {
		v := plan.AdTargetsPathTemplate.ValueString()
		body.SetAdTargetsPathTemplate(&v)
	}
	if !plan.AdTargetsType.IsNull() && !plan.AdTargetsType.IsUnknown() {
		v := plan.AdTargetsType.ValueString()
		body.SetAdTargetsType(&v)
	}
	if !plan.AdUserBaseDn.IsNull() && !plan.AdUserBaseDn.IsUnknown() {
		v := plan.AdUserBaseDn.ValueString()
		body.SetAdUserBaseDn(&v)
	}
	if !plan.AdUserGroups.IsNull() && !plan.AdUserGroups.IsUnknown() {
		v := plan.AdUserGroups.ValueString()
		body.SetAdUserGroups(&v)
	}
	if !plan.AdWinrmOverHttp.IsNull() && !plan.AdWinrmOverHttp.IsUnknown() {
		v := plan.AdWinrmOverHttp.ValueString()
		body.SetAdWinrmOverHttp(&v)
	}
	if !plan.AdWinrmPort.IsNull() && !plan.AdWinrmPort.IsUnknown() {
		v := plan.AdWinrmPort.ValueString()
		body.SetAdWinrmPort(&v)
	}
	if !plan.AdDiscoverLocalUsers.IsNull() && !plan.AdDiscoverLocalUsers.IsUnknown() {
		v := plan.AdDiscoverLocalUsers.ValueString()
		body.SetAdDiscoverLocalUsers(&v)
	}
	if !plan.AiCertificateDiscovery.IsNull() && !plan.AiCertificateDiscovery.IsUnknown() {
		v := plan.AiCertificateDiscovery.ValueString()
		body.SetAiCertificateDiscovery(&v)
	}
	if !plan.AwsKey.IsNull() && !plan.AwsKey.IsUnknown() {
		v := plan.AwsKey.ValueString()
		body.SetAwsKey(&v)
	}
	if !plan.AwsKeyId.IsNull() && !plan.AwsKeyId.IsUnknown() {
		v := plan.AwsKeyId.ValueString()
		body.SetAwsKeyId(&v)
	}
	if !plan.AwsRegion.IsNull() && !plan.AwsRegion.IsUnknown() {
		v := plan.AwsRegion.ValueString()
		body.SetAwsRegion(&v)
	}
	if !plan.AzureClientId.IsNull() && !plan.AzureClientId.IsUnknown() {
		v := plan.AzureClientId.ValueString()
		body.SetAzureClientId(&v)
	}
	if !plan.AzureKvName.IsNull() && !plan.AzureKvName.IsUnknown() {
		v := plan.AzureKvName.ValueString()
		body.SetAzureKvName(&v)
	}
	if !plan.AzureSecret.IsNull() && !plan.AzureSecret.IsUnknown() {
		v := plan.AzureSecret.ValueString()
		body.SetAzureSecret(&v)
	}
	if !plan.AzureTenantId.IsNull() && !plan.AzureTenantId.IsUnknown() {
		v := plan.AzureTenantId.ValueString()
		body.SetAzureTenantId(&v)
	}
	if !plan.ConjurAccount.IsNull() && !plan.ConjurAccount.IsUnknown() {
		v := plan.ConjurAccount.ValueString()
		body.SetConjurAccount(&v)
	}
	if !plan.ConjurApiKey.IsNull() && !plan.ConjurApiKey.IsUnknown() {
		v := plan.ConjurApiKey.ValueString()
		body.SetConjurApiKey(&v)
	}
	if !plan.ConjurUrl.IsNull() && !plan.ConjurUrl.IsUnknown() {
		v := plan.ConjurUrl.ValueString()
		body.SetConjurUrl(&v)
	}
	if !plan.ConjurUsername.IsNull() && !plan.ConjurUsername.IsUnknown() {
		v := plan.ConjurUsername.ValueString()
		body.SetConjurUsername(&v)
	}
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}
	if !plan.GcpKey.IsNull() && !plan.GcpKey.IsUnknown() {
		v := plan.GcpKey.ValueString()
		body.SetGcpKey(&v)
	}
	if !plan.GcpProjectId.IsNull() && !plan.GcpProjectId.IsUnknown() {
		v := plan.GcpProjectId.ValueString()
		body.SetGcpProjectId(&v)
	}
	if !plan.HashiJson.IsNull() && !plan.HashiJson.IsUnknown() {
		v := plan.HashiJson.ValueString()
		body.SetHashiJson(&v)
	}
	if !plan.HashiNs.IsNull() && !plan.HashiNs.IsUnknown() {
		body.SetHashiNs(expandStringSet(ctx, plan.HashiNs))
	}
	if !plan.HashiToken.IsNull() && !plan.HashiToken.IsUnknown() {
		v := plan.HashiToken.ValueString()
		body.SetHashiToken(&v)
	}
	if !plan.HashiUrl.IsNull() && !plan.HashiUrl.IsUnknown() {
		v := plan.HashiUrl.ValueString()
		body.SetHashiUrl(&v)
	}
	if !plan.Hosts.IsNull() && !plan.Hosts.IsUnknown() {
		v := plan.Hosts.ValueString()
		body.SetHosts(&v)
	}
	if !plan.K8sCaCertificate.IsNull() && !plan.K8sCaCertificate.IsUnknown() {
		body.SetK8sCaCertificate(expandStringSet(ctx, plan.K8sCaCertificate))
	}
	if !plan.K8sClientCertificate.IsNull() && !plan.K8sClientCertificate.IsUnknown() {
		body.SetK8sClientCertificate(expandStringSet(ctx, plan.K8sClientCertificate))
	}
	if !plan.K8sClientKey.IsNull() && !plan.K8sClientKey.IsUnknown() {
		body.SetK8sClientKey(expandStringSet(ctx, plan.K8sClientKey))
	}
	if !plan.K8sNamespace.IsNull() && !plan.K8sNamespace.IsUnknown() {
		v := plan.K8sNamespace.ValueString()
		body.SetK8sNamespace(&v)
	}
	if !plan.K8sPassword.IsNull() && !plan.K8sPassword.IsUnknown() {
		v := plan.K8sPassword.ValueString()
		body.SetK8sPassword(&v)
	}
	if !plan.K8sSkipSystem.IsNull() && !plan.K8sSkipSystem.IsUnknown() {
		v := plan.K8sSkipSystem.ValueBool()
		body.SetK8sSkipSystem(&v)
	}
	if !plan.K8sToken.IsNull() && !plan.K8sToken.IsUnknown() {
		v := plan.K8sToken.ValueString()
		body.SetK8sToken(&v)
	}
	if !plan.K8sUrl.IsNull() && !plan.K8sUrl.IsUnknown() {
		v := plan.K8sUrl.ValueString()
		body.SetK8sUrl(&v)
	}
	if !plan.K8sUsername.IsNull() && !plan.K8sUsername.IsUnknown() {
		v := plan.K8sUsername.ValueString()
		body.SetK8sUsername(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PortRanges.IsNull() && !plan.PortRanges.IsUnknown() {
		v := plan.PortRanges.ValueString()
		body.SetPortRanges(&v)
	}
	if !plan.ProtectionKey.IsNull() && !plan.ProtectionKey.IsUnknown() {
		v := plan.ProtectionKey.ValueString()
		body.SetProtectionKey(&v)
	}
	if !plan.SiAutoRotate.IsNull() && !plan.SiAutoRotate.IsUnknown() {
		v := plan.SiAutoRotate.ValueString()
		body.SetSiAutoRotate(&v)
	}
	if !plan.SiRotationHour.IsNull() && !plan.SiRotationHour.IsUnknown() {
		v := plan.SiRotationHour.ValueInt64()
		body.SetSiRotationHour(&v)
	}
	if !plan.SiRotationInterval.IsNull() && !plan.SiRotationInterval.IsUnknown() {
		v := plan.SiRotationInterval.ValueInt64()
		body.SetSiRotationInterval(&v)
	}
	if !plan.SiSraEnableRdp.IsNull() && !plan.SiSraEnableRdp.IsUnknown() {
		v := plan.SiSraEnableRdp.ValueString()
		body.SetSiSraEnableRdp(&v)
	}
	if !plan.SiTargetName.IsNull() && !plan.SiTargetName.IsUnknown() {
		v := plan.SiTargetName.ValueString()
		body.SetSiTargetName(&v)
	}
	if !plan.SiUserGroups.IsNull() && !plan.SiUserGroups.IsUnknown() {
		v := plan.SiUserGroups.ValueString()
		body.SetSiUserGroups(&v)
	}
	if !plan.SiUsersIgnore.IsNull() && !plan.SiUsersIgnore.IsUnknown() {
		v := plan.SiUsersIgnore.ValueString()
		body.SetSiUsersIgnore(&v)
	}
	if !plan.SiUsersPathTemplate.IsNull() && !plan.SiUsersPathTemplate.IsUnknown() {
		v := plan.SiUsersPathTemplate.ValueString()
		body.SetSiUsersPathTemplate(&v)
	}
	if !plan.TargetLocation.IsNull() && !plan.TargetLocation.IsUnknown() {
		v := plan.TargetLocation.ValueString()
		body.SetTargetLocation(&v)
	}
	if !plan.Type.IsNull() && !plan.Type.IsUnknown() {
		v := plan.Type.ValueString()
		body.SetType(&v)
	}
	if !plan.UseGwCloudIdentity.IsNull() && !plan.UseGwCloudIdentity.IsUnknown() {
		v := plan.UseGwCloudIdentity.ValueBool()
		body.SetUseGwCloudIdentity(&v)
	}

	tflog.Debug(ctx, "Updating GatewayMigration")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating GatewayMigration", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *GatewayMigrationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewayMigrationModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/gateway-delete-migration")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting GatewayMigration", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting GatewayMigration", err.Error())
		return
	}
}

func (r *GatewayMigrationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
