// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetSectigoResource{}
	_ resource.ResourceWithConfigure   = &TargetSectigoResource{}
	_ resource.ResourceWithImportState = &TargetSectigoResource{}
)

type TargetSectigoResource struct {
	client *AkeylessClient
}

func NewTargetSectigoResource() resource.Resource {
	return &TargetSectigoResource{}
}

type TargetSectigoModel struct {
	CertificateProfileId types.Int64 `tfsdk:"certificate_profile_id"`
	CustomerUri types.String `tfsdk:"customer_uri"`
	Description types.String `tfsdk:"description"`
	ExternalRequester types.String `tfsdk:"external_requester"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	OrganizationId types.Int64 `tfsdk:"organization_id"`
	Timeout types.String `tfsdk:"timeout"`
}

func (r *TargetSectigoResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_sectigo"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"certificate_profile_id": schema.Int64Attribute{
				Description: "Certificate Profile ID in Sectigo account",
				Required: true,
			},
			"customer_uri": schema.StringAttribute{
				Description: "Customer Uri of the Sectigo account",
				Required: true,
			},
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"external_requester": schema.StringAttribute{
				Description: "External Requester - a comma separated list of emails",
				Required: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"organization_id": schema.Int64Attribute{
				Description: "Organization ID in Sectigo account",
				Required: true,
			},
			"timeout": schema.StringAttribute{
				Description: "Timeout waiting for certificate validation in Duration format (1h - 1 Hour, 20m - 20 Minutes, 33m3s - 33 Minutes and 3 Seconds), maximum 1h.",
				Optional: true,
			},
		},
	}
}

func (r *TargetSectigoResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetSectigoResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetSectigoModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-sectigo")

	// Set certificate_profile_id
	if !plan.CertificateProfileId.IsNull() && !plan.CertificateProfileId.IsUnknown() {
		v := plan.CertificateProfileId.ValueInt64()
		body.SetCertificateProfileId(&v)
	}

	// Set customer_uri
	if !plan.CustomerUri.IsNull() && !plan.CustomerUri.IsUnknown() {
		v := plan.CustomerUri.ValueString()
		body.SetCustomerUri(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set external_requester
	if !plan.ExternalRequester.IsNull() && !plan.ExternalRequester.IsUnknown() {
		v := plan.ExternalRequester.ValueString()
		body.SetExternalRequester(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set organization_id
	if !plan.OrganizationId.IsNull() && !plan.OrganizationId.IsUnknown() {
		v := plan.OrganizationId.ValueInt64()
		body.SetOrganizationId(&v)
	}

	// Set timeout
	if !plan.Timeout.IsNull() && !plan.Timeout.IsUnknown() {
		v := plan.Timeout.ValueString()
		body.SetTimeout(&v)
	}

	tflog.Debug(ctx, "Creating TargetSectigo")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetSectigo", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetSectigoResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetSectigoModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetSectigoResource) readResource(ctx context.Context, id string) (TargetSectigoModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetSectigoModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetSectigo", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetSectigoResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetSectigoModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-sectigo")
	if !plan.CertificateProfileId.IsNull() && !plan.CertificateProfileId.IsUnknown() {
		v := plan.CertificateProfileId.ValueInt64()
		body.SetCertificateProfileId(&v)
	}
	if !plan.CustomerUri.IsNull() && !plan.CustomerUri.IsUnknown() {
		v := plan.CustomerUri.ValueString()
		body.SetCustomerUri(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ExternalRequester.IsNull() && !plan.ExternalRequester.IsUnknown() {
		v := plan.ExternalRequester.ValueString()
		body.SetExternalRequester(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.OrganizationId.IsNull() && !plan.OrganizationId.IsUnknown() {
		v := plan.OrganizationId.ValueInt64()
		body.SetOrganizationId(&v)
	}
	if !plan.Timeout.IsNull() && !plan.Timeout.IsUnknown() {
		v := plan.Timeout.ValueString()
		body.SetTimeout(&v)
	}

	tflog.Debug(ctx, "Updating TargetSectigo")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetSectigo", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetSectigoResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetSectigoModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetSectigo", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetSectigo", err.Error())
		return
	}
}

func (r *TargetSectigoResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
