// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretEksResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretEksResource{}
	_ resource.ResourceWithImportState = &DynamicSecretEksResource{}
)

type DynamicSecretEksResource struct {
	client *AkeylessClient
}

func NewDynamicSecretEksResource() resource.Resource {
	return &DynamicSecretEksResource{}
}

type DynamicSecretEksModel struct {
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	EksAccessKeyId types.String `tfsdk:"eks_access_key_id"`
	EksAssumeRole types.String `tfsdk:"eks_assume_role"`
	EksClusterCaCert types.String `tfsdk:"eks_cluster_ca_cert"`
	EksClusterEndpoint types.String `tfsdk:"eks_cluster_endpoint"`
	EksClusterName types.String `tfsdk:"eks_cluster_name"`
	EksRegion types.String `tfsdk:"eks_region"`
	EksSecretAccessKey types.String `tfsdk:"eks_secret_access_key"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	ProducerEncryptionKeyName types.String `tfsdk:"producer_encryption_key_name"`
	SecureAccessAllowPortForwading types.Bool `tfsdk:"secure_access_allow_port_forwading"`
	SecureAccessClusterEndpoint types.String `tfsdk:"secure_access_cluster_endpoint"`
	SecureAccessDelay types.Int64 `tfsdk:"secure_access_delay"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretEksResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_eks"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"eks_access_key_id": schema.StringAttribute{
				Description: "AWS access key ID for EKS",
				Optional: true,
				Sensitive: true,
			},
			"eks_assume_role": schema.StringAttribute{
				Description: "AWS role ARN to assume for EKS",
				Optional: true,
			},
			"eks_cluster_ca_cert": schema.StringAttribute{
				Description: "EKS cluster CA certificate (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"eks_cluster_endpoint": schema.StringAttribute{
				Description: "EKS cluster API server URL",
				Optional: true,
			},
			"eks_cluster_name": schema.StringAttribute{
				Description: "EKS cluster name",
				Optional: true,
			},
			"eks_region": schema.StringAttribute{
				Description: "AWS region for EKS cluster",
				Optional: true,
			},
			"eks_secret_access_key": schema.StringAttribute{
				Description: "AWS secret access key for EKS",
				Optional: true,
				Sensitive: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"producer_encryption_key_name": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"secure_access_allow_port_forwading": schema.BoolAttribute{
				Description: "Enable Port forwarding while using CLI access",
				Optional: true,
			},
			"secure_access_cluster_endpoint": schema.StringAttribute{
				Description: "The K8s cluster endpoint URL",
				Optional: true,
			},
			"secure_access_delay": schema.Int64Attribute{
				Description: "The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretEksResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretEksResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretEksModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-eks")

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set eks_access_key_id
	if !plan.EksAccessKeyId.IsNull() && !plan.EksAccessKeyId.IsUnknown() {
		v := plan.EksAccessKeyId.ValueString()
		body.SetEksAccessKeyId(&v)
	}

	// Set eks_assume_role
	if !plan.EksAssumeRole.IsNull() && !plan.EksAssumeRole.IsUnknown() {
		v := plan.EksAssumeRole.ValueString()
		body.SetEksAssumeRole(&v)
	}

	// Set eks_cluster_ca_cert
	if !plan.EksClusterCaCert.IsNull() && !plan.EksClusterCaCert.IsUnknown() {
		v := plan.EksClusterCaCert.ValueString()
		body.SetEksClusterCaCert(&v)
	}

	// Set eks_cluster_endpoint
	if !plan.EksClusterEndpoint.IsNull() && !plan.EksClusterEndpoint.IsUnknown() {
		v := plan.EksClusterEndpoint.ValueString()
		body.SetEksClusterEndpoint(&v)
	}

	// Set eks_cluster_name
	if !plan.EksClusterName.IsNull() && !plan.EksClusterName.IsUnknown() {
		v := plan.EksClusterName.ValueString()
		body.SetEksClusterName(&v)
	}

	// Set eks_region
	if !plan.EksRegion.IsNull() && !plan.EksRegion.IsUnknown() {
		v := plan.EksRegion.ValueString()
		body.SetEksRegion(&v)
	}

	// Set eks_secret_access_key
	if !plan.EksSecretAccessKey.IsNull() && !plan.EksSecretAccessKey.IsUnknown() {
		v := plan.EksSecretAccessKey.ValueString()
		body.SetEksSecretAccessKey(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set producer_encryption_key_name
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}

	// Set secure_access_allow_port_forwading
	if !plan.SecureAccessAllowPortForwading.IsNull() && !plan.SecureAccessAllowPortForwading.IsUnknown() {
		v := plan.SecureAccessAllowPortForwading.ValueBool()
		body.SetSecureAccessAllowPortForwading(&v)
	}

	// Set secure_access_cluster_endpoint
	if !plan.SecureAccessClusterEndpoint.IsNull() && !plan.SecureAccessClusterEndpoint.IsUnknown() {
		v := plan.SecureAccessClusterEndpoint.ValueString()
		body.SetSecureAccessClusterEndpoint(&v)
	}

	// Set secure_access_delay
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretEks")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretEks", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretEksResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretEksModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretEksResource) readResource(ctx context.Context, id string) (DynamicSecretEksModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretEksModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretEks", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretEksResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretEksModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-eks")
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.EksAccessKeyId.IsNull() && !plan.EksAccessKeyId.IsUnknown() {
		v := plan.EksAccessKeyId.ValueString()
		body.SetEksAccessKeyId(&v)
	}
	if !plan.EksAssumeRole.IsNull() && !plan.EksAssumeRole.IsUnknown() {
		v := plan.EksAssumeRole.ValueString()
		body.SetEksAssumeRole(&v)
	}
	if !plan.EksClusterCaCert.IsNull() && !plan.EksClusterCaCert.IsUnknown() {
		v := plan.EksClusterCaCert.ValueString()
		body.SetEksClusterCaCert(&v)
	}
	if !plan.EksClusterEndpoint.IsNull() && !plan.EksClusterEndpoint.IsUnknown() {
		v := plan.EksClusterEndpoint.ValueString()
		body.SetEksClusterEndpoint(&v)
	}
	if !plan.EksClusterName.IsNull() && !plan.EksClusterName.IsUnknown() {
		v := plan.EksClusterName.ValueString()
		body.SetEksClusterName(&v)
	}
	if !plan.EksRegion.IsNull() && !plan.EksRegion.IsUnknown() {
		v := plan.EksRegion.ValueString()
		body.SetEksRegion(&v)
	}
	if !plan.EksSecretAccessKey.IsNull() && !plan.EksSecretAccessKey.IsUnknown() {
		v := plan.EksSecretAccessKey.ValueString()
		body.SetEksSecretAccessKey(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}
	if !plan.SecureAccessAllowPortForwading.IsNull() && !plan.SecureAccessAllowPortForwading.IsUnknown() {
		v := plan.SecureAccessAllowPortForwading.ValueBool()
		body.SetSecureAccessAllowPortForwading(&v)
	}
	if !plan.SecureAccessClusterEndpoint.IsNull() && !plan.SecureAccessClusterEndpoint.IsUnknown() {
		v := plan.SecureAccessClusterEndpoint.ValueString()
		body.SetSecureAccessClusterEndpoint(&v)
	}
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretEks")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretEks", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretEksResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretEksModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretEks", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretEks", err.Error())
		return
	}
}

func (r *DynamicSecretEksResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
