// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretRedshiftResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretRedshiftResource{}
	_ resource.ResourceWithImportState = &DynamicSecretRedshiftResource{}
)

type DynamicSecretRedshiftResource struct {
	client *AkeylessClient
}

func NewDynamicSecretRedshiftResource() resource.Resource {
	return &DynamicSecretRedshiftResource{}
}

type DynamicSecretRedshiftModel struct {
	CreationStatements types.String `tfsdk:"creation_statements"`
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	Name types.String `tfsdk:"name"`
	PasswordLength types.String `tfsdk:"password_length"`
	ProducerEncryptionKey types.String `tfsdk:"producer_encryption_key"`
	RedshiftDbName types.String `tfsdk:"redshift_db_name"`
	RedshiftHost types.String `tfsdk:"redshift_host"`
	RedshiftPassword types.String `tfsdk:"redshift_password"`
	RedshiftPort types.String `tfsdk:"redshift_port"`
	RedshiftUsername types.String `tfsdk:"redshift_username"`
	Ssl types.Bool `tfsdk:"ssl"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretRedshiftResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_redshift"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"creation_statements": schema.StringAttribute{
				Description: "Redshift creation statements",
				Optional: true,
			},
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"password_length": schema.StringAttribute{
				Description: "The length of the password to be generated",
				Optional: true,
			},
			"producer_encryption_key": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"redshift_db_name": schema.StringAttribute{
				Description: "Redshift DB Name",
				Optional: true,
			},
			"redshift_host": schema.StringAttribute{
				Description: "Redshift host",
				Optional: true,
			},
			"redshift_password": schema.StringAttribute{
				Description: "Redshift admin password",
				Optional: true,
				Sensitive: true,
			},
			"redshift_port": schema.StringAttribute{
				Description: "Redshift port (default: 5439)",
				Optional: true,
			},
			"redshift_username": schema.StringAttribute{
				Description: "Redshift admin username",
				Optional: true,
			},
			"ssl": schema.BoolAttribute{
				Description: "Enable SSL connection",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretRedshiftResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretRedshiftResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretRedshiftModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-redshift")

	// Set creation_statements
	if !plan.CreationStatements.IsNull() && !plan.CreationStatements.IsUnknown() {
		v := plan.CreationStatements.ValueString()
		body.SetCreationStatements(&v)
	}

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set password_length
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}

	// Set producer_encryption_key
	if !plan.ProducerEncryptionKey.IsNull() && !plan.ProducerEncryptionKey.IsUnknown() {
		v := plan.ProducerEncryptionKey.ValueString()
		body.SetProducerEncryptionKey(&v)
	}

	// Set redshift_db_name
	if !plan.RedshiftDbName.IsNull() && !plan.RedshiftDbName.IsUnknown() {
		v := plan.RedshiftDbName.ValueString()
		body.SetRedshiftDbName(&v)
	}

	// Set redshift_host
	if !plan.RedshiftHost.IsNull() && !plan.RedshiftHost.IsUnknown() {
		v := plan.RedshiftHost.ValueString()
		body.SetRedshiftHost(&v)
	}

	// Set redshift_password
	if !plan.RedshiftPassword.IsNull() && !plan.RedshiftPassword.IsUnknown() {
		v := plan.RedshiftPassword.ValueString()
		body.SetRedshiftPassword(&v)
	}

	// Set redshift_port
	if !plan.RedshiftPort.IsNull() && !plan.RedshiftPort.IsUnknown() {
		v := plan.RedshiftPort.ValueString()
		body.SetRedshiftPort(&v)
	}

	// Set redshift_username
	if !plan.RedshiftUsername.IsNull() && !plan.RedshiftUsername.IsUnknown() {
		v := plan.RedshiftUsername.ValueString()
		body.SetRedshiftUsername(&v)
	}

	// Set ssl
	if !plan.Ssl.IsNull() && !plan.Ssl.IsUnknown() {
		v := plan.Ssl.ValueBool()
		body.SetSsl(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretRedshift")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretRedshift", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretRedshiftResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretRedshiftModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretRedshiftResource) readResource(ctx context.Context, id string) (DynamicSecretRedshiftModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretRedshiftModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretRedshift", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretRedshiftResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretRedshiftModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-redshift")
	if !plan.CreationStatements.IsNull() && !plan.CreationStatements.IsUnknown() {
		v := plan.CreationStatements.ValueString()
		body.SetCreationStatements(&v)
	}
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.PasswordLength.IsNull() && !plan.PasswordLength.IsUnknown() {
		v := plan.PasswordLength.ValueString()
		body.SetPasswordLength(&v)
	}
	if !plan.ProducerEncryptionKey.IsNull() && !plan.ProducerEncryptionKey.IsUnknown() {
		v := plan.ProducerEncryptionKey.ValueString()
		body.SetProducerEncryptionKey(&v)
	}
	if !plan.RedshiftDbName.IsNull() && !plan.RedshiftDbName.IsUnknown() {
		v := plan.RedshiftDbName.ValueString()
		body.SetRedshiftDbName(&v)
	}
	if !plan.RedshiftHost.IsNull() && !plan.RedshiftHost.IsUnknown() {
		v := plan.RedshiftHost.ValueString()
		body.SetRedshiftHost(&v)
	}
	if !plan.RedshiftPassword.IsNull() && !plan.RedshiftPassword.IsUnknown() {
		v := plan.RedshiftPassword.ValueString()
		body.SetRedshiftPassword(&v)
	}
	if !plan.RedshiftPort.IsNull() && !plan.RedshiftPort.IsUnknown() {
		v := plan.RedshiftPort.ValueString()
		body.SetRedshiftPort(&v)
	}
	if !plan.RedshiftUsername.IsNull() && !plan.RedshiftUsername.IsUnknown() {
		v := plan.RedshiftUsername.ValueString()
		body.SetRedshiftUsername(&v)
	}
	if !plan.Ssl.IsNull() && !plan.Ssl.IsUnknown() {
		v := plan.Ssl.ValueBool()
		body.SetSsl(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretRedshift")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretRedshift", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretRedshiftResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretRedshiftModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretRedshift", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretRedshift", err.Error())
		return
	}
}

func (r *DynamicSecretRedshiftResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
