// Code generated by terraform-forge. DO NOT EDIT.

package resources_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccAuthMethodOci_basic(t *testing.T) {
	rName := fmt.Sprintf("tf-test-%s", acctest.RandStringFromCharSet(10, acctest.CharSetAlphaNum))

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read
			{
				Config: testAccAuthMethodOciConfig_basic(rName),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("akeyless_auth_method_oci.test", "name", rName),
				),
			},
			// ImportState
			{
				ResourceName:      "akeyless_auth_method_oci.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccAuthMethodOciConfig_basic(name string) string {
	return fmt.Sprintf(`
resource "akeyless_auth_method_oci" "test" {
  name = "%s"
  # TODO: Add required fields
}
`, name)
}
