// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &DynamicSecretK8sResource{}
	_ resource.ResourceWithConfigure   = &DynamicSecretK8sResource{}
	_ resource.ResourceWithImportState = &DynamicSecretK8sResource{}
)

type DynamicSecretK8sResource struct {
	client *AkeylessClient
}

func NewDynamicSecretK8sResource() resource.Resource {
	return &DynamicSecretK8sResource{}
}

type DynamicSecretK8sModel struct {
	CustomUsernameTemplate types.String `tfsdk:"custom_username_template"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ItemCustomFields types.Map `tfsdk:"item_custom_fields"`
	K8sAllowedNamespaces types.String `tfsdk:"k8s_allowed_namespaces"`
	K8sClusterCaCert types.String `tfsdk:"k8s_cluster_ca_cert"`
	K8sClusterEndpoint types.String `tfsdk:"k8s_cluster_endpoint"`
	K8sClusterName types.String `tfsdk:"k8s_cluster_name"`
	K8sClusterToken types.String `tfsdk:"k8s_cluster_token"`
	K8sNamespace types.String `tfsdk:"k8s_namespace"`
	K8sPredefinedRoleName types.String `tfsdk:"k8s_predefined_role_name"`
	K8sPredefinedRoleType types.String `tfsdk:"k8s_predefined_role_type"`
	K8sRolebindingYamlData types.String `tfsdk:"k8s_rolebinding_yaml_data"`
	K8sRolebindingYamlDef types.String `tfsdk:"k8s_rolebinding_yaml_def"`
	K8sServiceAccount types.String `tfsdk:"k8s_service_account"`
	K8sServiceAccountType types.String `tfsdk:"k8s_service_account_type"`
	Name types.String `tfsdk:"name"`
	ProducerEncryptionKeyName types.String `tfsdk:"producer_encryption_key_name"`
	SecureAccessAllowPortForwading types.Bool `tfsdk:"secure_access_allow_port_forwading"`
	SecureAccessClusterEndpoint types.String `tfsdk:"secure_access_cluster_endpoint"`
	SecureAccessDashboardUrl types.String `tfsdk:"secure_access_dashboard_url"`
	SecureAccessDelay types.Int64 `tfsdk:"secure_access_delay"`
	Tags types.Set `tfsdk:"tags"`
	TargetName types.String `tfsdk:"target_name"`
	UseGwServiceAccount types.Bool `tfsdk:"use_gw_service_account"`
	UserTtl types.String `tfsdk:"user_ttl"`
}

func (r *DynamicSecretK8sResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dynamic_secret_k8s"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_username_template": schema.StringAttribute{
				Description: "Customize how temporary usernames are generated using go template",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"item_custom_fields": schema.MapAttribute{
				Description: "Additional custom fields to associate with the item",
				Optional: true,
				ElementType: types.StringType{},
			},
			"k8s_allowed_namespaces": schema.StringAttribute{
				Description: "Allowed Kubernetes namespaces (comma-separated)",
				Optional: true,
			},
			"k8s_cluster_ca_cert": schema.StringAttribute{
				Description: "Kubernetes cluster CA certificate (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"k8s_cluster_endpoint": schema.StringAttribute{
				Description: "Kubernetes API server URL",
				Optional: true,
			},
			"k8s_cluster_name": schema.StringAttribute{
				Description: "K8S cluster name",
				Optional: true,
			},
			"k8s_cluster_token": schema.StringAttribute{
				Description: "Kubernetes bearer token",
				Optional: true,
				Sensitive: true,
			},
			"k8s_namespace": schema.StringAttribute{
				Description: "Kubernetes namespace",
				Optional: true,
			},
			"k8s_predefined_role_name": schema.StringAttribute{
				Description: "The pre-existing Role or ClusterRole name to bind the generated ServiceAccount to (relevant only for k8s-service-account-type=dynamic)",
				Optional: true,
			},
			"k8s_predefined_role_type": schema.StringAttribute{
				Description: "Specifies the type of the pre-existing K8S role [Role, ClusterRole] (relevant only for k8s-service-account-type=dynamic)",
				Optional: true,
			},
			"k8s_rolebinding_yaml_data": schema.StringAttribute{
				Description: "Content of the yaml in a Base64 format.",
				Optional: true,
			},
			"k8s_rolebinding_yaml_def": schema.StringAttribute{
				Description: "Path to yaml file that contains definitions of K8S role and role binding (relevant only for k8s-service-account-type=dynamic)",
				Optional: true,
			},
			"k8s_service_account": schema.StringAttribute{
				Description: "Kubernetes service account name",
				Optional: true,
			},
			"k8s_service_account_type": schema.StringAttribute{
				Description: "K8S ServiceAccount type [fixed, dynamic].",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Dynamic secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"producer_encryption_key_name": schema.StringAttribute{
				Description: "Dynamic producer encryption key",
				Optional: true,
			},
			"secure_access_allow_port_forwading": schema.BoolAttribute{
				Description: "Enable Port forwarding while using CLI access",
				Optional: true,
			},
			"secure_access_cluster_endpoint": schema.StringAttribute{
				Description: "The K8s cluster endpoint URL",
				Optional: true,
			},
			"secure_access_dashboard_url": schema.StringAttribute{
				Description: "The K8s dashboard url",
				Optional: true,
			},
			"secure_access_delay": schema.Int64Attribute{
				Description: "The delay duration, in seconds, to wait after generating just-in-time credentials. Accepted range: 0-120 seconds",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Tags for the producer",
				Optional: true,
				ElementType: types.StringType{},
			},
			"target_name": schema.StringAttribute{
				Description: "Target name associated with this producer",
				Optional: true,
			},
			"use_gw_service_account": schema.BoolAttribute{
				Description: "Use the GW's service account",
				Optional: true,
			},
			"user_ttl": schema.StringAttribute{
				Description: "User TTL (e.g., 60m, 12h)",
				Optional: true,
			},
		},
	}
}

func (r *DynamicSecretK8sResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *DynamicSecretK8sResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan DynamicSecretK8sModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/dynamic-secret-create-k8s")

	// Set custom_username_template
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set item_custom_fields
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}

	// Set k8s_allowed_namespaces
	if !plan.K8sAllowedNamespaces.IsNull() && !plan.K8sAllowedNamespaces.IsUnknown() {
		v := plan.K8sAllowedNamespaces.ValueString()
		body.SetK8sAllowedNamespaces(&v)
	}

	// Set k8s_cluster_ca_cert
	if !plan.K8sClusterCaCert.IsNull() && !plan.K8sClusterCaCert.IsUnknown() {
		v := plan.K8sClusterCaCert.ValueString()
		body.SetK8sClusterCaCert(&v)
	}

	// Set k8s_cluster_endpoint
	if !plan.K8sClusterEndpoint.IsNull() && !plan.K8sClusterEndpoint.IsUnknown() {
		v := plan.K8sClusterEndpoint.ValueString()
		body.SetK8sClusterEndpoint(&v)
	}

	// Set k8s_cluster_name
	if !plan.K8sClusterName.IsNull() && !plan.K8sClusterName.IsUnknown() {
		v := plan.K8sClusterName.ValueString()
		body.SetK8sClusterName(&v)
	}

	// Set k8s_cluster_token
	if !plan.K8sClusterToken.IsNull() && !plan.K8sClusterToken.IsUnknown() {
		v := plan.K8sClusterToken.ValueString()
		body.SetK8sClusterToken(&v)
	}

	// Set k8s_namespace
	if !plan.K8sNamespace.IsNull() && !plan.K8sNamespace.IsUnknown() {
		v := plan.K8sNamespace.ValueString()
		body.SetK8sNamespace(&v)
	}

	// Set k8s_predefined_role_name
	if !plan.K8sPredefinedRoleName.IsNull() && !plan.K8sPredefinedRoleName.IsUnknown() {
		v := plan.K8sPredefinedRoleName.ValueString()
		body.SetK8sPredefinedRoleName(&v)
	}

	// Set k8s_predefined_role_type
	if !plan.K8sPredefinedRoleType.IsNull() && !plan.K8sPredefinedRoleType.IsUnknown() {
		v := plan.K8sPredefinedRoleType.ValueString()
		body.SetK8sPredefinedRoleType(&v)
	}

	// Set k8s_rolebinding_yaml_data
	if !plan.K8sRolebindingYamlData.IsNull() && !plan.K8sRolebindingYamlData.IsUnknown() {
		v := plan.K8sRolebindingYamlData.ValueString()
		body.SetK8sRolebindingYamlData(&v)
	}

	// Set k8s_rolebinding_yaml_def
	if !plan.K8sRolebindingYamlDef.IsNull() && !plan.K8sRolebindingYamlDef.IsUnknown() {
		v := plan.K8sRolebindingYamlDef.ValueString()
		body.SetK8sRolebindingYamlDef(&v)
	}

	// Set k8s_service_account
	if !plan.K8sServiceAccount.IsNull() && !plan.K8sServiceAccount.IsUnknown() {
		v := plan.K8sServiceAccount.ValueString()
		body.SetK8sServiceAccount(&v)
	}

	// Set k8s_service_account_type
	if !plan.K8sServiceAccountType.IsNull() && !plan.K8sServiceAccountType.IsUnknown() {
		v := plan.K8sServiceAccountType.ValueString()
		body.SetK8sServiceAccountType(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set producer_encryption_key_name
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}

	// Set secure_access_allow_port_forwading
	if !plan.SecureAccessAllowPortForwading.IsNull() && !plan.SecureAccessAllowPortForwading.IsUnknown() {
		v := plan.SecureAccessAllowPortForwading.ValueBool()
		body.SetSecureAccessAllowPortForwading(&v)
	}

	// Set secure_access_cluster_endpoint
	if !plan.SecureAccessClusterEndpoint.IsNull() && !plan.SecureAccessClusterEndpoint.IsUnknown() {
		v := plan.SecureAccessClusterEndpoint.ValueString()
		body.SetSecureAccessClusterEndpoint(&v)
	}

	// Set secure_access_dashboard_url
	if !plan.SecureAccessDashboardUrl.IsNull() && !plan.SecureAccessDashboardUrl.IsUnknown() {
		v := plan.SecureAccessDashboardUrl.ValueString()
		body.SetSecureAccessDashboardUrl(&v)
	}

	// Set secure_access_delay
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set target_name
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}

	// Set use_gw_service_account
	if !plan.UseGwServiceAccount.IsNull() && !plan.UseGwServiceAccount.IsUnknown() {
		v := plan.UseGwServiceAccount.ValueBool()
		body.SetUseGwServiceAccount(&v)
	}

	// Set user_ttl
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Creating DynamicSecretK8s")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating DynamicSecretK8s", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretK8sResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state DynamicSecretK8sModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretK8sResource) readResource(ctx context.Context, id string) (DynamicSecretK8sModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state DynamicSecretK8sModel

	body := akeyless_api.NewReadBody("/dynamic-secret-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading DynamicSecretK8s", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_targets_assoc.0.target_name"); ok {
		state.TargetName = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "user_ttl"); ok {
		state.UserTtl = types.StringValue(v)
	}

	return state, diags
}

func (r *DynamicSecretK8sResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan DynamicSecretK8sModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/dynamic-secret-update-k8s")
	if !plan.CustomUsernameTemplate.IsNull() && !plan.CustomUsernameTemplate.IsUnknown() {
		v := plan.CustomUsernameTemplate.ValueString()
		body.SetCustomUsernameTemplate(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ItemCustomFields.IsNull() && !plan.ItemCustomFields.IsUnknown() {
		// TODO: handle ItemCustomFields (types.Map)
	}
	if !plan.K8sAllowedNamespaces.IsNull() && !plan.K8sAllowedNamespaces.IsUnknown() {
		v := plan.K8sAllowedNamespaces.ValueString()
		body.SetK8sAllowedNamespaces(&v)
	}
	if !plan.K8sClusterCaCert.IsNull() && !plan.K8sClusterCaCert.IsUnknown() {
		v := plan.K8sClusterCaCert.ValueString()
		body.SetK8sClusterCaCert(&v)
	}
	if !plan.K8sClusterEndpoint.IsNull() && !plan.K8sClusterEndpoint.IsUnknown() {
		v := plan.K8sClusterEndpoint.ValueString()
		body.SetK8sClusterEndpoint(&v)
	}
	if !plan.K8sClusterName.IsNull() && !plan.K8sClusterName.IsUnknown() {
		v := plan.K8sClusterName.ValueString()
		body.SetK8sClusterName(&v)
	}
	if !plan.K8sClusterToken.IsNull() && !plan.K8sClusterToken.IsUnknown() {
		v := plan.K8sClusterToken.ValueString()
		body.SetK8sClusterToken(&v)
	}
	if !plan.K8sNamespace.IsNull() && !plan.K8sNamespace.IsUnknown() {
		v := plan.K8sNamespace.ValueString()
		body.SetK8sNamespace(&v)
	}
	if !plan.K8sPredefinedRoleName.IsNull() && !plan.K8sPredefinedRoleName.IsUnknown() {
		v := plan.K8sPredefinedRoleName.ValueString()
		body.SetK8sPredefinedRoleName(&v)
	}
	if !plan.K8sPredefinedRoleType.IsNull() && !plan.K8sPredefinedRoleType.IsUnknown() {
		v := plan.K8sPredefinedRoleType.ValueString()
		body.SetK8sPredefinedRoleType(&v)
	}
	if !plan.K8sRolebindingYamlData.IsNull() && !plan.K8sRolebindingYamlData.IsUnknown() {
		v := plan.K8sRolebindingYamlData.ValueString()
		body.SetK8sRolebindingYamlData(&v)
	}
	if !plan.K8sRolebindingYamlDef.IsNull() && !plan.K8sRolebindingYamlDef.IsUnknown() {
		v := plan.K8sRolebindingYamlDef.ValueString()
		body.SetK8sRolebindingYamlDef(&v)
	}
	if !plan.K8sServiceAccount.IsNull() && !plan.K8sServiceAccount.IsUnknown() {
		v := plan.K8sServiceAccount.ValueString()
		body.SetK8sServiceAccount(&v)
	}
	if !plan.K8sServiceAccountType.IsNull() && !plan.K8sServiceAccountType.IsUnknown() {
		v := plan.K8sServiceAccountType.ValueString()
		body.SetK8sServiceAccountType(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProducerEncryptionKeyName.IsNull() && !plan.ProducerEncryptionKeyName.IsUnknown() {
		v := plan.ProducerEncryptionKeyName.ValueString()
		body.SetProducerEncryptionKeyName(&v)
	}
	if !plan.SecureAccessAllowPortForwading.IsNull() && !plan.SecureAccessAllowPortForwading.IsUnknown() {
		v := plan.SecureAccessAllowPortForwading.ValueBool()
		body.SetSecureAccessAllowPortForwading(&v)
	}
	if !plan.SecureAccessClusterEndpoint.IsNull() && !plan.SecureAccessClusterEndpoint.IsUnknown() {
		v := plan.SecureAccessClusterEndpoint.ValueString()
		body.SetSecureAccessClusterEndpoint(&v)
	}
	if !plan.SecureAccessDashboardUrl.IsNull() && !plan.SecureAccessDashboardUrl.IsUnknown() {
		v := plan.SecureAccessDashboardUrl.ValueString()
		body.SetSecureAccessDashboardUrl(&v)
	}
	if !plan.SecureAccessDelay.IsNull() && !plan.SecureAccessDelay.IsUnknown() {
		v := plan.SecureAccessDelay.ValueInt64()
		body.SetSecureAccessDelay(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.TargetName.IsNull() && !plan.TargetName.IsUnknown() {
		v := plan.TargetName.ValueString()
		body.SetTargetName(&v)
	}
	if !plan.UseGwServiceAccount.IsNull() && !plan.UseGwServiceAccount.IsUnknown() {
		v := plan.UseGwServiceAccount.ValueBool()
		body.SetUseGwServiceAccount(&v)
	}
	if !plan.UserTtl.IsNull() && !plan.UserTtl.IsUnknown() {
		v := plan.UserTtl.ValueString()
		body.SetUserTtl(&v)
	}

	tflog.Debug(ctx, "Updating DynamicSecretK8s")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating DynamicSecretK8s", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *DynamicSecretK8sResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state DynamicSecretK8sModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/dynamic-secret-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting DynamicSecretK8s", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting DynamicSecretK8s", err.Error())
		return
	}
}

func (r *DynamicSecretK8sResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
