// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetK8sResource{}
	_ resource.ResourceWithConfigure   = &TargetK8sResource{}
	_ resource.ResourceWithImportState = &TargetK8sResource{}
)

type TargetK8sResource struct {
	client *AkeylessClient
}

func NewTargetK8sResource() resource.Resource {
	return &TargetK8sResource{}
}

type TargetK8sModel struct {
	Description types.String `tfsdk:"description"`
	K8sAuthType types.String `tfsdk:"k8s_auth_type"`
	K8sClientCertificate types.String `tfsdk:"k8s_client_certificate"`
	K8sClientKey types.String `tfsdk:"k8s_client_key"`
	K8sClusterCaCert types.String `tfsdk:"k8s_cluster_ca_cert"`
	K8sClusterEndpoint types.String `tfsdk:"k8s_cluster_endpoint"`
	K8sClusterName types.String `tfsdk:"k8s_cluster_name"`
	K8sClusterToken types.String `tfsdk:"k8s_cluster_token"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	UseGwServiceAccount types.Bool `tfsdk:"use_gw_service_account"`
}

func (r *TargetK8sResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_k8s"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"k8s_auth_type": schema.StringAttribute{
				Description: "Kubernetes auth type: token, certificate, or password",
				Optional: true,
			},
			"k8s_client_certificate": schema.StringAttribute{
				Description: "Kubernetes client certificate (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"k8s_client_key": schema.StringAttribute{
				Description: "Kubernetes client key (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"k8s_cluster_ca_cert": schema.StringAttribute{
				Description: "Kubernetes cluster CA certificate (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"k8s_cluster_endpoint": schema.StringAttribute{
				Description: "Kubernetes API server URL",
				Optional: true,
			},
			"k8s_cluster_name": schema.StringAttribute{
				Description: "K8S cluster name",
				Optional: true,
			},
			"k8s_cluster_token": schema.StringAttribute{
				Description: "Kubernetes bearer token",
				Optional: true,
				Sensitive: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"use_gw_service_account": schema.BoolAttribute{
				Description: "Use gateway service account for authentication",
				Optional: true,
			},
		},
	}
}

func (r *TargetK8sResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetK8sResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetK8sModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-k8s")

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set k8s_auth_type
	if !plan.K8sAuthType.IsNull() && !plan.K8sAuthType.IsUnknown() {
		v := plan.K8sAuthType.ValueString()
		body.SetK8sAuthType(&v)
	}

	// Set k8s_client_certificate
	if !plan.K8sClientCertificate.IsNull() && !plan.K8sClientCertificate.IsUnknown() {
		v := plan.K8sClientCertificate.ValueString()
		body.SetK8sClientCertificate(&v)
	}

	// Set k8s_client_key
	if !plan.K8sClientKey.IsNull() && !plan.K8sClientKey.IsUnknown() {
		v := plan.K8sClientKey.ValueString()
		body.SetK8sClientKey(&v)
	}

	// Set k8s_cluster_ca_cert
	if !plan.K8sClusterCaCert.IsNull() && !plan.K8sClusterCaCert.IsUnknown() {
		v := plan.K8sClusterCaCert.ValueString()
		body.SetK8sClusterCaCert(&v)
	}

	// Set k8s_cluster_endpoint
	if !plan.K8sClusterEndpoint.IsNull() && !plan.K8sClusterEndpoint.IsUnknown() {
		v := plan.K8sClusterEndpoint.ValueString()
		body.SetK8sClusterEndpoint(&v)
	}

	// Set k8s_cluster_name
	if !plan.K8sClusterName.IsNull() && !plan.K8sClusterName.IsUnknown() {
		v := plan.K8sClusterName.ValueString()
		body.SetK8sClusterName(&v)
	}

	// Set k8s_cluster_token
	if !plan.K8sClusterToken.IsNull() && !plan.K8sClusterToken.IsUnknown() {
		v := plan.K8sClusterToken.ValueString()
		body.SetK8sClusterToken(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set use_gw_service_account
	if !plan.UseGwServiceAccount.IsNull() && !plan.UseGwServiceAccount.IsUnknown() {
		v := plan.UseGwServiceAccount.ValueBool()
		body.SetUseGwServiceAccount(&v)
	}

	tflog.Debug(ctx, "Creating TargetK8s")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetK8s", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetK8sResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetK8sModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetK8sResource) readResource(ctx context.Context, id string) (TargetK8sModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetK8sModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetK8s", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetK8sResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetK8sModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-k8s")
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.K8sAuthType.IsNull() && !plan.K8sAuthType.IsUnknown() {
		v := plan.K8sAuthType.ValueString()
		body.SetK8sAuthType(&v)
	}
	if !plan.K8sClientCertificate.IsNull() && !plan.K8sClientCertificate.IsUnknown() {
		v := plan.K8sClientCertificate.ValueString()
		body.SetK8sClientCertificate(&v)
	}
	if !plan.K8sClientKey.IsNull() && !plan.K8sClientKey.IsUnknown() {
		v := plan.K8sClientKey.ValueString()
		body.SetK8sClientKey(&v)
	}
	if !plan.K8sClusterCaCert.IsNull() && !plan.K8sClusterCaCert.IsUnknown() {
		v := plan.K8sClusterCaCert.ValueString()
		body.SetK8sClusterCaCert(&v)
	}
	if !plan.K8sClusterEndpoint.IsNull() && !plan.K8sClusterEndpoint.IsUnknown() {
		v := plan.K8sClusterEndpoint.ValueString()
		body.SetK8sClusterEndpoint(&v)
	}
	if !plan.K8sClusterName.IsNull() && !plan.K8sClusterName.IsUnknown() {
		v := plan.K8sClusterName.ValueString()
		body.SetK8sClusterName(&v)
	}
	if !plan.K8sClusterToken.IsNull() && !plan.K8sClusterToken.IsUnknown() {
		v := plan.K8sClusterToken.ValueString()
		body.SetK8sClusterToken(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.UseGwServiceAccount.IsNull() && !plan.UseGwServiceAccount.IsUnknown() {
		v := plan.UseGwServiceAccount.ValueBool()
		body.SetUseGwServiceAccount(&v)
	}

	tflog.Debug(ctx, "Updating TargetK8s")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetK8s", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetK8sResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetK8sModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetK8s", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetK8s", err.Error())
		return
	}
}

func (r *TargetK8sResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
