// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &TargetGitlabResource{}
	_ resource.ResourceWithConfigure   = &TargetGitlabResource{}
	_ resource.ResourceWithImportState = &TargetGitlabResource{}
)

type TargetGitlabResource struct {
	client *AkeylessClient
}

func NewTargetGitlabResource() resource.Resource {
	return &TargetGitlabResource{}
}

type TargetGitlabModel struct {
	Description types.String `tfsdk:"description"`
	GitlabAccessToken types.String `tfsdk:"gitlab_access_token"`
	GitlabCertificate types.String `tfsdk:"gitlab_certificate"`
	GitlabUrl types.String `tfsdk:"gitlab_url"`
	Key types.String `tfsdk:"key"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
}

func (r *TargetGitlabResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_target_gitlab"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Description: "Target description",
				Optional: true,
			},
			"gitlab_access_token": schema.StringAttribute{
				Description: "GitLab personal access token",
				Optional: true,
				Sensitive: true,
			},
			"gitlab_certificate": schema.StringAttribute{
				Description: "GitLab TLS certificate (PEM)",
				Optional: true,
				Sensitive: true,
			},
			"gitlab_url": schema.StringAttribute{
				Description: "GitLab URL (for self-hosted)",
				Optional: true,
			},
			"key": schema.StringAttribute{
				Description: "The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Target name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

func (r *TargetGitlabResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TargetGitlabResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TargetGitlabModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/target-create-gitlab")

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set gitlab_access_token
	if !plan.GitlabAccessToken.IsNull() && !plan.GitlabAccessToken.IsUnknown() {
		v := plan.GitlabAccessToken.ValueString()
		body.SetGitlabAccessToken(&v)
	}

	// Set gitlab_certificate
	if !plan.GitlabCertificate.IsNull() && !plan.GitlabCertificate.IsUnknown() {
		v := plan.GitlabCertificate.ValueString()
		body.SetGitlabCertificate(&v)
	}

	// Set gitlab_url
	if !plan.GitlabUrl.IsNull() && !plan.GitlabUrl.IsUnknown() {
		v := plan.GitlabUrl.ValueString()
		body.SetGitlabUrl(&v)
	}

	// Set key
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	tflog.Debug(ctx, "Creating TargetGitlab")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating TargetGitlab", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetGitlabResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TargetGitlabModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetGitlabResource) readResource(ctx context.Context, id string) (TargetGitlabModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state TargetGitlabModel

	body := akeyless_api.NewReadBody("/target-get")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading TargetGitlab", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "comment"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "target_name"); ok {
		state.Name = types.StringValue(v)
	}

	return state, diags
}

func (r *TargetGitlabResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TargetGitlabModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/target-update-gitlab")
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.GitlabAccessToken.IsNull() && !plan.GitlabAccessToken.IsUnknown() {
		v := plan.GitlabAccessToken.ValueString()
		body.SetGitlabAccessToken(&v)
	}
	if !plan.GitlabCertificate.IsNull() && !plan.GitlabCertificate.IsUnknown() {
		v := plan.GitlabCertificate.ValueString()
		body.SetGitlabCertificate(&v)
	}
	if !plan.GitlabUrl.IsNull() && !plan.GitlabUrl.IsUnknown() {
		v := plan.GitlabUrl.ValueString()
		body.SetGitlabUrl(&v)
	}
	if !plan.Key.IsNull() && !plan.Key.IsUnknown() {
		v := plan.Key.ValueString()
		body.SetKey(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	tflog.Debug(ctx, "Updating TargetGitlab")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating TargetGitlab", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TargetGitlabResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TargetGitlabModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/target-delete")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting TargetGitlab", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting TargetGitlab", err.Error())
		return
	}
}

func (r *TargetGitlabResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
