// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &AuthMethodOciResource{}
	_ resource.ResourceWithConfigure   = &AuthMethodOciResource{}
	_ resource.ResourceWithImportState = &AuthMethodOciResource{}
)

type AuthMethodOciResource struct {
	client *AkeylessClient
}

func NewAuthMethodOciResource() resource.Resource {
	return &AuthMethodOciResource{}
}

type AuthMethodOciModel struct {
	AccessExpires types.Int64 `tfsdk:"access_expires"`
	AllowedClientType types.Set `tfsdk:"allowed_client_type"`
	AuditLogsClaims types.Set `tfsdk:"audit_logs_claims"`
	BoundIps types.Set `tfsdk:"bound_ips"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	ExpirationEventIn types.Set `tfsdk:"expiration_event_in"`
	ForceSubClaims types.Bool `tfsdk:"force_sub_claims"`
	GroupOcid types.Set `tfsdk:"group_ocid"`
	GwBoundIps types.Set `tfsdk:"gw_bound_ips"`
	JwtTtl types.Int64 `tfsdk:"jwt_ttl"`
	Name types.String `tfsdk:"name"`
	ProductType types.Set `tfsdk:"product_type"`
	TenantOcid types.String `tfsdk:"tenant_ocid"`
}

func (r *AuthMethodOciResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_auth_method_oci"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_expires": schema.Int64Attribute{
				Description: "Access expiration in Unix time (0 = no expiry)",
				Optional: true,
			},
			"allowed_client_type": schema.SetAttribute{
				Description: "limit the auth method usage for specific client types [cli,ui,gateway-admin,sdk,mobile,extension]",
				Optional: true,
				ElementType: types.StringType{},
			},
			"audit_logs_claims": schema.SetAttribute{
				Description: "Subclaims to include in audit logs, e.g \"--audit-logs-claims email --audit-logs-claims username\"",
				Optional: true,
				ElementType: types.StringType{},
			},
			"bound_ips": schema.SetAttribute{
				Description: "CIDR whitelist for access",
				Optional: true,
				ElementType: types.StringType{},
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Auth Method description",
				Optional: true,
			},
			"expiration_event_in": schema.SetAttribute{
				Description: "How many days before the expiration of the auth method would you like to be notified.",
				Optional: true,
				ElementType: types.StringType{},
			},
			"force_sub_claims": schema.BoolAttribute{
				Description: "Force sub-claims enforcement",
				Optional: true,
			},
			"group_ocid": schema.SetAttribute{
				Description: "OCI group OCIDs to restrict access",
				Required: true,
				ElementType: types.StringType{},
			},
			"gw_bound_ips": schema.SetAttribute{
				Description: "Gateway CIDR whitelist",
				Optional: true,
				ElementType: types.StringType{},
			},
			"jwt_ttl": schema.Int64Attribute{
				Description: "JWT TTL in seconds",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Auth Method name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"product_type": schema.SetAttribute{
				Description: "Choose the relevant product type for the auth method [sm, sra, pm, dp, ca]",
				Optional: true,
				ElementType: types.StringType{},
			},
			"tenant_ocid": schema.StringAttribute{
				Description: "OCI tenant OCID",
				Required: true,
			},
		},
	}
}

func (r *AuthMethodOciResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *AuthMethodOciResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan AuthMethodOciModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/auth-method-create-oci")

	// Set access_expires
	if !plan.AccessExpires.IsNull() && !plan.AccessExpires.IsUnknown() {
		v := plan.AccessExpires.ValueInt64()
		body.SetAccessExpires(&v)
	}

	// Set allowed_client_type
	if !plan.AllowedClientType.IsNull() && !plan.AllowedClientType.IsUnknown() {
		body.SetAllowedClientType(expandStringSet(ctx, plan.AllowedClientType))
	}

	// Set audit_logs_claims
	if !plan.AuditLogsClaims.IsNull() && !plan.AuditLogsClaims.IsUnknown() {
		body.SetAuditLogsClaims(expandStringSet(ctx, plan.AuditLogsClaims))
	}

	// Set bound_ips
	if !plan.BoundIps.IsNull() && !plan.BoundIps.IsUnknown() {
		body.SetBoundIps(expandStringSet(ctx, plan.BoundIps))
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set expiration_event_in
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}

	// Set force_sub_claims
	if !plan.ForceSubClaims.IsNull() && !plan.ForceSubClaims.IsUnknown() {
		v := plan.ForceSubClaims.ValueBool()
		body.SetForceSubClaims(&v)
	}

	// Set group_ocid
	if !plan.GroupOcid.IsNull() && !plan.GroupOcid.IsUnknown() {
		body.SetGroupOcid(expandStringSet(ctx, plan.GroupOcid))
	}

	// Set gw_bound_ips
	if !plan.GwBoundIps.IsNull() && !plan.GwBoundIps.IsUnknown() {
		body.SetGwBoundIps(expandStringSet(ctx, plan.GwBoundIps))
	}

	// Set jwt_ttl
	if !plan.JwtTtl.IsNull() && !plan.JwtTtl.IsUnknown() {
		v := plan.JwtTtl.ValueInt64()
		body.SetJwtTtl(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set product_type
	if !plan.ProductType.IsNull() && !plan.ProductType.IsUnknown() {
		body.SetProductType(expandStringSet(ctx, plan.ProductType))
	}

	// Set tenant_ocid
	if !plan.TenantOcid.IsNull() && !plan.TenantOcid.IsUnknown() {
		v := plan.TenantOcid.ValueString()
		body.SetTenantOcid(&v)
	}

	tflog.Debug(ctx, "Creating AuthMethodOci")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating AuthMethodOci", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodOciResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state AuthMethodOciModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodOciResource) readResource(ctx context.Context, id string) (AuthMethodOciModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state AuthMethodOciModel

	body := akeyless_api.NewReadBody("/get-auth-method")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading AuthMethodOci", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "access_info.access_expires"); ok {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			state.AccessExpires = types.Int64Value(n)
		}
	}
	if v, ok := GetNestedString(result, "access_info.force_sub_claims"); ok {
		state.ForceSubClaims = types.BoolValue(v == "true")
	}
	if v, ok := GetNestedStringSlice(result, "access_info.oci_access_rules.group_ocid"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.GroupOcid = setVal
	}
	if v, ok := GetNestedString(result, "access_info.oci_access_rules.tenant_ocid"); ok {
		state.TenantOcid = types.StringValue(v)
	}

	return state, diags
}

func (r *AuthMethodOciResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan AuthMethodOciModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/auth-method-update-oci")
	if !plan.AccessExpires.IsNull() && !plan.AccessExpires.IsUnknown() {
		v := plan.AccessExpires.ValueInt64()
		body.SetAccessExpires(&v)
	}
	if !plan.AllowedClientType.IsNull() && !plan.AllowedClientType.IsUnknown() {
		body.SetAllowedClientType(expandStringSet(ctx, plan.AllowedClientType))
	}
	if !plan.AuditLogsClaims.IsNull() && !plan.AuditLogsClaims.IsUnknown() {
		body.SetAuditLogsClaims(expandStringSet(ctx, plan.AuditLogsClaims))
	}
	if !plan.BoundIps.IsNull() && !plan.BoundIps.IsUnknown() {
		body.SetBoundIps(expandStringSet(ctx, plan.BoundIps))
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.ExpirationEventIn.IsNull() && !plan.ExpirationEventIn.IsUnknown() {
		body.SetExpirationEventIn(expandStringSet(ctx, plan.ExpirationEventIn))
	}
	if !plan.ForceSubClaims.IsNull() && !plan.ForceSubClaims.IsUnknown() {
		v := plan.ForceSubClaims.ValueBool()
		body.SetForceSubClaims(&v)
	}
	if !plan.GroupOcid.IsNull() && !plan.GroupOcid.IsUnknown() {
		body.SetGroupOcid(expandStringSet(ctx, plan.GroupOcid))
	}
	if !plan.GwBoundIps.IsNull() && !plan.GwBoundIps.IsUnknown() {
		body.SetGwBoundIps(expandStringSet(ctx, plan.GwBoundIps))
	}
	if !plan.JwtTtl.IsNull() && !plan.JwtTtl.IsUnknown() {
		v := plan.JwtTtl.ValueInt64()
		body.SetJwtTtl(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProductType.IsNull() && !plan.ProductType.IsUnknown() {
		body.SetProductType(expandStringSet(ctx, plan.ProductType))
	}
	if !plan.TenantOcid.IsNull() && !plan.TenantOcid.IsUnknown() {
		v := plan.TenantOcid.ValueString()
		body.SetTenantOcid(&v)
	}

	tflog.Debug(ctx, "Updating AuthMethodOci")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating AuthMethodOci", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *AuthMethodOciResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state AuthMethodOciModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-auth-method")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting AuthMethodOci", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting AuthMethodOci", err.Error())
		return
	}
}

func (r *AuthMethodOciResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
