// Code generated by terraform-forge. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	akeyless_api "github.com/akeylesslabs/akeyless-go/v5"
)

var (
	_ resource.Resource                = &StaticSecretResource{}
	_ resource.ResourceWithConfigure   = &StaticSecretResource{}
	_ resource.ResourceWithImportState = &StaticSecretResource{}
)

type StaticSecretResource struct {
	client *AkeylessClient
}

func NewStaticSecretResource() resource.Resource {
	return &StaticSecretResource{}
}

type StaticSecretModel struct {
	Accessibility types.String `tfsdk:"accessibility"`
	DeleteProtection types.Bool `tfsdk:"delete_protection"`
	Description types.String `tfsdk:"description"`
	Format types.String `tfsdk:"format"`
	MaxVersions types.String `tfsdk:"max_versions"`
	Name types.String `tfsdk:"name"`
	ProtectionKey types.String `tfsdk:"protection_key"`
	Tags types.Set `tfsdk:"tags"`
	Type types.String `tfsdk:"type"`
	Value types.String `tfsdk:"value"`
}

func (r *StaticSecretResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_static_secret"
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"accessibility": schema.StringAttribute{
				Description: "Secret accessibility: regular or personal",
				Optional: true,
			},
			"delete_protection": schema.BoolAttribute{
				Description: "Enable delete protection",
				Optional: true,
			},
			"description": schema.StringAttribute{
				Description: "Description of the object",
				Optional: true,
			},
			"format": schema.StringAttribute{
				Description: "Secret format [text/json/key-value] (relevant only for type 'generic')",
				Optional: true,
			},
			"max_versions": schema.StringAttribute{
				Description: "Set the maximum number of versions, limited by the account settings defaults.",
				Optional: true,
			},
			"name": schema.StringAttribute{
				Description: "Secret name",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"protection_key": schema.StringAttribute{
				Description: "Encryption key name for the secret",
				Optional: true,
			},
			"tags": schema.SetAttribute{
				Description: "Add tags attached to this object",
				Optional: true,
				ElementType: types.StringType{},
			},
			"type": schema.StringAttribute{
				Description: "The secret sub type [generic/password]",
				Optional: true,
			},
			"value": schema.StringAttribute{
				Description: "The secret value",
				Required: true,
				Sensitive: true,
			},
		},
	}
}

func (r *StaticSecretResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*AkeylessClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *AkeylessClient, got: %T", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *StaticSecretResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan StaticSecretModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewCreateBody("/create-secret")

	// Set accessibility
	if !plan.Accessibility.IsNull() && !plan.Accessibility.IsUnknown() {
		v := plan.Accessibility.ValueString()
		body.SetAccessibility(&v)
	}

	// Set delete_protection
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}

	// Set description
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}

	// Set format
	if !plan.Format.IsNull() && !plan.Format.IsUnknown() {
		v := plan.Format.ValueString()
		body.SetFormat(&v)
	}

	// Set max_versions
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}

	// Set name
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}

	// Set protection_key
	if !plan.ProtectionKey.IsNull() && !plan.ProtectionKey.IsUnknown() {
		v := plan.ProtectionKey.ValueString()
		body.SetProtectionKey(&v)
	}

	// Set tags
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}

	// Set type
	if !plan.Type.IsNull() && !plan.Type.IsUnknown() {
		v := plan.Type.ValueString()
		body.SetType(&v)
	}

	// Set value
	if !plan.Value.IsNull() && !plan.Value.IsUnknown() {
		v := plan.Value.ValueString()
		body.SetValue(&v)
	}

	tflog.Debug(ctx, "Creating StaticSecret")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error creating StaticSecret", err.Error())
		return
	}

	// Read back the resource to populate computed fields
	state, readDiags := r.readResource(ctx, plan.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *StaticSecretResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state StaticSecretModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	refreshed, readDiags := r.readResource(ctx, state.Name.ValueString())
	resp.Diagnostics.Append(readDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &refreshed)
	resp.Diagnostics.Append(diags...)
}

func (r *StaticSecretResource) readResource(ctx context.Context, id string) (StaticSecretModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	var state StaticSecretModel

	body := akeyless_api.NewReadBody("/describe-item")
	body.SetName(&id)

	result, err := r.client.Call(ctx, body)
	if err != nil {
		diags.AddError("Error reading StaticSecret", err.Error())
		return state, diags
	}

	state.Name = types.StringValue(id)
	if v, ok := GetNestedString(result, "delete_protection"); ok {
		state.DeleteProtection = types.BoolValue(v == "true")
	}
	if v, ok := GetNestedString(result, "item_metadata"); ok {
		state.Description = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "item_name"); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := GetNestedString(result, "protection_key_name"); ok {
		state.ProtectionKey = types.StringValue(v)
	}
	if v, ok := GetNestedStringSlice(result, "item_tags"); ok && len(v) > 0 {
		setVal, setDiags := types.SetValueFrom(ctx, types.StringType{}, v)
		diags.Append(setDiags...)
		state.Tags = setVal
	}
	if v, ok := GetNestedString(result, "item_type"); ok {
		state.Type = types.StringValue(v)
	}

	return state, diags
}

func (r *StaticSecretResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan StaticSecretModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewUpdateBody("/update-secret-val")
	if !plan.Accessibility.IsNull() && !plan.Accessibility.IsUnknown() {
		v := plan.Accessibility.ValueString()
		body.SetAccessibility(&v)
	}
	if !plan.DeleteProtection.IsNull() && !plan.DeleteProtection.IsUnknown() {
		v := plan.DeleteProtection.ValueBool()
		body.SetDeleteProtection(&v)
	}
	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		body.SetDescription(&v)
	}
	if !plan.Format.IsNull() && !plan.Format.IsUnknown() {
		v := plan.Format.ValueString()
		body.SetFormat(&v)
	}
	if !plan.MaxVersions.IsNull() && !plan.MaxVersions.IsUnknown() {
		v := plan.MaxVersions.ValueString()
		body.SetMaxVersions(&v)
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		body.SetName(&v)
	}
	if !plan.ProtectionKey.IsNull() && !plan.ProtectionKey.IsUnknown() {
		v := plan.ProtectionKey.ValueString()
		body.SetProtectionKey(&v)
	}
	if !plan.Tags.IsNull() && !plan.Tags.IsUnknown() {
		body.SetTags(expandStringSet(ctx, plan.Tags))
	}
	if !plan.Type.IsNull() && !plan.Type.IsUnknown() {
		v := plan.Type.ValueString()
		body.SetType(&v)
	}
	if !plan.Value.IsNull() && !plan.Value.IsUnknown() {
		v := plan.Value.ValueString()
		body.SetValue(&v)
	}

	tflog.Debug(ctx, "Updating StaticSecret")

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error updating StaticSecret", err.Error())
		return
	}

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *StaticSecretResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state StaticSecretModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	body := akeyless_api.NewDeleteBody("/delete-item")
	id := state.Name.ValueString()
	body.SetName(&id)

	tflog.Debug(ctx, "Deleting StaticSecret", map[string]interface{}{"id": id})

	_, err := r.client.Call(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting StaticSecret", err.Error())
		return
	}
}

func (r *StaticSecretResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
